// spanishLexicon.ts
// Spanish short definitions for Strong's Concordance entries.
//
// Coverage: ~230 entries covering the most common biblical vocabulary.
// Source: curated from standard Spanish biblical lexicons and theological dictionaries.
// Fallback: entries NOT in this map show the English shortDefinition.
//
// Format: Strong ID → Spanish short definition (concise, 1–2 line gloss)

export const SPANISH_LEXICON: Record<string, string> = {

  // ── Hebrew — Antiguo Testamento ────────────────────────────────────────────

  'H1':    'padre, antecesor, progenitor',
  'H120':  'hombre, humanidad; Adán (el de la tierra)',
  'H127':  'tierra cultivable, suelo, terreno',
  'H136':  'Señor soberano, Adonai',
  'H157':  'amar, tener afecto, apreciar',
  'H160':  'amor, afecto',
  'H215':  'brillar, iluminar, dar luz',
  'H216':  'luz, resplandor, claridad',
  'H376':  'hombre, varón, persona',
  'H410':  'Dios (El), el Poderoso, el Fuerte',
  'H430':  'Dios (Elohim), divinidad, seres poderosos',
  'H517':  'madre, origen, fuente de vida',
  'H530':  'fidelidad, firmeza, confianza (emunah)',
  'H539':  'creer, confiar, ser fiel, amén',
  'H543':  'amén, así sea, verdaderamente',
  'H571':  'verdad, fidelidad, integridad (emet)',
  'H653':  'oscuridad, tiniebla profunda',
  'H776':  'tierra, suelo, nación, país',
  'H802':  'mujer, esposa',
  'H1004': 'casa, hogar, familia, templo',
  'H1121': 'hijo, descendiente, miembro de un grupo',
  'H1248': 'hijo primogénito, heredero del trono',
  'H1254': 'crear (bara), producir de la nada',
  'H1288': 'bendecir, arrodillarse, alabar',
  'H1293': 'bendición, don, regalo de Dios',
  'H1350': 'redimir, rescatar, liberar como pariente (goel)',
  'H1353': 'redención, rescate, liberación',
  'H1369': 'fuerza, valentía, poder (guebura)',
  'H1697': 'palabra, asunto, promesa, dabar',
  'H1732': 'David — el amado, el elegido',
  'H1818': 'sangre (dam)',
  'H1847': 'conocimiento, discernimiento, saber (daat)',
  'H1865': 'libertad, liberación, manumisión',
  'H1870': 'camino, senda, modo de vida (derek)',
  'H1964': 'palacio, templo, santuario (hekal)',
  'H1980': 'andar, ir, caminar, vivir (halak)',
  'H2319': 'nuevo, reciente, renovado',
  'H2398': 'pecar, errar, fallar (jata)',
  'H2399': 'pecado, transgresión, error moral',
  'H2403': 'pecado; ofrenda por el pecado (jatatah)',
  'H2416': 'viviente, vivo; vida, criatura',
  'H2421': 'vivir, preservar la vida, dar vida (jayah)',
  'H2425': 'vivir, seguir vivo',
  'H2451': 'sabiduría, prudencia, destreza (jokmah)',
  'H2580': 'gracia, favor, benevolencia (jen)',
  'H2617': 'misericordia, amor leal, bondad inagotable (hesed)',
  'H2623': 'piadoso, fiel, lleno de misericordia',
  'H2822': 'oscuridad, tinieblas, sombra de muerte',
  'H2896': 'bueno, bondadoso, hermoso, agradable',
  'H3045': 'conocer, entender, percibir íntimamente (yada)',
  'H3068': 'YHWH — el Señor eterno, el que es',
  'H3117': 'día, tiempo, período, época (yom)',
  'H3205': 'nacer, dar a luz, engendrar',
  'H3323': 'aceite de oliva virgen',
  'H3444': 'salvación, liberación (yeshuah)',
  'H3467': 'salvar, librar, dar socorro (yasha)',
  'H3468': 'salvación, socorro, liberación',
  'H3513': 'glorificar, honrar, ser pesado (de peso)',
  'H3519': 'gloria, honor, majestad, esplendor (kavod)',
  'H3548': 'sacerdote, ministro del templo (kohen)',
  'H3722': 'expiar, cubrir, reconciliar (kippur)',
  'H3789': 'escribir, inscribir, registrar (katav)',
  'H3820': 'corazón, mente, voluntad (lev)',
  'H3824': 'corazón, interior, centro del ser (levav)',
  'H3915': 'noche, medianoche (layil)',
  'H4159': 'milagro, señal, prodigio (mofet)',
  'H4191': 'morir, matar, perecer (mut)',
  'H4194': 'muerte, fallecimiento (mavet)',
  'H4325': 'agua, aguas (mayim)',
  'H4397': 'ángel, mensajero divino (malak)',
  'H4428': 'rey, gobernante, soberano (melek)',
  'H4467': 'reino, reinado, dominio real (mamlaká)',
  'H4687': 'mandamiento, precepto, mitzvá',
  'H4899': 'ungido, Mesías (mashiaj)',
  'H4941': 'juicio, derecho, justicia (mishpat)',
  'H5012': 'profetizar, hablar en nombre de Dios',
  'H5016': 'profecía, revelación divina',
  'H5030': 'profeta, portavoz de Dios (navi)',
  'H5117': 'reposar, descansar, establecer (nuaj)',
  'H5162': 'arrepentirse, consolarse, cambiar de opinión (naham)',
  'H5315': 'alma, vida, ser viviente (nefesh)',
  'H5414': 'dar, poner, entregar, conceder (natan)',
  'H5545': 'perdonar, absolver, salaj',
  'H5547': 'perdón, capacidad de perdonar',
  'H5650': 'siervo, esclavo (eved)',
  'H5647': 'servir, trabajar, adorar (avad)',
  'H5707': 'testigo (ed)',
  'H5715': 'testimonio, revelación, ley (edut)',
  'H5769': 'eternidad, tiempo indefinido, olam',
  'H6213': 'hacer, fabricar, cumplir (asah)',
  'H6419': 'orar, interceder (palal)',
  'H6662': 'justo, recto (tsadik)',
  'H6664': 'justicia, rectitud (tsedeq)',
  'H6666': 'justicia, acto justo (tsedakah)',
  'H6918': 'santo, consagrado, separado (qadosh)',
  'H6942': 'santificar, consagrar, apartar (qadash)',
  'H6944': 'santidad, lo sagrado, lo dedicado a Dios (qodesh)',
  'H6965': 'levantarse, estar en pie, resucitar (qum)',
  'H7225': 'principio, comienzo, primicia (reshit)',
  'H7307': 'Espíritu, viento, aliento vital (ruah)',
  'H7355': 'mostrar misericordia, tener compasión (rajam)',
  'H7453': 'prójimo, amigo, compañero (rea)',
  'H7462': 'pastorear, apacentar, guiar (raah)',
  'H7473': 'pastor, el que cuida del rebaño',
  'H7495': 'sanar, curar, restaurar (rapha)',
  'H7706': 'Dios Todopoderoso (El Shaddai)',
  'H7725': 'convertirse, regresar, arrepentirse (shuv)',
  'H7760': 'poner, colocar, establecer (sum/sim)',
  'H7812': 'adorar, postrarse, inclinarse (shajah)',
  'H7896': 'poner, colocar, situar (shith)',
  'H7965': 'paz, bienestar, prosperidad, integridad (shalom)',
  'H8034': 'nombre, reputación, fama (shem)',
  'H8057': 'alegría, gozo, júbilo (simjah)',
  'H8064': 'cielos, firmamento (shamayim)',
  'H8085': 'oír, escuchar, obedecer (shema)',
  'H8342': 'gozo, alegría intensa (sasson)',
  'H8398': 'mundo, tierra habitada, tierra firme (tevel)',
  'H8416': 'alabanza, canto de loor (tehilah)',
  'H8451': 'ley, instrucción, enseñanza, Torah',
  'H8605': 'oración, súplica, plegaria (tefilah)',
  'H8615': 'esperanza, expectativa, hilo de esperanza (tiqvah)',

  // ── Greek — Nuevo Testamento ───────────────────────────────────────────────

  'G18':   'bueno, bondadoso, benéfico (agathos)',
  'G25':   'amar con amor incondicional (agapaó)',
  'G26':   'amor ágape — amor incondicional y sacrificial',
  'G32':   'ángel, mensajero celestial (angelos)',
  'G37':   'santificar, consagrar, separar para Dios (hagiazó)',
  'G38':   'santificación, consagración, hagiasmos',
  'G40':   'santo, sagrado; el Espíritu Santo (hagios)',
  'G42':   'santidad, pureza, hagiotes',
  'G129':  'sangre (haima)',
  'G134':  'alabar, elogiar a Dios (aineó)',
  'G165':  'eternidad, era, siglo (aión)',
  'G166':  'eterno, sempiterno, que dura para siempre (aiónios)',
  'G191':  'oír, escuchar, entender (akouó)',
  'G225':  'verdad, realidad (alétheia)',
  'G264':  'pecar, errar, cometer falta (hamartanó)',
  'G266':  'pecado, falla moral (hamartía)',
  'G281':  'amén — verdaderamente, así sea',
  'G386':  'resurrección, anastasis',
  'G450':  'levantarse, resucitar, ponerse en pie (anistemi)',
  'G444':  'hombre, ser humano, persona (anthropos)',
  'G629':  'redención, liberación mediante pago (apolutrosis)',
  'G652':  'apóstol, enviado oficial, representante',
  'G746':  'principio, comienzo, gobernante, autoridad (arjé)',
  'G859':  'perdón, remisión de pecados (aphesis)',
  'G863':  'perdonar, soltar, remitir (aphiemi)',
  'G907':  'bautizar, sumergir en agua',
  'G908':  'bautismo, inmersión, baptisma',
  'G932':  'reino, reinado, dominio (basileia)',
  'G935':  'rey, soberano, monarca (basileus)',
  'G1080': 'engendrar, nacer, dar a luz (gennaó)',
  'G1093': 'tierra, suelo, campo, gé',
  'G1097': 'conocer, comprender, reconocer (ginóskó)',
  'G1108': 'conocimiento, gnosis — comprensión espiritual',
  'G1124': 'escritura sagrada, texto bíblico (grafé)',
  'G1135': 'mujer, esposa (guné)',
  'G1325': 'dar, otorgar, conceder (didómi)',
  'G1342': 'justo, recto, inocente (dikaios)',
  'G1343': 'justicia, rectitud divina (dikaiosyné)',
  'G1391': 'gloria, honor, esplendor, doxa',
  'G1392': 'glorificar, alabar, honrar (doxazó)',
  'G1401': 'siervo, esclavo, doulos',
  'G1411': 'poder, fuerza, milagro (dynamis)',
  'G1515': 'paz, armonía, tranquilidad (eiréné)',
  'G1577': 'iglesia, asamblea de creyentes (ekklesia)',
  'G1655': 'misericordioso, compasivo, eleémon',
  'G1656': 'misericordia, compasión, eleos',
  'G1657': 'libertad, liberación (eleutheria)',
  'G1680': 'esperanza, expectativa confiada (elpis)',
  'G1785': 'mandamiento, precepto (entolé)',
  'G1849': 'autoridad, poder delegado (exousia)',
  'G1867': 'elogiar, alabar, commend (epaineo)',
  'G2098': 'evangelio, buenas noticias (euangelion)',
  'G2127': 'bendecir, hablar bien de (eulogeó)',
  'G2129': 'bendición, alabanza, eulogia',
  'G2198': 'vivir, estar vivo, zaó',
  'G2222': 'vida eterna, vida divina, zóé',
  'G2250': 'día (héméra)',
  'G2288': 'muerte (thanatos)',
  'G2316': 'Dios, la deidad suprema (Theos)',
  'G2323': 'sanar, curar, servir (therapeúó)',
  'G2392': 'sanidad, curación milagrosa (iasis)',
  'G2409': 'sacerdote, ministro del templo (hiereus)',
  'G2424': 'Jesús — el Señor salva, Yeshua',
  'G2434': 'expiación, propiciación, hilasmos',
  'G2537': 'nuevo, renovado, de nueva naturaleza (kainos)',
  'G2588': 'corazón, mente, centro emocional (kardia)',
  'G2842': 'comunión, compañerismo, participación (koinonía)',
  'G2889': 'mundo, universo, orden creado (kosmos)',
  'G2920': 'juicio, veredicto, decisión divina (krisis)',
  'G2936': 'crear, dar existencia (ktizó)',
  'G2937': 'creación, lo creado por Dios (ktisis)',
  'G2962': 'Señor, Maestro, soberano (Kyrios)',
  'G3056': 'Palabra, razón, Verbo divino (Logos)',
  'G3084': 'redimir, liberar mediante rescate (lutróó)',
  'G3101': 'discípulo, alumno, seguidor (mathétés)',
  'G3134': 'Maranata — el Señor viene (arameo)',
  'G3141': 'testimonio, declaración, martyría',
  'G3144': 'testigo, mártir (martys)',
  'G3323': 'Mesías, el Ungido de Dios',
  'G3340': 'arrepentirse, cambiar de mente y dirección (metanoeó)',
  'G3341': 'arrepentimiento, cambio profundo de mente (metánoia)',
  'G3384': 'madre (métér)',
  'G3439': 'unigénito, único en su especie (monogenes)',
  'G3485': 'templo interior, santuario (naos)',
  'G3551': 'ley, norma, código (nomos)',
  'G3571': 'noche (nyx)',
  'G3598': 'camino, senda, ruta (hodos)',
  'G3624': 'casa, hogar, familia, linaje (oikos)',
  'G3686': 'nombre, reputación, persona (onoma)',
  'G3772': 'cielo, firmamento, los cielos (ouranos)',
  'G3841': 'Todopoderoso, Omnipotente (Pantokrátor)',
  'G3962': 'padre, Padre celestial (patér)',
  'G4100': 'creer, confiar, tener fe (pisteuó)',
  'G4102': 'fe, fidelidad, confianza plena (pistis)',
  'G4139': 'prójimo, el que está cerca (plésion)',
  'G4151': 'Espíritu, aliento, Espíritu Santo (pneuma)',
  'G4160': 'hacer, realizar, cumplir, obrar (poieó)',
  'G4165': 'pastorear, apacentar, guiar (poimainó)',
  'G4166': 'pastor, el que cuida el rebaño (poimén)',
  'G4198': 'ir, caminar, vivir, poreuomai',
  'G4335': 'oración, plegaria (proseujé)',
  'G4336': 'orar, rogar a Dios (proseujaomai)',
  'G4352': 'adorar, postrarse ante, proskuneó',
  'G4394': 'profecía, don de revelación (propheteia)',
  'G4395': 'profetizar, hablar por Dios (prophéteuó)',
  'G4396': 'profeta, portavoz de Dios (prophétés)',
  'G4592': 'señal, milagro, señal divina (sémion)',
  'G4655': 'tinieblas, oscuridad espiritual (skotos)',
  'G4678': 'sabiduría divina y práctica (sophia)',
  'G4716': 'cruz, el madero de la crucifixión (stauros)',
  'G4982': 'salvar, librar, sanar, preservar (sózó)',
  'G4991': 'salvación, liberación eterna (sotería)',
  'G4992': 'salvador, el que libra (sótér)',
  'G5204': 'agua (hydór)',
  'G5207': 'hijo, descendiente, heredero (hyios)',
  'G5457': 'luz (phós)',
  'G5479': 'gozo, alegría profunda (jará)',
  'G5485': 'gracia, favor inmerecido de Dios (járis)',
  'G5547': 'Cristo, el Ungido, Mesías en griego (Jristós)',
  'G5590': 'alma, vida, ser interior, psyché',
};

/**
 * Returns the Spanish short definition for a Strong ID, or null if not available.
 * The caller should fall back to the English shortDefinition from the StrongEntry.
 */
export function getSpanishShortDef(strongId: string): string | null {
  return SPANISH_LEXICON[strongId] ?? null;
}
