// Strong's Concordance — Block-based data types
//
// This file defines the shape of entries stored in the JSON block files
// generated by scripts/generate-strong-blocks.ts.
// It is intentionally separate from StrongEntry (the UI type in types.ts)
// so that the block format can evolve independently.

export interface BlockStrongEntry {
  id: string;
  testament: 'OT' | 'NT';
  language: 'Hebrew' | 'Greek';
  lemmaOriginal: string;
  transliteration: string;
  pronunciation?: string;
  grammarCategory: string;
  shortDefinition: string;
  longDefinition: string;
  kjvRenderings: string[];
  occurrencesCount: number;
  relatedVerses: string[];
}

export interface BlockManifestEntry {
  blockId: string;
  lang: 'h' | 'g';
  start: number;
  end: number;
  count: number;
  filename: string;
}
