// Studies catalog — add new studies here as they are downloaded from the repo.
// Process: see SYNC_PROCESS.md

import type { StudyCatalogEntry } from './types';

export const STUDIES_CATALOG: StudyCatalogEntry[] = [
  {
    id: 'mammon_anxiety_freedom_001',
    emoji: '💰',
    title: 'Desatado de las Riquezas',
    subtitle: 'Lo que Jesús dijo hace 2000 años es exactamente lo que necesitas escuchar hoy',
    estimated_reading_minutes: 12,
    imageUrl: 'https://images.unsplash.com/photo-1499063078284-f78f7d89616a?w=800&q=80',
    dataFile: () => require('./data/mammon_anxiety_freedom_es_001.json'),
  },
  {
    id: 'morning_star_001',
    emoji: '⭐',
    title: 'Estrella de la Mañana',
    subtitle: 'El testimonio más poderoso sobre la identidad de Jesús',
    estimated_reading_minutes: 6,
    imageUrl: 'https://images.unsplash.com/photo-1444628838545-ac4016a5418a?w=800&q=80',
    dataFile: () => require('./data/morning_star_es_001.json'),
  },
  {
    id: 'hammer_of_god_001',
    emoji: '🔨',
    title: 'El Martillo de Dios',
    subtitle: 'De ejecutores del juicio a adoradores del Mesías: La historia redentora de los Medos',
    estimated_reading_minutes: 8,
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    dataFile: () => require('./data/hammer_of_god_es_001.json'),
  },
  {
    id: 'balaam_humble_vision_001',
    emoji: '🫏',
    title: 'Cuando la Burra Vio al Ángel y el Profeta Estaba Ciego',
    subtitle: 'La advertencia más solemne sobre revelación sin transformación',
    estimated_reading_minutes: 8,
    imageUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    dataFile: () => require('./data/balaam_humble_vision_es_001.json'),
  },
  {
    id: 'logos_creation_001',
    emoji: '✨',
    title: 'En el Principio era el Verbo',
    subtitle: 'Cuando Juan declara que Jesús es el Logos eterno que creó todas las cosas',
    estimated_reading_minutes: 6,
    imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&q=80',
    dataFile: () => require('./data/logos_creation_es_001.json'),
  },
  {
    id: 'lamb_of_god_001',
    emoji: '🐑',
    title: 'El Cordero de Dios',
    subtitle: 'La culminación de 1,500 años de sistema sacrificial en una sola declaración',
    estimated_reading_minutes: 6,
    imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80',
    dataFile: () => require('./data/lamb_of_god_es_001.json'),
  },
  {
    id: 'natanael_fig_tree_001',
    emoji: '🌿',
    title: 'Debajo de la Higuera',
    subtitle: 'El encuentro donde Jesús revela que conoce tus secretos más profundos',
    estimated_reading_minutes: 6,
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
    dataFile: () => require('./data/natanael_fig_tree_es_001.json'),
  },
  {
    id: 'cana_wedding_001',
    emoji: '🍷',
    title: 'Las Bodas de Caná',
    subtitle: 'Cuando Jesús convierte lo ordinario en extraordinario',
    estimated_reading_minutes: 6,
    imageUrl: 'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=800&q=80',
    dataFile: () => require('./data/cana_wedding_es_001.json'),
  },
  {
    id: 'born_again_001',
    emoji: '🌱',
    title: 'Es Necesario Nacer de Nuevo',
    subtitle: 'El misterio del nuevo nacimiento espiritual revelado',
    estimated_reading_minutes: 6,
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
    dataFile: () => require('./data/born_again_es_001.json'),
  },
  {
    id: 'temple_cleansing_001',
    emoji: '⛪',
    title: 'La Purificación del Templo',
    subtitle: 'Cuando Jesús declara que Él es el Templo verdadero',
    estimated_reading_minutes: 6,
    imageUrl: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80',
    dataFile: () => require('./data/temple_cleansing_es_001.json'),
  },
  {
    id: 'woman_at_well_001',
    emoji: '💧',
    title: 'La Mujer del Pozo',
    subtitle: 'Cuando Jesús rompe todas las barreras por una conversación que cambiará una ciudad',
    estimated_reading_minutes: 5,
    imageUrl: 'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=800&q=80',
    dataFile: () => require('./data/woman_at_well_es_001.json'),
  },
  {
    id: 'i_am_before_abraham_001',
    emoji: '🔥',
    title: 'YO SOY: Antes que Abraham Fuese',
    subtitle: 'Cuando Jesús reclama eternidad y la multitud toma piedras',
    estimated_reading_minutes: 6,
    imageUrl: 'https://images.unsplash.com/photo-1476611338391-6f395a0ebc7b?w=800&q=80',
    dataFile: () => require('./data/i_am_before_abraham_es_001.json'),
  },
  {
    id: 'good_shepherd_001',
    emoji: '🌾',
    title: 'El Buen Pastor',
    subtitle: 'Cuando Jesús declara que conoce a sus ovejas por nombre',
    estimated_reading_minutes: 6,
    imageUrl: 'https://images.unsplash.com/photo-1504215680853-026ed2a45def?w=800&q=80',
    dataFile: () => require('./data/good_shepherd_es_001.json'),
  },
  {
    id: 'jesus_troubled_himself_001',
    emoji: '🤍',
    title: 'Se Turbó a Sí Mismo',
    subtitle: 'Cuando Jesús eligió entrar en nuestro dolor',
    estimated_reading_minutes: 7,
    imageUrl: 'https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=800&q=80',
    dataFile: () => require('./data/jesus_troubled_himself_es_001.json'),
  },
  {
    id: 'passed_from_death_001',
    emoji: '✝️',
    title: 'Pasados de Muerte a Vida',
    subtitle: "La revelación final: ya no puedes 'des-nacer'",
    estimated_reading_minutes: 8,
    imageUrl: 'https://images.unsplash.com/photo-1531907700752-62799b2a3e84?w=800&q=80',
    dataFile: () => require('./data/passed_from_death_es_001.json'),
  },
  {
    id: 'transfiguration_001',
    emoji: '🌤️',
    title: 'La Transfiguración',
    subtitle: 'Cuando el velo de la carne se abre y la gloria irrumpe',
    estimated_reading_minutes: 7,
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
    dataFile: () => require('./data/transfiguration_es_001.json'),
  },
  {
    id: 'buried_talent_001',
    emoji: '💎',
    title: 'El Talento Enterrado',
    subtitle: 'Cuando el miedo paraliza y las manos quedan vacías',
    estimated_reading_minutes: 8,
    imageUrl: 'https://images.unsplash.com/photo-1499529112087-3cb3b73cec95?w=800&q=80',
    dataFile: () => require('./data/buried_talent_es_001.json'),
  },
  {
    id: 'triumphal_entry_001',
    emoji: '🌴',
    title: 'La Entrada Triunfal',
    subtitle: 'Cuando el Rey rechazado entra a Jerusalén montado en un pollino, no en un caballo de guerra',
    estimated_reading_minutes: 5,
    imageUrl: 'https://images.unsplash.com/photo-1510146020680-d9bd32a86754?w=800&q=80',
    dataFile: () => require('./data/triumphal_entry_es_001.json'),
  },
  {
    id: 'gethsemane_agony_001',
    emoji: '🫒',
    title: 'La Agonía del Testador',
    subtitle: 'Cuando el Hijo de Dios suda sangre en la prensa de aceite',
    estimated_reading_minutes: 7,
    imageUrl: 'https://images.unsplash.com/photo-1502657877623-f66bf489d236?w=800&q=80',
    dataFile: () => require('./data/gethsemane_agony_es_001.json'),
  },
  {
    id: 'new_covenant_cup_001',
    emoji: '🫙',
    title: 'La Copa del Nuevo Pacto',
    subtitle: 'Cuando el Testador firma con su sangre el testamento de nuestra libertad',
    estimated_reading_minutes: 7,
    imageUrl: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80',
    dataFile: () => require('./data/new_covenant_cup_es_001.json'),
  },
  {
    id: 'cup_of_wrath_001',
    emoji: '⚡',
    title: 'La Copa de la Ira',
    subtitle: 'Cuando el Inocente bebe el juicio que nos correspondía',
    estimated_reading_minutes: 8,
    imageUrl: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=800&q=80',
    dataFile: () => require('./data/cup_of_wrath_es_001.json'),
  },
  {
    id: 'veil_torn_001',
    emoji: '⛩️',
    title: 'El Velo Rasgado',
    subtitle: 'Cuando Dios abre el camino al Lugar Santísimo',
    estimated_reading_minutes: 7,
    imageUrl: 'https://images.unsplash.com/photo-1548515428-c5c2e0b7b2ae?w=800&q=80',
    dataFile: () => require('./data/veil_torn_es_001.json'),
  },
  {
    id: 'saints_resurrected_001',
    emoji: '🌅',
    title: 'Los Santos Resucitados',
    subtitle: 'Cuando la muerte de Cristo liberó a los cautivos del Hades',
    estimated_reading_minutes: 8,
    imageUrl: 'https://images.unsplash.com/photo-1472120591814-c3f5d50fc5c5?w=800&q=80',
    dataFile: () => require('./data/saints_resurrected_es_001.json'),
  },
  {
    id: 'breath_new_adam_001',
    emoji: '☁️',
    title: 'El Soplo del Nuevo Adán',
    subtitle: 'Cuando Jesús reconecta al hombre con Dios',
    estimated_reading_minutes: 7,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    dataFile: () => require('./data/breath_new_adam_es_001.json'),
  },
  {
    id: 'road_to_emmaus_001',
    emoji: '🛤️',
    title: 'El Camino a Emaús',
    subtitle: 'Cuando el Cristo resucitado camina contigo sin que lo reconozcas, hasta que parte el pan',
    estimated_reading_minutes: 10,
    imageUrl: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=800&q=80',
    dataFile: () => require('./data/road_to_emmaus_es_001.json'),
  },
  {
    id: 'restoration_by_fire_001',
    emoji: '🪵',
    title: 'Las Brasas de la Restauración',
    subtitle: 'Cuando el olor del fracaso se convierte en el aroma del perdón',
    estimated_reading_minutes: 9,
    imageUrl: 'https://images.unsplash.com/photo-1504704911898-68304a7d2807?w=800&q=80',
    dataFile: () => require('./data/restoration_by_fire_es_001.json'),
  },
  {
    id: 'great_commission_001',
    emoji: '🌍',
    title: 'La Gran Comisión',
    subtitle: 'Cuando Jesús transforma a seguidores en enviados',
    estimated_reading_minutes: 6,
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    dataFile: () => require('./data/great_commission_es_001.json'),
  },
  {
    id: 'ascension_victory_001',
    emoji: '🕊️',
    title: 'La Ascensión Victoriosa',
    subtitle: 'Cuando el Rey conquista el trono y envía el Espíritu',
    estimated_reading_minutes: 7,
    imageUrl: 'https://images.unsplash.com/photo-1513553404607-988bf2703777?w=800&q=80',
    dataFile: () => require('./data/ascension_victory_es_001.json'),
  },
  {
    id: 'pentecost_power_001',
    emoji: '🌪️',
    title: 'El Poder de Pentecostés',
    subtitle: 'Cuando el Espíritu Santo transforma cobardes en valientes',
    estimated_reading_minutes: 7,
    imageUrl: 'https://images.unsplash.com/photo-1476820865390-c52aeebb9891?w=800&q=80',
    dataFile: () => require('./data/pentecost_power_es_001.json'),
  },
  {
    id: 'damascus_road_001',
    emoji: '🌟',
    title: 'El Camino a Damasco',
    subtitle: 'Cuando la luz de Cristo derriba al perseguidor más feroz',
    estimated_reading_minutes: 7,
    imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&q=80',
    dataFile: () => require('./data/damascus_road_es_001.json'),
  },
  {
    id: 'gold_silver_ashes_001',
    emoji: '🏆',
    title: 'Oro, Plata o Cenizas',
    subtitle: 'Cuando el fuego prueba la calidad de tu obra',
    estimated_reading_minutes: 7,
    imageUrl: 'https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?w=800&q=80',
    dataFile: () => require('./data/gold_silver_ashes_es_001.json'),
  },
  {
    id: 'zechariah_14_return_001',
    emoji: '🏔️',
    title: 'Zacarías 14: Cuando Sus Pies Toquen el Monte de los Olivos',
    subtitle: 'El día en que el cielo desciende y la tierra es transformada',
    estimated_reading_minutes: 9,
    imageUrl: 'https://images.unsplash.com/photo-1467472899956-f32a29d64394?w=800&q=80',
    dataFile: () => require('./data/zechariah_14_return_es_001.json'),
  },
  {
    id: 'full_hands_king_001',
    emoji: '👑',
    title: 'Manos Llenas para el Rey',
    subtitle: 'Cuando el Alfa y la Omega trae su recompensa',
    estimated_reading_minutes: 7,
    imageUrl: 'https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=800&q=80',
    dataFile: () => require('./data/full_hands_king_es_001.json'),
  },
];
