// Biblical Cards — Phase 1: 6 standard cards + 1 special legendary + Pascua 2026 event set
// Phase 2 will add trading system for duplicates.
// imageUrl is optional — when present, the card renders remote artwork instead of local fallback.

export type CardRarity = 'common' | 'rare' | 'epic' | 'legendary';

export interface BiblicalCard {
  id: string;
  nameEs: string;
  nameEn: string;
  /** Category: what type of biblical subject this is */
  category: 'Personajes' | 'Objetos' | 'Eventos';
  /** Rarity tier — drives UI treatment and drop rates */
  rarity: CardRarity;
  /**
   * Whether this card is included in the standard random pack draw pool.
   * Set to false for special / event / legendary-only cards.
   */
  inStandardPool: boolean;
  /**
   * Album grouping — determines which collection tab the card appears in.
   *   'starter'        → Colección Inicial
   *   'pascua_2026'    → Historia de Pascua
   *   'milagros_2026'  → Milagros de Jesús
   *   'secret_rewards' → Cartas Secretas (reward-only, not in any pack)
   */
  albumGroup: 'starter' | 'pascua_2026' | 'milagros_2026' | 'secret_rewards';
  // ── Event metadata (optional) ────────────────────────────────────────────
  /** Slug for the event this card belongs to, e.g. "pascua" */
  event?: string;
  /** Versioned event set identifier, e.g. "pascua_2026" */
  eventSet?: string;
  /** Chronological order within the event set (1-based) */
  eventOrder?: number;
  // ─────────────────────────────────────────────────────────────────────────
  descriptionEs: string;
  descriptionEn: string;
  verseRef: string;
  verseTextEs: string;
  // Enriched lore fields
  datoDestacadoEs: string;
  significadoBiblicoEs: string;
  visualHints: string[];
  // Gradient colors for the card face
  gradientColors: [string, string, string];
  accentColor: string;
  // Optional remote artwork. When present, rendered as the main illustration.
  imageUrl?: string;
  /**
   * Focal point for the illustration crop (0–1 range).
   * 0.5 / 0.5 = centered (default).
   *
   * ARTWORK GENERATION GUIDELINES
   * ─────────────────────────────────────────────────────────────────────────
   * • Compose for a vertical trading-card crop (roughly 2:3 portrait ratio).
   * • Keep the main subject(s) inside a central safe zone:
   *     horizontal: 15%–85% of image width
   *     vertical:   10%–85% of image height
   * • Do NOT place faces, heads, or key action areas near the frame edge.
   * • Leave visual breathing room at top and bottom (≥ 10% padding).
   * • If the scene has multiple subjects, anchor the focal point between them.
   * • After generating, set imageFocusX / imageFocusY so the renderer centres
   *   the crop on the most important part of the scene.
   * ─────────────────────────────────────────────────────────────────────────
   */
  imageFocusX?: number;
  imageFocusY?: number;
  // Per-card decorative motif used by the local fallback renderer
  motif: {
    topSymbol: string;
    subtitleEs: string;
    subtitleEn: string;
    artEmoji: string;
    decorSymbols: [string, string, string];
    sheenColors: [string, string];
    cornerGlyph: string;
  };
}

// ─── Rarity display config ────────────────────────────────────────────────────
export const RARITY_CONFIG: Record<CardRarity, {
  labelEs: string;
  labelEn: string;
  color: string;       // text + border
  bg: string;          // chip background
  glow: string;        // shadow/glow color
}> = {
  common:    { labelEs: 'Común',     labelEn: 'Common',    color: '#9CA3AF', bg: 'rgba(156,163,175,0.18)', glow: 'rgba(156,163,175,0.30)' },
  rare:      { labelEs: 'Rara',      labelEn: 'Rare',      color: '#60A5FA', bg: 'rgba(96,165,250,0.18)',  glow: 'rgba(96,165,250,0.40)'  },
  epic:      { labelEs: 'Épica',     labelEn: 'Epic',      color: '#C084FC', bg: 'rgba(192,132,252,0.18)', glow: 'rgba(192,132,252,0.45)' },
  legendary: { labelEs: 'Legendaria',labelEn: 'Legendary', color: '#D4AF37', bg: 'rgba(212,175,55,0.20)',  glow: 'rgba(212,175,55,0.55)'  },
};

// ─────────────────────────────────────────────────────────────────────────────

export const BIBLICAL_CARDS: Record<string, BiblicalCard> = {
  david: {
    id: 'david',
    nameEs: 'David',
    nameEn: 'David',
    category: 'Personajes',
    rarity: 'rare',
    inStandardPool: true,
    albumGroup: 'starter',
    descriptionEs: 'Pastor, músico, guerrero y rey. David venció a Goliat y fue llamado un hombre conforme al corazón de Dios.',
    descriptionEn: 'Shepherd, musician, warrior and king. David defeated Goliath and was called a man after God\'s own heart.',
    verseRef: 'Hechos 13:22',
    verseTextEs: 'He hallado a David hijo de Isaí, varón conforme a mi corazón.',
    datoDestacadoEs: 'Escribió muchos de los Salmos más conocidos de la Biblia.',
    significadoBiblicoEs: 'Representa adoración, valentía, arrepentimiento genuino y liderazgo guiado por Dios.',
    visualHints: ['harp', 'sling', 'shepherd', 'crown'],
    gradientColors: ['#0C1850', '#162E82', '#1C3D9E'],
    accentColor: '#D4AF37',
    // Custom illustration — David card artwork
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772839374_1772839382183_019cc576-2ca7-734e-b019-1c199427b8f0.png',
    // Focus: shift slightly left + up to keep both David and Goliath's upper
    // bodies / heads in frame and keep the sling-and-rock action visible.
    imageFocusX: 0.5,
    imageFocusY: 0.28,
    motif: {
      topSymbol: '✦',
      subtitleEs: 'Rey de Israel',
      subtitleEn: 'King of Israel',
      artEmoji: '🎵',
      decorSymbols: ['𝄞', '✦', '⚜'],
      sheenColors: ['rgba(212,175,55,0.28)', 'rgba(212,175,55,0.06)'],
      cornerGlyph: '♜',
    },
  },
  moses: {
    id: 'moses',
    nameEs: 'Moisés',
    nameEn: 'Moses',
    category: 'Personajes',
    rarity: 'rare',
    inStandardPool: true,
    albumGroup: 'starter',
    descriptionEs: 'Dios lo llamó desde la zarza ardiente para sacar a Israel de Egipto y guiarlo hacia la libertad.',
    descriptionEn: 'God called him from the burning bush to lead Israel out of Egypt toward freedom.',
    verseRef: 'Éxodo 3:10',
    verseTextEs: 'Ven, y te enviaré a Faraón, para que saques de Egipto a mi pueblo.',
    datoDestacadoEs: 'Recibió la Ley en el monte Sinaí y fue uno de los líderes más importantes del Antiguo Testamento.',
    significadoBiblicoEs: 'Representa obediencia al llamado de Dios, liberación y dirección divina.',
    visualHints: ['staff', 'mount sinai', 'tablets', 'burning bush'],
    gradientColors: ['#2C1654', '#4A1880', '#6B2FA0'],
    accentColor: '#C9A227',
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772851308_1772851309624_019cc62c-2c38-757b-b0b6-0a683b8ce07a.png',
    imageFocusX: 0.5,
    imageFocusY: 0.32,
    motif: {
      topSymbol: '☩',
      subtitleEs: 'Profeta de Dios',
      subtitleEn: 'Prophet of God',
      artEmoji: '📜',
      decorSymbols: ['⚡', '✦', '🗿'],
      sheenColors: ['rgba(201,162,39,0.28)', 'rgba(180,100,220,0.08)'],
      cornerGlyph: '✡',
    },
  },
  ark: {
    id: 'ark',
    nameEs: 'Arca de Noé',
    nameEn: "Noah's Ark",
    category: 'Objetos',
    rarity: 'rare',
    inStandardPool: true,
    albumGroup: 'starter',
    descriptionEs: 'El arca preservó a Noé, su familia y la vida animal durante el diluvio.',
    descriptionEn: 'The ark preserved Noah, his family and animal life through the flood.',
    verseRef: 'Génesis 6:14',
    verseTextEs: 'Hazte un arca de madera de ciprés; harás aposentos en el arca.',
    datoDestacadoEs: 'Fue construida por obediencia a Dios, aun antes de que la lluvia comenzara.',
    significadoBiblicoEs: 'Representa salvación, pacto, refugio y fe obediente.',
    visualHints: ['ark', 'rainbow', 'animals', 'dove'],
    gradientColors: ['#0B3D2E', '#165A40', '#1E7A52'],
    accentColor: '#4DD9AC',
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772851341_1772851343433_019cc62c-b049-758a-bf0e-463f60d82391.png',
    imageFocusX: 0.5,
    imageFocusY: 0.35,
    motif: {
      topSymbol: '🌈',
      subtitleEs: 'Pacto Eterno',
      subtitleEn: 'Eternal Covenant',
      artEmoji: '⛵',
      decorSymbols: ['〰', '✦', '〰'],
      sheenColors: ['rgba(77,217,172,0.28)', 'rgba(56,142,60,0.08)'],
      cornerGlyph: '🕊',
    },
  },
  espada_espiritu: {
    id: 'espada_espiritu',
    nameEs: 'Espada del Espíritu',
    nameEn: 'Sword of the Spirit',
    category: 'Objetos',
    rarity: 'epic',
    inStandardPool: true,
    albumGroup: 'starter',
    descriptionEs: 'La Palabra de Dios es llamada la espada del Espíritu, un arma espiritual para la verdad y la victoria.',
    descriptionEn: 'The Word of God is called the sword of the Spirit — a spiritual weapon for truth and victory.',
    verseRef: 'Efesios 6:17',
    verseTextEs: 'Tomad el yelmo de la salvación, y la espada del Espíritu, que es la palabra de Dios.',
    datoDestacadoEs: 'Forma parte de la armadura de Dios descrita por Pablo.',
    significadoBiblicoEs: 'Representa verdad, autoridad espiritual y defensa contra el engaño.',
    visualHints: ['sword', 'light', 'armor', 'scripture'],
    gradientColors: ['#0A1828', '#0E2A50', '#162E6A'],
    accentColor: '#A8C8F0',
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772851359_1772851360307_019cc62c-f233-71bb-a736-cd4af8414c87.png',
    imageFocusX: 0.5,
    imageFocusY: 0.35,
    motif: {
      topSymbol: '⚔',
      subtitleEs: 'Armadura de Dios',
      subtitleEn: 'Armor of God',
      artEmoji: '⚔️',
      decorSymbols: ['✦', '⚔', '✦'],
      sheenColors: ['rgba(168,200,240,0.30)', 'rgba(100,160,220,0.08)'],
      cornerGlyph: '🛡',
    },
  },
  arpa_david: {
    id: 'arpa_david',
    nameEs: 'Arpa de David',
    nameEn: "David's Harp",
    category: 'Objetos',
    rarity: 'rare',
    inStandardPool: true,
    albumGroup: 'starter',
    descriptionEs: 'David tocaba el arpa y Saúl hallaba alivio. Su música ministraba paz en tiempos de tormento.',
    descriptionEn: "David played the harp and Saul found relief. His music ministered peace in times of torment.",
    verseRef: '1 Samuel 16:23',
    verseTextEs: 'Tomaba David el arpa, y tocaba con su mano; y Saúl tenía alivio y estaba mejor.',
    datoDestacadoEs: 'La adoración de David no era solo arte; era una expresión espiritual poderosa.',
    significadoBiblicoEs: 'Representa adoración, consuelo y sensibilidad a la presencia de Dios.',
    visualHints: ['harp', 'golden strings', 'music', 'worship'],
    gradientColors: ['#3B1A08', '#6B3510', '#8B4A18'],
    accentColor: '#F4C56A',
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772851381_1772851383826_019cc62d-4e12-764c-81c5-e5e189b760b0.png',
    imageFocusX: 0.5,
    imageFocusY: 0.35,
    motif: {
      topSymbol: '𝄞',
      subtitleEs: 'Adoración Real',
      subtitleEn: 'Royal Worship',
      artEmoji: '🎶',
      decorSymbols: ['♪', '✦', '♫'],
      sheenColors: ['rgba(244,197,106,0.30)', 'rgba(220,160,50,0.08)'],
      cornerGlyph: '♪',
    },
  },
  zarza_ardiente: {
    id: 'zarza_ardiente',
    nameEs: 'Zarza Ardiente',
    nameEn: 'Burning Bush',
    category: 'Eventos',
    rarity: 'epic',
    inStandardPool: true,
    albumGroup: 'starter',
    descriptionEs: 'Dios se manifestó a Moisés en una zarza que ardía sin consumirse.',
    descriptionEn: 'God revealed Himself to Moses in a bush that burned without being consumed.',
    verseRef: 'Éxodo 3:2',
    verseTextEs: 'Y se le apareció el ángel de Jehová en una llama de fuego en medio de una zarza.',
    datoDestacadoEs: 'Allí comenzó el llamado que cambiaría la historia de Israel.',
    significadoBiblicoEs: 'Representa llamado divino, santidad y revelación de Dios.',
    visualHints: ['burning bush', 'flame', 'desert', 'divine light'],
    gradientColors: ['#2A0E00', '#5C1F00', '#8B3300'],
    accentColor: '#FF7A2A',
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772851416_1772851418326_019cc62d-d4d6-721b-9001-dcf88cc0fe1e.png',
    imageFocusX: 0.5,
    imageFocusY: 0.35,
    motif: {
      topSymbol: '🔥',
      subtitleEs: 'Llamado Divino',
      subtitleEn: 'Divine Calling',
      artEmoji: '🔥',
      decorSymbols: ['✦', '🔥', '✦'],
      sheenColors: ['rgba(255,122,42,0.30)', 'rgba(220,80,20,0.08)'],
      cornerGlyph: '✡',
    },
  },

  // ─── SPECIAL / UNRELEASED CARDS ─────────────────────────────────────────────
  // inStandardPool: false → never drawn from a normal sobre_biblico pack.
  // Will be distributed via special events or future mechanics.

  jesus_rey_reyes: {
    id: 'jesus_rey_reyes',
    nameEs: 'Jesús',
    nameEn: 'Jesus',
    category: 'Personajes',
    rarity: 'legendary',
    inStandardPool: false,
    albumGroup: 'starter',
    descriptionEs: 'Jesús es el Hijo de Dios, Salvador y Rey de Reyes. En Él hay vida, redención y victoria eterna.',
    descriptionEn: 'Jesus is the Son of God, Savior and King of Kings. In Him there is life, redemption, and eternal victory.',
    verseRef: 'Apocalipsis 19:16',
    verseTextEs: 'Y en su vestidura y en su muslo tiene escrito este nombre: REY DE REYES Y SEÑOR DE SEÑORES.',
    datoDestacadoEs: 'Su vida, muerte y resurrección transformaron la historia para siempre.',
    significadoBiblicoEs: 'Representa salvación, gracia, autoridad suprema y esperanza eterna.',
    visualHints: ['crown of thorns', 'white robe', 'divine light', 'resurrection', 'cross'],
    gradientColors: ['#1A1200', '#3D2B00', '#5C3F00'],
    accentColor: '#F5E27A',
    motif: {
      topSymbol: '✟',
      subtitleEs: 'Rey de Reyes',
      subtitleEn: 'King of Kings',
      artEmoji: '✝️',
      decorSymbols: ['✟', '✦', '✟'],
      sheenColors: ['rgba(245,226,122,0.40)', 'rgba(255,255,220,0.12)'],
      cornerGlyph: '♔',
    },
  },

  // ─── PASCUA 2026 EVENT SET ────────────────────────────────────────────────────
  // event: "pascua" | eventSet: "pascua_2026" | inStandardPool: false
  // Cards are sorted by eventOrder (1–14) in getEventSetCards().

  entrada_jerusalen: {
    id: 'entrada_jerusalen',
    nameEs: 'Entrada Triunfal',
    nameEn: 'Triumphal Entry',
    category: 'Eventos',
    rarity: 'rare',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 1,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772844070_1772844072869_019cc5bd-bfa5-70c7-a3ad-6047237ae38f.png',
    imageFocusX: 0.5,
    imageFocusY: 0.38,
    descriptionEs: 'Jesús entra en Jerusalén montado en un burrito mientras la multitud lo recibe como Rey.',
    descriptionEn: 'Jesus enters Jerusalem on a donkey as the crowd receives him as King.',
    verseRef: 'Mateo 21:9',
    verseTextEs: '¡Hosanna al Hijo de David! ¡Bendito el que viene en el nombre del Señor!',
    datoDestacadoEs: 'La multitud extendía mantos y ramas en el camino.',
    significadoBiblicoEs: 'Representa el cumplimiento de las profecías sobre el Mesías.',
    visualHints: ['donkey', 'palm branches', 'crowd', 'Jerusalem gate'],
    gradientColors: ['#1A2E0A', '#2D4F12', '#3D6618'],
    accentColor: '#7EC850',
    motif: {
      topSymbol: '✦',
      subtitleEs: 'Domingo de Ramos',
      subtitleEn: 'Palm Sunday',
      artEmoji: '🌿',
      decorSymbols: ['🌿', '✦', '🌿'],
      sheenColors: ['rgba(126,200,80,0.28)', 'rgba(80,160,40,0.08)'],
      cornerGlyph: '✦',
    },
  },

  burrito: {
    id: 'burrito',
    nameEs: 'El Burrito',
    nameEn: "The Donkey",
    category: 'Objetos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 2,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772844100_1772844101916_019cc5be-311c-7077-929b-6080e0935e60.png',
    imageFocusX: 0.5,
    imageFocusY: 0.35,
    descriptionEs: 'El humilde animal que llevó a Jesús durante su entrada triunfal en Jerusalén.',
    descriptionEn: 'The humble animal that carried Jesus during his triumphal entry into Jerusalem.',
    verseRef: 'Lucas 19:30',
    verseTextEs: 'Id a la aldea de enfrente, en la cual entrareis y hallaréis un pollino atado.',
    datoDestacadoEs: 'Jesús eligió un burrito en lugar de un caballo de guerra.',
    significadoBiblicoEs: 'Simboliza humildad y paz.',
    visualHints: ['donkey', 'palm road', 'humble', 'Jerusalem'],
    gradientColors: ['#2A1F0E', '#4A3618', '#5E4520'],
    accentColor: '#C4975A',
    motif: {
      topSymbol: '🫏',
      subtitleEs: 'Humildad',
      subtitleEn: 'Humility',
      artEmoji: '🫏',
      decorSymbols: ['✦', '🫏', '✦'],
      sheenColors: ['rgba(196,151,90,0.28)', 'rgba(150,100,50,0.08)'],
      cornerGlyph: '✦',
    },
  },

  ultima_cena: {
    id: 'ultima_cena',
    nameEs: 'La Última Cena',
    nameEn: 'The Last Supper',
    category: 'Eventos',
    rarity: 'epic',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 3,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772846114_1772846116331_019cc5dc-edeb-7055-8af6-0475517658b4.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    descriptionEs: 'Jesús comparte el pan y el vino con sus discípulos antes de su arresto.',
    descriptionEn: 'Jesus shares bread and wine with his disciples before his arrest.',
    verseRef: 'Lucas 22:19',
    verseTextEs: 'Esto es mi cuerpo, que por vosotros es dado; haced esto en memoria de mí.',
    datoDestacadoEs: '"Haced esto en memoria de mí."',
    significadoBiblicoEs: 'Institución de la Santa Cena.',
    visualHints: ['bread', 'wine', 'table', 'twelve disciples', 'candlelight'],
    gradientColors: ['#1E0E00', '#3D1E00', '#5C2D00'],
    accentColor: '#E07B30',
    motif: {
      topSymbol: '✟',
      subtitleEs: 'Santa Cena',
      subtitleEn: 'Holy Communion',
      artEmoji: '🍞',
      decorSymbols: ['🍞', '✟', '🍷'],
      sheenColors: ['rgba(224,123,48,0.30)', 'rgba(180,80,20,0.08)'],
      cornerGlyph: '✟',
    },
  },

  getsemani: {
    id: 'getsemani',
    nameEs: 'Oración en Getsemaní',
    nameEn: 'Prayer at Gethsemane',
    category: 'Eventos',
    rarity: 'epic',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 4,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772847059_1772847060427_019cc5eb-55cb-7552-91e7-acfbfd98cba8.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    descriptionEs: 'Jesús ora con profunda angustia antes de su arresto.',
    descriptionEn: 'Jesus prays in deep anguish before his arrest.',
    verseRef: 'Mateo 26:39',
    verseTextEs: 'No sea como yo quiero, sino como tú.',
    datoDestacadoEs: '"No sea como yo quiero, sino como tú."',
    significadoBiblicoEs: 'Muestra obediencia total al Padre.',
    visualHints: ['olive garden', 'kneeling', 'moonlight', 'anguish', 'prayer'],
    gradientColors: ['#050E1A', '#0A1E36', '#102848'],
    accentColor: '#5B8DD9',
    motif: {
      topSymbol: '☩',
      subtitleEs: 'Obediencia',
      subtitleEn: 'Obedience',
      artEmoji: '🌙',
      decorSymbols: ['☩', '✦', '☩'],
      sheenColors: ['rgba(91,141,217,0.28)', 'rgba(50,90,160,0.08)'],
      cornerGlyph: '☩',
    },
  },

  judas: {
    id: 'judas',
    nameEs: 'La Traición de Judas',
    nameEn: 'The Betrayal of Judas',
    category: 'Personajes',
    rarity: 'rare',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 5,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772847082_1772847084638_019cc5eb-b45e-7628-9b4a-1d8bc27f254a.png',
    imageFocusX: 0.5,
    imageFocusY: 0.38,
    descriptionEs: 'Judas identifica a Jesús con un beso para entregarlo a los soldados.',
    descriptionEn: 'Judas identifies Jesus with a kiss to hand him over to the soldiers.',
    verseRef: 'Mateo 26:49',
    verseTextEs: '¡Salve, Maestro! Y le besó.',
    datoDestacadoEs: 'El beso de traición.',
    significadoBiblicoEs: 'Cumplimiento de las profecías.',
    visualHints: ['kiss', 'betrayal', 'soldiers', 'torchlight', 'thirty silver coins'],
    gradientColors: ['#1A0A00', '#360F00', '#501500'],
    accentColor: '#C0392B',
    motif: {
      topSymbol: '✦',
      subtitleEs: 'Traición',
      subtitleEn: 'Betrayal',
      artEmoji: '💋',
      decorSymbols: ['💰', '✦', '💔'],
      sheenColors: ['rgba(192,57,43,0.28)', 'rgba(140,30,20,0.08)'],
      cornerGlyph: '✦',
    },
  },

  arresto: {
    id: 'arresto',
    nameEs: 'Arresto de Jesús',
    nameEn: 'Arrest of Jesus',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 6,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772847155_1772847156414_019cc5ec-ccbe-728c-91fa-b9136f10e227.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    descriptionEs: 'Jesús es arrestado por los soldados y llevado ante las autoridades.',
    descriptionEn: 'Jesus is arrested by soldiers and brought before the authorities.',
    verseRef: 'Juan 18:12',
    verseTextEs: 'La compañía de soldados prendió a Jesús y le ató.',
    datoDestacadoEs: 'Los discípulos se dispersan.',
    significadoBiblicoEs: 'Inicio del juicio injusto.',
    visualHints: ['soldiers', 'torches', 'bound hands', 'night', 'garden'],
    gradientColors: ['#0A0A14', '#141422', '#1E1E30'],
    accentColor: '#8888CC',
    motif: {
      topSymbol: '⛓',
      subtitleEs: 'Captura',
      subtitleEn: 'Captured',
      artEmoji: '⛓️',
      decorSymbols: ['⛓', '✦', '⛓'],
      sheenColors: ['rgba(136,136,204,0.24)', 'rgba(80,80,160,0.08)'],
      cornerGlyph: '⛓',
    },
  },

  poncio_pilato: {
    id: 'poncio_pilato',
    nameEs: 'Poncio Pilato',
    nameEn: 'Pontius Pilate',
    category: 'Personajes',
    rarity: 'rare',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 7,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772847174_1772847175747_019cc5ed-1843-737b-ac97-936acde40b79.png',
    imageFocusX: 0.5,
    imageFocusY: 0.38,
    descriptionEs: 'Gobernador romano que autorizó la crucifixión de Jesús.',
    descriptionEn: 'Roman governor who authorized the crucifixion of Jesus.',
    verseRef: 'Mateo 27:24',
    verseTextEs: 'Tomó agua y se lavó las manos delante de la multitud, diciendo: Inocente soy yo de la sangre de este justo.',
    datoDestacadoEs: 'Pilato se lava las manos ante la multitud.',
    significadoBiblicoEs: 'Representa la presión política frente a la verdad.',
    visualHints: ['Roman robes', 'stone basin', 'water', 'crowd', 'Jerusalem courtyard'],
    gradientColors: ['#1A1208', '#2E2010', '#3E2C14'],
    accentColor: '#C8A84B',
    motif: {
      topSymbol: '⚖',
      subtitleEs: 'Juicio',
      subtitleEn: 'Judgment',
      artEmoji: '⚖️',
      decorSymbols: ['⚖', '✦', '🏛'],
      sheenColors: ['rgba(200,168,75,0.28)', 'rgba(160,120,40,0.08)'],
      cornerGlyph: '⚖',
    },
  },

  barrabas: {
    id: 'barrabas',
    nameEs: 'Barrabás',
    nameEn: 'Barabbas',
    category: 'Personajes',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 8,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772847201_1772847205482_019cc5ed-8c6a-75ae-8a7e-e912b2918299.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    descriptionEs: 'Criminal liberado por la multitud en lugar de Jesús.',
    descriptionEn: 'Criminal released by the crowd instead of Jesus.',
    verseRef: 'Mateo 27:26',
    verseTextEs: 'Entonces les soltó a Barrabás; y habiendo azotado a Jesús, le entregó para ser crucificado.',
    datoDestacadoEs: 'El pueblo pidió la libertad de Barrabás.',
    significadoBiblicoEs: 'Imagen simbólica del pecador liberado mientras Cristo toma su lugar.',
    visualHints: ['prisoner', 'chains broken', 'crowd', 'freedom'],
    gradientColors: ['#140A0A', '#280F0F', '#3A1414'],
    accentColor: '#AA4444',
    motif: {
      topSymbol: '⛓',
      subtitleEs: 'El Libre',
      subtitleEn: 'The Freed',
      artEmoji: '🔓',
      decorSymbols: ['🔓', '✦', '⛓'],
      sheenColors: ['rgba(170,68,68,0.28)', 'rgba(120,40,40,0.08)'],
      cornerGlyph: '✦',
    },
  },

  camino_calvario: {
    id: 'camino_calvario',
    nameEs: 'Camino al Calvario',
    nameEn: 'Way of the Cross',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 9,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772847222_1772847223507_019cc5ed-d2d3-760e-a7cf-97fdfd1fdaf7.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    descriptionEs: 'Jesús carga la cruz rumbo al lugar de la crucifixión.',
    descriptionEn: 'Jesus carries the cross toward the place of crucifixion.',
    verseRef: 'Lucas 23:26',
    verseTextEs: 'Y llevándole, tomaron a cierto Simón de Cirene que venía del campo, y le pusieron encima la cruz para que la llevase tras Jesús.',
    datoDestacadoEs: 'Simón de Cirene ayuda a llevar la cruz.',
    significadoBiblicoEs: 'Camino de sacrificio y redención.',
    visualHints: ['cross', 'cobblestone road', 'crowd watching', 'Simon of Cyrene', 'Jerusalem street'],
    gradientColors: ['#1A1008', '#301E0C', '#452810'],
    accentColor: '#B07840',
    motif: {
      topSymbol: '✟',
      subtitleEs: 'Vía Crucis',
      subtitleEn: 'Via Crucis',
      artEmoji: '✝️',
      decorSymbols: ['✟', '✦', '✟'],
      sheenColors: ['rgba(176,120,64,0.28)', 'rgba(130,80,30,0.08)'],
      cornerGlyph: '✟',
    },
  },

  crucifixion: {
    id: 'crucifixion',
    nameEs: 'Jesús en la Cruz',
    nameEn: 'Jesus on the Cross',
    category: 'Eventos',
    rarity: 'legendary',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 10,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772847253_1772847254831_019cc5ee-4d2f-774e-be0a-6d55d6497ea8.png',
    imageFocusX: 0.5,
    imageFocusY: 0.35,
    descriptionEs: 'Jesús entrega su vida en la cruz por la salvación del mundo.',
    descriptionEn: 'Jesus gives his life on the cross for the salvation of the world.',
    verseRef: 'Lucas 23:46',
    verseTextEs: 'Padre, en tus manos encomiendo mi espíritu.',
    datoDestacadoEs: '"Padre, en tus manos encomiendo mi espíritu."',
    significadoBiblicoEs: 'El sacrificio central de la fe cristiana.',
    visualHints: ['cross', 'Golgotha', 'dark sky', 'crown of thorns', 'divine light'],
    gradientColors: ['#1A0000', '#380000', '#500000'],
    accentColor: '#CC3333',
    motif: {
      topSymbol: '✟',
      subtitleEs: 'Sacrificio Eterno',
      subtitleEn: 'Eternal Sacrifice',
      artEmoji: '✝️',
      decorSymbols: ['✟', '✦', '✟'],
      sheenColors: ['rgba(204,51,51,0.35)', 'rgba(160,20,20,0.10)'],
      cornerGlyph: '✟',
    },
  },

  velo_rasgado: {
    id: 'velo_rasgado',
    nameEs: 'El Velo Rasgado',
    nameEn: 'The Torn Veil',
    category: 'Eventos',
    rarity: 'epic',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 11,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772847502_1772847503900_019cc5f2-1a1c-718f-b977-2d8665f41d56.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    descriptionEs: 'El velo del templo se rasga cuando Jesús muere.',
    descriptionEn: 'The temple veil tears in two when Jesus dies.',
    verseRef: 'Mateo 27:51',
    verseTextEs: 'El velo del templo se rasgó en dos, de arriba abajo.',
    datoDestacadoEs: 'El acceso directo a Dios queda abierto.',
    significadoBiblicoEs: 'Fin de la separación entre Dios y la humanidad.',
    visualHints: ['temple veil', 'tearing', 'divine light', 'holy of holies', 'earthquake'],
    gradientColors: ['#1A1200', '#342400', '#4A3300'],
    accentColor: '#D4A030',
    motif: {
      topSymbol: '✟',
      subtitleEs: 'Acceso a Dios',
      subtitleEn: 'Access to God',
      artEmoji: '⚡',
      decorSymbols: ['✟', '⚡', '✟'],
      sheenColors: ['rgba(212,160,48,0.32)', 'rgba(170,110,20,0.08)'],
      cornerGlyph: '✟',
    },
  },

  tumba_sellada: {
    id: 'tumba_sellada',
    nameEs: 'La Tumba Sellada',
    nameEn: 'The Sealed Tomb',
    category: 'Eventos',
    rarity: 'rare',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 12,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772847524_1772847525704_019cc5f2-6f48-7032-bd58-132509c80ffe.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    descriptionEs: 'La tumba de Jesús es sellada y vigilada por soldados.',
    descriptionEn: 'The tomb of Jesus is sealed and guarded by soldiers.',
    verseRef: 'Mateo 27:66',
    verseTextEs: 'Fueron y aseguraron el sepulcro, sellando la piedra y poniendo la guardia.',
    datoDestacadoEs: 'La piedra es colocada en la entrada.',
    significadoBiblicoEs: 'Preparación para el milagro de la resurrección.',
    visualHints: ['stone tomb', 'sealed stone', 'Roman soldiers', 'dawn', 'garden'],
    gradientColors: ['#0A0A0A', '#161616', '#222222'],
    accentColor: '#888888',
    motif: {
      topSymbol: '⛰',
      subtitleEs: 'Silencio',
      subtitleEn: 'Silence',
      artEmoji: '🪨',
      decorSymbols: ['🪨', '✦', '🪨'],
      sheenColors: ['rgba(136,136,136,0.24)', 'rgba(90,90,90,0.08)'],
      cornerGlyph: '⛰',
    },
  },

  resurreccion: {
    id: 'resurreccion',
    nameEs: 'La Resurrección',
    nameEn: 'The Resurrection',
    category: 'Eventos',
    rarity: 'legendary',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 13,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772847551_1772847552311_019cc5f2-d737-7233-86a0-b987c26ddc07.png',
    imageFocusX: 0.5,
    imageFocusY: 0.35,
    descriptionEs: 'Jesús resucita al tercer día venciendo la muerte.',
    descriptionEn: 'Jesus rises on the third day, conquering death.',
    verseRef: 'Mateo 28:6',
    verseTextEs: 'No está aquí, pues ha resucitado, como dijo. Venid, ved el lugar donde fue puesto el Señor.',
    datoDestacadoEs: '"No está aquí, pues ha resucitado."',
    significadoBiblicoEs: 'La victoria definitiva sobre el pecado y la muerte.',
    visualHints: ['empty tomb', 'open stone', 'blazing light', 'angel', 'white linen'],
    gradientColors: ['#1A1400', '#3D3200', '#604E00'],
    accentColor: '#F5D060',
    motif: {
      topSymbol: '✟',
      subtitleEs: '¡Resucitó!',
      subtitleEn: 'He is Risen!',
      artEmoji: '☀️',
      decorSymbols: ['✟', '☀️', '✟'],
      sheenColors: ['rgba(245,208,96,0.40)', 'rgba(220,170,40,0.12)'],
      cornerGlyph: '☀',
    },
  },

  // ─── SECRET COLLECTION REWARD CARD ─────────────────────────────────────────
  // This card is NOT in any pack pool. It can only be obtained by completing
  // the Historia de Pascua collection (all 14 event cards).
  jesus_resucitado: {
    id: 'jesus_resucitado',
    nameEs: 'Jesús Resucitado',
    nameEn: 'The Risen Christ',
    category: 'Personajes',
    rarity: 'legendary',
    inStandardPool: false,
    albumGroup: 'secret_rewards',
    // Not part of the event set pool (reward-only)
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1773019559_1773019562207_019cd033-80df-71a4-82ca-cad604eec3cf.png',
    imageFocusX: 0.5,
    imageFocusY: 0.38,
    descriptionEs: 'Jesús venció a la muerte y se apareció a sus discípulos glorificado. Su resurrección es el fundamento de la fe cristiana.',
    descriptionEn: 'Jesus conquered death and appeared to His disciples in glory. His resurrection is the foundation of the Christian faith.',
    verseRef: 'Juan 20:17',
    verseTextEs: 'Sube a mi Padre y a vuestro Padre, a mi Dios y a vuestro Dios.',
    datoDestacadoEs: 'Carta secreta — obtenida completando la colección "Historia de Pascua".',
    significadoBiblicoEs: 'La resurrección es la victoria definitiva sobre el pecado y la muerte. Cristo vive, y en Él, vivimos.',
    visualHints: ['risen Christ', 'radiant light', 'empty tomb', 'glory', 'wounds of light'],
    gradientColors: ['#3A1800', '#6B3000', '#FFAA00'],
    accentColor: '#FFD700',
    motif: {
      topSymbol: '✦',
      subtitleEs: 'Colección Especial',
      subtitleEn: 'Special Collection',
      artEmoji: '☀️',
      decorSymbols: ['✝', '☀️', '✦'],
      sheenColors: ['rgba(255,215,0,0.38)', 'rgba(255,140,0,0.12)'],
      cornerGlyph: '✦',
    },
  },
  // ────────────────────────────────────────────────────────────────────────────

  // ─── Milagros de Jesús 2026 — 30 cards ──────────────────────────────────────

  // COMUNES (18)
  agua_en_vino: {
    id: 'agua_en_vino',
    nameEs: 'Agua en Vino',
    nameEn: 'Water into Wine',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 1,
    descriptionEs: 'En las bodas de Caná, Jesús convierte el agua en vino, revelando su gloria.',
    descriptionEn: 'At the wedding in Cana, Jesus turns water into wine, revealing His glory.',
    verseRef: 'Juan 2:11',
    verseTextEs: 'Este principio de señales hizo Jesús en Caná de Galilea.',
    datoDestacadoEs: 'Fue el primer milagro registrado de Jesús, a petición de su madre María.',
    significadoBiblicoEs: 'La abundancia del reino supera toda escasez humana.',
    visualHints: ['stone jars', 'water', 'wine', 'Cana wedding'],
    gradientColors: ['#1A0533', '#3D0F6E', '#6B21A8'],
    accentColor: '#C084FC',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/lKWKhottEOE.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '🍷', subtitleEs: 'Caná de Galilea', subtitleEn: 'Cana of Galilee', artEmoji: '🍷', decorSymbols: ['🏺', '✦', '🍇'], sheenColors: ['rgba(192,132,252,0.25)', 'rgba(107,33,168,0.08)'], cornerGlyph: '✦' },
  },
  pesca_milagrosa: {
    id: 'pesca_milagrosa',
    nameEs: 'Pesca Milagrosa',
    nameEn: 'Miraculous Catch',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 2,
    descriptionEs: 'Jesús ordena a Pedro echar las redes y la pesca es tan abundante que las redes se rompen.',
    descriptionEn: 'Jesus tells Peter to cast the nets, and the catch is so great the nets begin to break.',
    verseRef: 'Lucas 5:6',
    verseTextEs: 'Y haciéndolo así, encerraron gran cantidad de peces, y su red se rompía.',
    datoDestacadoEs: 'Tras este milagro Pedro, Jacobo y Juan dejaron todo y siguieron a Jesús.',
    significadoBiblicoEs: 'Cristo llama a sus discípulos con señales de su poder sobrenatural.',
    visualHints: ['fishing nets', 'fish', 'lake', 'boat', 'Peter'],
    gradientColors: ['#0D1B2A', '#1B3A5C', '#1E6091'],
    accentColor: '#60A5FA',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/795b88mTq54.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '🐟', subtitleEs: 'Mar de Galilea', subtitleEn: 'Sea of Galilee', artEmoji: '🎣', decorSymbols: ['🐟', '✦', '🌊'], sheenColors: ['rgba(96,165,250,0.22)', 'rgba(30,96,145,0.08)'], cornerGlyph: '✦' },
  },
  sanidad_leproso: {
    id: 'sanidad_leproso',
    nameEs: 'Sanidad del Leproso',
    nameEn: 'Healing the Leper',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 3,
    descriptionEs: 'Un hombre con lepra se arrodilla ante Jesús; Él lo toca y lo sana al instante.',
    descriptionEn: 'A man with leprosy kneels before Jesus; He touches him and heals him instantly.',
    verseRef: 'Mateo 8:3',
    verseTextEs: 'Jesús extendió la mano y le tocó, diciendo: Quiero; sé limpio.',
    datoDestacadoEs: 'Tocar a un leproso era tabú; Jesús rompió la barrera con compasión.',
    significadoBiblicoEs: 'Cristo purifica lo que la sociedad rechaza.',
    visualHints: ['leper', 'healing touch', 'light', 'cleansing'],
    gradientColors: ['#1A2E1A', '#2D5A2D', '#3A8A3A'],
    accentColor: '#86EFAC',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/sdaTL9f1kws.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '✦', subtitleEs: 'Limpio por la Gracia', subtitleEn: 'Cleansed by Grace', artEmoji: '🙌', decorSymbols: ['✦', '🌿', '☀️'], sheenColors: ['rgba(134,239,172,0.22)', 'rgba(58,138,58,0.08)'], cornerGlyph: '✦' },
  },
  sanidad_paralitico: {
    id: 'sanidad_paralitico',
    nameEs: 'Sanidad del Paralítico',
    nameEn: 'Healing the Paralytic',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 4,
    descriptionEs: 'Cuatro amigos bajan a un paralítico por el techo. Jesús perdona sus pecados y lo sana.',
    descriptionEn: 'Four friends lower a paralyzed man through the roof. Jesus forgives and heals him.',
    verseRef: 'Marcos 2:11',
    verseTextEs: 'A ti te digo: Levántate, toma tu camilla, y vete a tu casa.',
    datoDestacadoEs: 'Jesús primero perdonó los pecados, mostrando que la sanidad espiritual precede a la física.',
    significadoBiblicoEs: 'La fe intercesora puede abrir caminos imposibles.',
    visualHints: ['rooftop', 'mat', 'paralyzed man', 'four friends', 'crowd'],
    gradientColors: ['#1C1A0A', '#3D3A10', '#6B6218'],
    accentColor: '#FDE68A',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/QzHTRCG3T8o.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '✦', subtitleEs: 'Fe que Abre Techos', subtitleEn: 'Faith that Opens Roofs', artEmoji: '🛏️', decorSymbols: ['🏠', '✦', '🙏'], sheenColors: ['rgba(253,230,138,0.22)', 'rgba(107,98,24,0.08)'], cornerGlyph: '✦' },
  },
  sanidad_centurion: {
    id: 'sanidad_centurion',
    nameEs: 'Siervo del Centurión',
    nameEn: 'Centurion\'s Servant',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 5,
    descriptionEs: 'Un centurión romano pide ayuda a Jesús por su siervo enfermo; Jesús sana a distancia.',
    descriptionEn: 'A Roman centurion asks Jesus to heal his sick servant; Jesus heals from a distance.',
    verseRef: 'Mateo 8:13',
    verseTextEs: 'Ve, y como creíste, te sea hecho.',
    datoDestacadoEs: 'Jesús dijo que no había encontrado tanta fe ni en Israel.',
    significadoBiblicoEs: 'La fe trasciende fronteras culturales y religiosas.',
    visualHints: ['centurion armor', 'Roman soldier', 'servant', 'distance healing'],
    gradientColors: ['#1E1208', '#3D2510', '#7A4920'],
    accentColor: '#F59E0B',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/fDeNPwV1l1E.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '⚔️', subtitleEs: 'Fe sin Fronteras', subtitleEn: 'Faith Without Borders', artEmoji: '⚔️', decorSymbols: ['⚔️', '✦', '🏛️'], sheenColors: ['rgba(245,158,11,0.22)', 'rgba(122,73,32,0.08)'], cornerGlyph: '✦' },
  },
  sanidad_suegra_pedro: {
    id: 'sanidad_suegra_pedro',
    nameEs: 'Suegra de Pedro',
    nameEn: 'Peter\'s Mother-in-Law',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 6,
    descriptionEs: 'Jesús toma de la mano a la suegra de Pedro con fiebre alta y la sana al instante.',
    descriptionEn: 'Jesus takes Peter\'s mother-in-law by the hand while she has a high fever, and heals her.',
    verseRef: 'Marcos 1:31',
    verseTextEs: 'Entonces él se acercó, y la tomó de la mano y la levantó; e inmediatamente le dejó la fiebre.',
    datoDestacadoEs: 'Tras ser sanada, ella comenzó a servirles — su primer acto de gratitud.',
    significadoBiblicoEs: 'La sanidad de Jesús restaura para el servicio.',
    visualHints: ['bedside', 'fever', 'hand', 'Peter', 'home'],
    gradientColors: ['#200A0A', '#4A1515', '#7A2020'],
    accentColor: '#FCA5A5',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/_5Qt71364Dw.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '🤝', subtitleEs: 'Sanada para Servir', subtitleEn: 'Healed to Serve', artEmoji: '🤝', decorSymbols: ['🤝', '✦', '🏠'], sheenColors: ['rgba(252,165,165,0.22)', 'rgba(122,32,32,0.08)'], cornerGlyph: '✦' },
  },
  mano_seca: {
    id: 'mano_seca',
    nameEs: 'La Mano Seca',
    nameEn: 'The Withered Hand',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 7,
    descriptionEs: 'En día de reposo, Jesús sana a un hombre con la mano atrofiada ante los fariseos.',
    descriptionEn: 'On the Sabbath, Jesus heals a man with a withered hand before the Pharisees.',
    verseRef: 'Mateo 12:13',
    verseTextEs: 'Entonces dijo al hombre: Extiende tu mano. Y él la extendió, y le fue restaurada sana como la otra.',
    datoDestacadoEs: 'Este milagro desafió directamente las tradiciones religiosas de los líderes judíos.',
    significadoBiblicoEs: 'Dios no está limitado por reglas humanas; su amor actúa libremente.',
    visualHints: ['synagogue', 'hand', 'healing', 'Pharisees', 'Sabbath'],
    gradientColors: ['#0F1A2E', '#1E3558', '#2B5C8A'],
    accentColor: '#93C5FD',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/m45cYlsNe4U.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '✋', subtitleEs: 'Restaurado', subtitleEn: 'Restored', artEmoji: '✋', decorSymbols: ['✋', '✦', '🕌'], sheenColors: ['rgba(147,197,253,0.22)', 'rgba(43,92,138,0.08)'], cornerGlyph: '✦' },
  },
  diez_leprosos: {
    id: 'diez_leprosos',
    nameEs: 'Diez Leprosos',
    nameEn: 'Ten Lepers',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 8,
    descriptionEs: 'Jesús sana a diez leprosos; solo uno, un samaritano, regresa a dar gracias.',
    descriptionEn: 'Jesus heals ten lepers; only one, a Samaritan, returns to give thanks.',
    verseRef: 'Lucas 17:17',
    verseTextEs: '¿No son diez los que fueron limpios? Y los nueve, ¿dónde están?',
    datoDestacadoEs: 'El que dio gracias era samaritano — un extranjero ante los ojos judíos.',
    significadoBiblicoEs: 'La gratitud completa la gracia recibida.',
    visualHints: ['ten lepers', 'road', 'Samaritan', 'gratitude', 'cleansing'],
    gradientColors: ['#1A1000', '#3D2800', '#7A5000'],
    accentColor: '#FCD34D',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/QJPABuGL8Ek.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '10', subtitleEs: 'Solo Uno Volvió', subtitleEn: 'Only One Returned', artEmoji: '🙏', decorSymbols: ['🙏', '✦', '🌾'], sheenColors: ['rgba(252,211,77,0.22)', 'rgba(122,80,0,0.08)'], cornerGlyph: '✦' },
  },
  sordomudo: {
    id: 'sordomudo',
    nameEs: 'Sanidad del Sordomudo',
    nameEn: 'Healing the Deaf-Mute',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 9,
    descriptionEs: 'Jesús toca los oídos y la lengua de un hombre sordo y mudo; dice "Efatá" — ábrete.',
    descriptionEn: 'Jesus touches the ears and tongue of a deaf-mute man and says "Ephphatha" — be opened.',
    verseRef: 'Marcos 7:34',
    verseTextEs: 'Y mirando al cielo, gimió, y le dijo: Efatá, es decir: Sé abierto.',
    datoDestacadoEs: '"Efatá" es una de las pocas palabras en arameo conservadas en los evangelios.',
    significadoBiblicoEs: 'Cristo abre oídos y bocas — físicamente y espiritualmente.',
    visualHints: ['ears', 'tongue', 'sky', 'healing gesture', 'crowd'],
    gradientColors: ['#0A1828', '#102B48', '#164E63'],
    accentColor: '#67E8F9',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/hbtH75vd5uc.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '👂', subtitleEs: 'Efatá — Ábrete', subtitleEn: 'Ephphatha — Be Opened', artEmoji: '👂', decorSymbols: ['👂', '✦', '🌊'], sheenColors: ['rgba(103,232,249,0.22)', 'rgba(22,78,99,0.08)'], cornerGlyph: '✦' },
  },
  ciego_betsaida: {
    id: 'ciego_betsaida',
    nameEs: 'Ciego de Betsaida',
    nameEn: 'Blind Man of Bethsaida',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 10,
    descriptionEs: 'Jesús sana a un ciego en dos etapas fuera de la aldea de Betsaida.',
    descriptionEn: 'Jesus heals a blind man in two stages outside the village of Bethsaida.',
    verseRef: 'Marcos 8:25',
    verseTextEs: 'Luego le puso otra vez las manos sobre los ojos, y le hizo que mirase; y fue restaurado, y vio de lejos y claramente a todos.',
    datoDestacadoEs: 'Único milagro en dos fases — posiblemente para enseñar que la fe crece gradualmente.',
    significadoBiblicoEs: 'Dios sana a su propio ritmo; cada paso de fe cuenta.',
    visualHints: ['blind man', 'hands on eyes', 'two stages', 'village', 'sight'],
    gradientColors: ['#0D1117', '#1A2236', '#253252'],
    accentColor: '#A5B4FC',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/RG-peGMZ91I.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '👁️', subtitleEs: 'Betsaida', subtitleEn: 'Bethsaida', artEmoji: '👁️', decorSymbols: ['👁️', '✦', '🌅'], sheenColors: ['rgba(165,180,252,0.22)', 'rgba(37,50,82,0.08)'], cornerGlyph: '✦' },
  },
  multiplicacion_panes: {
    id: 'multiplicacion_panes',
    nameEs: 'Multiplicación de Panes',
    nameEn: 'Feeding the Five Thousand',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 11,
    descriptionEs: 'Con cinco panes y dos peces, Jesús alimenta a cinco mil hombres y sobran doce canastas.',
    descriptionEn: 'With five loaves and two fish, Jesus feeds five thousand men with twelve baskets left over.',
    verseRef: 'Juan 6:11',
    verseTextEs: 'Y Jesús tomó aquellos panes, y habiendo dado gracias, los repartió entre los discípulos.',
    datoDestacadoEs: 'Es el único milagro registrado en los cuatro evangelios, además de la resurrección.',
    significadoBiblicoEs: 'Dios multiplica lo poco que le entregamos.',
    visualHints: ['loaves', 'fish', 'baskets', 'multitude', 'hillside'],
    gradientColors: ['#1A1200', '#3D2D00', '#7A5A00'],
    accentColor: '#F59E0B',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/Eug1ZcKm-oY.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '🍞', subtitleEs: '5000 Alimentados', subtitleEn: '5000 Fed', artEmoji: '🍞', decorSymbols: ['🍞', '🐟', '✦'], sheenColors: ['rgba(245,158,11,0.25)', 'rgba(122,90,0,0.08)'], cornerGlyph: '✦' },
  },
  moneda_pez: {
    id: 'moneda_pez',
    nameEs: 'Moneda en el Pez',
    nameEn: 'Coin in the Fish',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 12,
    descriptionEs: 'Jesús ordena a Pedro pescar un pez; en su boca hallará una moneda para pagar los impuestos.',
    descriptionEn: 'Jesus tells Peter to catch a fish; in its mouth he will find a coin to pay the temple tax.',
    verseRef: 'Mateo 17:27',
    verseTextEs: 'Ve al mar, echa el anzuelo, y el primer pez que saques, tómalo, y al abrirle la boca, hallarás un estatero.',
    datoDestacadoEs: 'Es uno de los milagros más insólitos — un pez con dinero exacto para el impuesto.',
    significadoBiblicoEs: 'Dios provee de maneras inesperadas y creativas.',
    visualHints: ['fish mouth', 'coin', 'hook', 'Peter', 'sea'],
    gradientColors: ['#051B20', '#0A3540', '#0E5060'],
    accentColor: '#34D399',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/aOrkWiqUxFw.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '🪙', subtitleEs: 'Provisión Sobrenatural', subtitleEn: 'Supernatural Provision', artEmoji: '🪙', decorSymbols: ['🪙', '🐟', '✦'], sheenColors: ['rgba(52,211,153,0.22)', 'rgba(14,80,96,0.08)'], cornerGlyph: '✦' },
  },
  calma_tormenta: {
    id: 'calma_tormenta',
    nameEs: 'Calma la Tormenta',
    nameEn: 'Calms the Storm',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 13,
    descriptionEs: 'Jesús reprende al viento y al mar; sobreviene una gran calma ante los discípulos aterrados.',
    descriptionEn: 'Jesus rebukes the wind and sea; a great calm falls as the disciples are amazed.',
    verseRef: 'Marcos 4:39',
    verseTextEs: 'Y se levantó, y reprendió al viento, y dijo al mar: Calla, enmudece.',
    datoDestacadoEs: 'Estaba dormido en la popa del barco cuando estalló la tormenta.',
    significadoBiblicoEs: 'Cristo tiene autoridad sobre todas las fuerzas de la naturaleza.',
    visualHints: ['stormy sea', 'boat', 'waves', 'sleeping Jesus', 'calm water'],
    gradientColors: ['#040E1A', '#071E38', '#0A2D54'],
    accentColor: '#7DD3FC',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/-tb914Om03w.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '⚡', subtitleEs: '¡Calla, Enmudece!', subtitleEn: 'Peace, Be Still!', artEmoji: '⚡', decorSymbols: ['⚡', '🌊', '✦'], sheenColors: ['rgba(125,211,252,0.25)', 'rgba(10,45,84,0.08)'], cornerGlyph: '✦' },
  },
  higuera_maldita: {
    id: 'higuera_maldita',
    nameEs: 'Higuera Maldita',
    nameEn: 'The Cursed Fig Tree',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 14,
    descriptionEs: 'Jesús maldice una higuera sin fruto; al día siguiente los discípulos la hallan seca de raíz.',
    descriptionEn: 'Jesus curses a fig tree with no fruit; the next day the disciples find it withered to the roots.',
    verseRef: 'Marcos 11:21',
    verseTextEs: 'Rabí, mira, la higuera que maldijiste se ha secado.',
    datoDestacadoEs: 'El único "milagro de juicio" de Jesús — una lección sobre la fe y la fruta espiritual.',
    significadoBiblicoEs: 'La apariencia religiosa sin fruto espiritual tiene consecuencias.',
    visualHints: ['withered fig tree', 'road', 'leaves', 'dry branches', 'disciples'],
    gradientColors: ['#1A0F05', '#3D2410', '#6B3D18'],
    accentColor: '#D97706',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/atrytN-BAOA.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '🌿', subtitleEs: 'Sin Fruto', subtitleEn: 'No Fruit', artEmoji: '🌿', decorSymbols: ['🌿', '✦', '🍂'], sheenColors: ['rgba(217,119,6,0.22)', 'rgba(107,61,24,0.08)'], cornerGlyph: '✦' },
  },
  red_peces: {
    id: 'red_peces',
    nameEs: 'Red Llena de Peces',
    nameEn: 'Net Full of Fish',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 15,
    descriptionEs: 'El Jesús resucitado aparece en la orilla; los discípulos echan la red y sacan 153 peces grandes.',
    descriptionEn: 'The risen Jesus appears on the shore; the disciples cast the net and pull in 153 large fish.',
    verseRef: 'Juan 21:11',
    verseTextEs: 'Simón Pedro subió y sacó la red a tierra, llena de grandes peces, ciento cincuenta y tres.',
    datoDestacadoEs: 'El número 153 ha generado incontables interpretaciones teológicas y matemáticas.',
    significadoBiblicoEs: 'La obediencia a Cristo siempre produce resultados abundantes.',
    visualHints: ['net', '153 fish', 'risen Jesus', 'shore', 'morning fire'],
    gradientColors: ['#060F1A', '#0D2035', '#123050'],
    accentColor: '#38BDF8',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/1ebwg22FXHU.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '🐟', subtitleEs: '153 Peces', subtitleEn: '153 Fish', artEmoji: '🐟', decorSymbols: ['🐟', '🌅', '✦'], sheenColors: ['rgba(56,189,248,0.22)', 'rgba(18,48,80,0.08)'], cornerGlyph: '✦' },
  },
  alimenta_4000: {
    id: 'alimenta_4000',
    nameEs: 'Alimenta a 4000',
    nameEn: 'Feeding the Four Thousand',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 16,
    descriptionEs: 'Jesús multiplica siete panes y unos pocos peces para cuatro mil personas; sobran siete canastas.',
    descriptionEn: 'Jesus multiplies seven loaves and a few fish for four thousand; seven baskets remain.',
    verseRef: 'Marcos 8:9',
    verseTextEs: 'Y comieron, y se saciaron; y recogieron de los pedazos que habían sobrado, siete canastas.',
    datoDestacadoEs: 'Este segundo milagro de multiplicación se dio en territorio gentil (pagano).',
    significadoBiblicoEs: 'La gracia de Dios no tiene fronteras culturales ni geográficas.',
    visualHints: ['seven loaves', 'fish', 'crowd', 'baskets', 'hillside'],
    gradientColors: ['#1A1500', '#3D3200', '#7A6400'],
    accentColor: '#FBBF24',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/B469U8C0D_g.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '🍞', subtitleEs: '4000 Alimentados', subtitleEn: '4000 Fed', artEmoji: '🍞', decorSymbols: ['🍞', '🐟', '✦'], sheenColors: ['rgba(251,191,36,0.22)', 'rgba(122,100,0,0.08)'], cornerGlyph: '✦' },
  },
  liberacion_demonio: {
    id: 'liberacion_demonio',
    nameEs: 'Liberación en la Sinagoga',
    nameEn: 'Deliverance in the Synagogue',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 17,
    descriptionEs: 'Un hombre con espíritu inmundo interrumpe la enseñanza; Jesús lo reprende y lo libera.',
    descriptionEn: 'A man with an unclean spirit interrupts the teaching; Jesus rebukes it and sets him free.',
    verseRef: 'Marcos 1:25',
    verseTextEs: 'Pero Jesús le reprendió, diciendo: ¡Cállate, y sal de él!',
    datoDestacadoEs: 'Ocurrió en la sinagoga de Capernaúm durante el primer año del ministerio de Jesús.',
    significadoBiblicoEs: 'Cristo tiene autoridad sobre el reino de las tinieblas.',
    visualHints: ['synagogue', 'unclean spirit', 'convulsion', 'authority', 'crowd amazed'],
    gradientColors: ['#100520', '#200A40', '#350F60'],
    accentColor: '#A78BFA',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/zP9eQrcf1ck.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '✦', subtitleEs: '¡Sal de Él!', subtitleEn: 'Come Out!', artEmoji: '⚡', decorSymbols: ['⚡', '✦', '🕌'], sheenColors: ['rgba(167,139,250,0.22)', 'rgba(53,15,96,0.08)'], cornerGlyph: '✦' },
  },
  nina_resucitada: {
    id: 'nina_resucitada',
    nameEs: 'Niña Resucitada',
    nameEn: 'Raising Jairus\' Daughter',
    category: 'Eventos',
    rarity: 'common',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 18,
    descriptionEs: 'La hija de Jairo muere; Jesús la toma de la mano y le dice "Talita cumi" — y ella se levanta.',
    descriptionEn: 'Jairus\' daughter dies; Jesus takes her hand and says "Talitha cumi" — and she rises.',
    verseRef: 'Marcos 5:41',
    verseTextEs: 'Y tomando la mano de la niña, le dijo: Talita cumi.',
    datoDestacadoEs: '"Talita cumi" significa "Niña, a ti te digo, levántate" en arameo.',
    significadoBiblicoEs: 'Jesús tiene poder sobre la muerte — incluso en lo más tierno e inocente.',
    visualHints: ['child', 'hand', 'bedroom', 'Jairus', 'rising'],
    gradientColors: ['#1A0820', '#350F40', '#55186A'],
    accentColor: '#E879F9',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/MF0kgoLGjWQ.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '✦', subtitleEs: 'Talita Cumi', subtitleEn: 'Talitha Cumi', artEmoji: '🌸', decorSymbols: ['🌸', '✦', '🙏'], sheenColors: ['rgba(232,121,249,0.22)', 'rgba(85,24,106,0.08)'], cornerGlyph: '✦' },
  },

  // RARAS (8)
  caminar_agua: {
    id: 'caminar_agua',
    nameEs: 'Caminar sobre el Agua',
    nameEn: 'Walking on Water',
    category: 'Eventos',
    rarity: 'rare',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 19,
    descriptionEs: 'Jesús camina sobre las olas en medio de la tormenta; Pedro intenta imitarlo pero duda.',
    descriptionEn: 'Jesus walks on the waves in the storm; Peter tries to imitate Him but doubts.',
    verseRef: 'Mateo 14:29',
    verseTextEs: 'Y descendiendo Pedro de la barca, andaba sobre las aguas para ir a Jesús.',
    datoDestacadoEs: 'Pedro es el único humano registrado en la historia que caminó sobre el agua.',
    significadoBiblicoEs: 'La fe en Cristo es capaz de sostener lo imposible — pero la duda hunde.',
    visualHints: ['Jesus on water', 'Peter sinking', 'storm', 'waves', 'boat'],
    gradientColors: ['#020A14', '#041525', '#071F38'],
    accentColor: '#60A5FA',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/BIE472RjPhA.png',
    imageFocusX: 0.5,
    imageFocusY: 0.38,
    motif: { topSymbol: '🌊', subtitleEs: 'Fe sobre las Aguas', subtitleEn: 'Faith on the Waters', artEmoji: '🌊', decorSymbols: ['🌊', '✦', '⚡'], sheenColors: ['rgba(96,165,250,0.35)', 'rgba(7,31,56,0.10)'], cornerGlyph: '✦' },
  },
  ciego_nacimiento: {
    id: 'ciego_nacimiento',
    nameEs: 'Ciego de Nacimiento',
    nameEn: 'Blind from Birth',
    category: 'Eventos',
    rarity: 'rare',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 20,
    descriptionEs: 'Jesús hace barro con su saliva, lo pone en los ojos de un ciego de nacimiento y le devuelve la vista.',
    descriptionEn: 'Jesus makes mud with saliva, applies it to a blind man\'s eyes, and restores his sight.',
    verseRef: 'Juan 9:7',
    verseTextEs: 'Ve a lavarte en el estanque de Siloé. Fue entonces, y se lavó, y regresó viendo.',
    datoDestacadoEs: 'El hombre sanado confrontó valientemente a los fariseos en su defensa de Jesús.',
    significadoBiblicoEs: 'Jesús es la luz del mundo que abre los ojos espirituales y físicos.',
    visualHints: ['mud', 'blind man', 'pool of Siloam', 'sight restored', 'Pharisees'],
    gradientColors: ['#0C1520', '#162535', '#1E3550'],
    accentColor: '#93C5FD',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/p0jzHq9oL5Y.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '👁️', subtitleEs: 'Estanque de Siloé', subtitleEn: 'Pool of Siloam', artEmoji: '👁️', decorSymbols: ['👁️', '💧', '✦'], sheenColors: ['rgba(147,197,253,0.32)', 'rgba(30,53,80,0.10)'], cornerGlyph: '✦' },
  },
  hijo_viuda_nain: {
    id: 'hijo_viuda_nain',
    nameEs: 'Hijo de la Viuda de Naín',
    nameEn: 'Son of the Widow of Nain',
    category: 'Eventos',
    rarity: 'rare',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 21,
    descriptionEs: 'Al ver a la viuda llorando junto a su hijo muerto, Jesús se conmueve y lo resucita.',
    descriptionEn: 'Seeing the widow weeping over her dead son, Jesus is moved with compassion and raises him.',
    verseRef: 'Lucas 7:14',
    verseTextEs: 'Entonces se acercó y tocó el féretro; y los que lo llevaban se detuvieron. Y dijo: Joven, a ti te digo, levántate.',
    datoDestacadoEs: 'Jesús actuó por pura compasión — nadie le había pedido nada.',
    significadoBiblicoEs: 'El corazón de Dios se mueve ante el sufrimiento humano.',
    visualHints: ['funeral procession', 'coffin', 'widow weeping', 'Jesus touching bier', 'crowd'],
    gradientColors: ['#120A1A', '#251535', '#3A2050'],
    accentColor: '#C084FC',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/zpkqBDrQZlM.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '✦', subtitleEs: 'Nain', subtitleEn: 'Nain', artEmoji: '🕊️', decorSymbols: ['🕊️', '✦', '😢'], sheenColors: ['rgba(192,132,252,0.30)', 'rgba(58,32,80,0.10)'], cornerGlyph: '✦' },
  },
  endemoniado_gadareno: {
    id: 'endemoniado_gadareno',
    nameEs: 'El Endemoniado Gadareno',
    nameEn: 'The Gadarene Demoniac',
    category: 'Eventos',
    rarity: 'rare',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 22,
    descriptionEs: 'Un hombre poseído por Legión es liberado; los demonios pasan a una piara de cerdos.',
    descriptionEn: 'A man possessed by Legion is freed; the demons enter a herd of pigs which rush into the sea.',
    verseRef: 'Marcos 5:9',
    verseTextEs: 'Le preguntó: ¿Cómo te llamas? Y respondió diciendo: Legión me llamo; porque somos muchos.',
    datoDestacadoEs: '"Legión" implicaba miles de demonios — el hombre fue completamente restaurado.',
    significadoBiblicoEs: 'Ningún nivel de posesión demoníaca supera la autoridad de Cristo.',
    visualHints: ['cliff', 'pigs rushing', 'healed man', 'chains broken', 'sea'],
    gradientColors: ['#0E0A18', '#1C1530', '#2B2048'],
    accentColor: '#818CF8',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/k-rfPPrErvE.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    motif: { topSymbol: '⛓️', subtitleEs: 'Legión Vencida', subtitleEn: 'Legion Defeated', artEmoji: '⛓️', decorSymbols: ['⛓️', '✦', '🐖'], sheenColors: ['rgba(129,140,248,0.30)', 'rgba(43,32,72,0.10)'], cornerGlyph: '✦' },
  },
  mujer_flujo: {
    id: 'mujer_flujo',
    nameEs: 'La Mujer del Flujo de Sangre',
    nameEn: 'Woman with the Issue of Blood',
    category: 'Personajes',
    rarity: 'rare',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 23,
    descriptionEs: 'Doce años enferma, esta mujer toca el manto de Jesús en secreto y es sana al instante.',
    descriptionEn: 'Ill for twelve years, this woman secretly touches Jesus\' cloak and is instantly healed.',
    verseRef: 'Lucas 8:48',
    verseTextEs: 'Y él le dijo: Hija, tu fe te ha salvado; ve en paz.',
    datoDestacadoEs: 'Jesús sintió que virtud había salido de Él — su poder responde a la fe.',
    significadoBiblicoEs: 'La fe desesperada y humilde activa el poder de Dios.',
    visualHints: ['crowd', 'cloak touch', 'woman faith', 'healing flow', 'peace'],
    gradientColors: ['#1A0A14', '#3A1530', '#5C204A'],
    accentColor: '#F472B6',
    motif: { topSymbol: '✦', subtitleEs: 'Tu Fe te Salvó', subtitleEn: 'Your Faith Has Saved You', artEmoji: '🩸', decorSymbols: ['✦', '🌹', '🙏'], sheenColors: ['rgba(244,114,182,0.30)', 'rgba(92,32,74,0.10)'], cornerGlyph: '✦' },
  },
  jesus_desaparece: {
    id: 'jesus_desaparece',
    nameEs: 'Jesús Desaparece',
    nameEn: 'Jesus Disappears',
    category: 'Eventos',
    rarity: 'rare',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 24,
    descriptionEs: 'La multitud en Nazaret intenta despeñarlo; pero Él pasa en medio de ellos y se va.',
    descriptionEn: 'The crowd in Nazareth tries to throw Him off a cliff, but He passes through them and leaves.',
    verseRef: 'Lucas 4:30',
    verseTextEs: 'Mas él pasó por en medio de ellos, y se fue.',
    datoDestacadoEs: 'Este hecho revela que Jesús podía volverse intangible o invisible cuando era su hora.',
    significadoBiblicoEs: 'La vida de Jesús estaba protegida hasta que su hora llegara.',
    visualHints: ['crowd', 'cliff', 'Nazareth', 'Jesus passing through', 'amazement'],
    gradientColors: ['#0D1520', '#162540', '#1E3860'],
    accentColor: '#BAE6FD',
    motif: { topSymbol: '✦', subtitleEs: 'Paso en Medio', subtitleEn: 'Passed Through', artEmoji: '🌫️', decorSymbols: ['🌫️', '✦', '🏔️'], sheenColors: ['rgba(186,230,253,0.28)', 'rgba(30,56,96,0.10)'], cornerGlyph: '✦' },
  },
  tempestad_calmada: {
    id: 'tempestad_calmada',
    nameEs: 'Tempestad Calmada',
    nameEn: 'Storm Stilled',
    category: 'Eventos',
    rarity: 'rare',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 25,
    descriptionEs: 'Los discípulos despiertan a Jesús aterrados; con una sola palabra el lago queda en calma perfecta.',
    descriptionEn: 'The terrified disciples wake Jesus; with a single word the lake becomes perfectly calm.',
    verseRef: 'Lucas 8:25',
    verseTextEs: '¿Dónde está vuestra fe? Y atemorizados, se maravillaron.',
    datoDestacadoEs: 'La expresión griega para la calma describe un silencio sobrenatural total.',
    significadoBiblicoEs: 'La paz de Cristo supera toda comprensión y toda tormenta.',
    visualHints: ['stormy lake', 'disciples', 'Jesus standing', 'instant calm', 'amazement'],
    gradientColors: ['#030810', '#060F20', '#091830'],
    accentColor: '#7DD3FC',
    motif: { topSymbol: '🌊', subtitleEs: '¿Dónde Está Tu Fe?', subtitleEn: 'Where Is Your Faith?', artEmoji: '🌊', decorSymbols: ['🌊', '⚡', '✦'], sheenColors: ['rgba(125,211,252,0.32)', 'rgba(9,24,48,0.10)'], cornerGlyph: '✦' },
  },

  // ÉPICAS (3)
  resurreccion_lazaro: {
    id: 'resurreccion_lazaro',
    nameEs: 'Resurrección de Lázaro',
    nameEn: 'Resurrection of Lazarus',
    category: 'Eventos',
    rarity: 'epic',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 26,
    descriptionEs: 'Lázaro lleva cuatro días muerto; Jesús llora, ora, y ordena: "¡Lázaro, ven fuera!"',
    descriptionEn: 'Lazarus has been dead four days; Jesus weeps, prays, and commands: "Lazarus, come forth!"',
    verseRef: 'Juan 11:43',
    verseTextEs: 'Y habiendo dicho esto, clamó a gran voz: ¡Lázaro, ven fuera!',
    datoDestacadoEs: '"Jesús lloró" — el versículo más corto de la Biblia y el más humano.',
    significadoBiblicoEs: 'Cristo es la resurrección y la vida — tiene poder sobre la muerte misma.',
    visualHints: ['tomb entrance', 'burial cloths', 'Lazarus emerging', 'crowd', 'Martha Mary weeping'],
    gradientColors: ['#0A0A20', '#141440', '#1E1E60'],
    accentColor: '#C084FC',
    imageUrl: 'https://staticfiles.net/s992MiD9pVwEokaNoJW62wGwzPsyGoEAhsBB93ylqQY/d/8ssJy-wZ-Aw.png',
    imageFocusX: 0.5,
    imageFocusY: 0.35,
    motif: { topSymbol: '✦', subtitleEs: '¡Lázaro, Ven Fuera!', subtitleEn: 'Lazarus, Come Forth!', artEmoji: '💜', decorSymbols: ['💜', '✦', '⚡'], sheenColors: ['rgba(192,132,252,0.45)', 'rgba(30,30,96,0.12)'], cornerGlyph: '✦' },
  },
  transfiguracion: {
    id: 'transfiguracion',
    nameEs: 'La Transfiguración',
    nameEn: 'The Transfiguration',
    category: 'Eventos',
    rarity: 'epic',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 27,
    descriptionEs: 'En el monte, el rostro de Jesús resplandece como el sol; Moisés y Elías aparecen con Él.',
    descriptionEn: 'On the mountain, Jesus\' face shines like the sun; Moses and Elijah appear with Him.',
    verseRef: 'Mateo 17:2',
    verseTextEs: 'Y se transfiguró delante de ellos, y resplandeció su rostro como el sol.',
    datoDestacadoEs: 'Pedro, Jacobo y Juan fueron los únicos testigos de este momento de gloria divina.',
    significadoBiblicoEs: 'Jesús es simultáneamente humano y plenamente divino — el Hijo de Dios.',
    visualHints: ['mountain', 'radiant face', 'white garments', 'Moses Elijah', 'cloud of glory'],
    gradientColors: ['#1A1400', '#3D3000', '#6B5800'],
    accentColor: '#FDE68A',
    motif: { topSymbol: '☀️', subtitleEs: 'Gloria Divina', subtitleEn: 'Divine Glory', artEmoji: '☀️', decorSymbols: ['☀️', '✦', '⛰️'], sheenColors: ['rgba(253,230,138,0.45)', 'rgba(107,88,0,0.12)'], cornerGlyph: '✦' },
  },
  jesus_aparece_resucitado: {
    id: 'jesus_aparece_resucitado',
    nameEs: 'Jesús Aparece Resucitado',
    nameEn: 'Jesus Appears Risen',
    category: 'Eventos',
    rarity: 'epic',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 28,
    descriptionEs: 'El resucitado se aparece a los discípulos a puertas cerradas; les muestra sus manos y su costado.',
    descriptionEn: 'The risen Christ appears to the disciples through locked doors; He shows them His hands and side.',
    verseRef: 'Juan 20:19',
    verseTextEs: 'La paz sea con vosotros. Y cuando les hubo dicho esto, les mostró las manos y el costado.',
    datoDestacadoEs: 'Jesús entró a través de puertas cerradas — su cuerpo resucitado tiene propiedades sobrenaturales.',
    significadoBiblicoEs: 'La resurrección de Cristo es la base de toda esperanza cristiana.',
    visualHints: ['locked room', 'risen Jesus', 'disciples', 'hands and side', 'peace'],
    gradientColors: ['#0D1A14', '#163020', '#1E4A2C'],
    accentColor: '#6EE7B7',
    motif: { topSymbol: '✝', subtitleEs: 'La Paz Sea con Vosotros', subtitleEn: 'Peace Be With You', artEmoji: '✝', decorSymbols: ['✝', '✦', '🕊️'], sheenColors: ['rgba(110,231,183,0.40)', 'rgba(30,74,44,0.12)'], cornerGlyph: '✦' },
  },

  // LEGENDARIA (1)
  jesus_glorificado: {
    id: 'jesus_glorificado',
    nameEs: 'Jesús Glorificado',
    nameEn: 'Jesus Glorified',
    category: 'Personajes',
    rarity: 'legendary',
    inStandardPool: false,
    albumGroup: 'milagros_2026',
    event: 'milagros',
    eventSet: 'milagros_2026',
    eventOrder: 29,
    descriptionEs: 'El Hijo de Dios en su gloria eterna — alfa y omega, el primero y el último, el que vive.',
    descriptionEn: 'The Son of God in His eternal glory — Alpha and Omega, the First and Last, the Living One.',
    verseRef: 'Apocalipsis 1:18',
    verseTextEs: 'Yo soy el primero y el último; y el que vivo, y estuve muerto; mas he aquí que vivo por los siglos de los siglos.',
    datoDestacadoEs: 'La carta legendaria de la colección — la imagen definitiva de la gloria de Cristo.',
    significadoBiblicoEs: 'Jesús es el Señor de la historia, la eternidad y toda la creación.',
    visualHints: ['radiant throne', 'alpha omega', 'crown of glory', 'golden light', 'cosmic presence'],
    gradientColors: ['#1A0E00', '#3D2200', '#7A4400'],
    accentColor: '#D4AF37',
    motif: { topSymbol: '✦', subtitleEs: 'Alfa y Omega', subtitleEn: 'Alpha and Omega', artEmoji: '✝', decorSymbols: ['✦', '☀️', '✝'], sheenColors: ['rgba(212,175,55,0.55)', 'rgba(122,68,0,0.15)'], cornerGlyph: '✦' },
  },

  // ─── SECRET REWARD — Milagros 2026 ───────────────────────────────────────────
  // Awarded for completing all 29 regular milagros cards (eventOrder 1-29)
  reino_de_dios: {
    id: 'reino_de_dios',
    nameEs: 'El Reino de Dios',
    nameEn: 'The Kingdom of God',
    category: 'Eventos',
    rarity: 'legendary',
    inStandardPool: false,
    albumGroup: 'secret_rewards',
    descriptionEs: 'Carta secreta otorgada por completar la colección "Milagros de Jesús". El Reino de Dios ha llegado.',
    descriptionEn: 'Secret card awarded for completing the "Miracles of Jesus" collection. The Kingdom of God has come.',
    verseRef: 'Marcos 1:15',
    verseTextEs: 'El tiempo se ha cumplido, y el reino de Dios se ha acercado; arrepentíos, y creed en el evangelio.',
    datoDestacadoEs: 'Carta secreta — obtenida completando la colección "Milagros de Jesús".',
    significadoBiblicoEs: 'Los milagros de Jesús son señales del Reino que ya ha llegado y que vendrá en plenitud.',
    visualHints: ['kingdom of heaven', 'golden gates', 'light rays', 'dove', 'eternal glory'],
    gradientColors: ['#0A0A00', '#1A1A00', '#2A2A00'],
    accentColor: '#D4AF37',
    motif: { topSymbol: '✦', subtitleEs: 'Colección Especial', subtitleEn: 'Special Collection', artEmoji: '👑', decorSymbols: ['👑', '✦', '☀️'], sheenColors: ['rgba(212,175,55,0.55)', 'rgba(42,42,0,0.15)'], cornerGlyph: '✦' },
  },

  // ─── END Milagros de Jesús 2026 ──────────────────────────────────────────────

  tomas: {
    id: 'tomas',
    nameEs: 'Tomás el Incrédulo',
    nameEn: 'Doubting Thomas',
    category: 'Personajes',
    rarity: 'rare',
    inStandardPool: false,
    albumGroup: 'pascua_2026',
    event: 'pascua',
    eventSet: 'pascua_2026',
    eventOrder: 14,
    imageUrl: 'https://images.composerapi.com/019c33a9-4a45-71bd-8908-f785cc52f6a1/assets/images/image_1772847569_1772847570281_019cc5f3-1d69-7112-9e0f-d5e391048e95.png',
    imageFocusX: 0.5,
    imageFocusY: 0.4,
    descriptionEs: 'Tomás duda de la resurrección hasta ver a Jesús resucitado.',
    descriptionEn: 'Thomas doubts the resurrection until he sees the risen Jesus.',
    verseRef: 'Juan 20:27',
    verseTextEs: 'Pon aquí tu dedo, y mira mis manos; y acerca tu mano, y métela en mi costado.',
    datoDestacadoEs: '"Señor mío y Dios mío."',
    significadoBiblicoEs: 'La fe que nace después de la duda.',
    visualHints: ['hands', 'wounds', 'doubt', 'faith', 'risen Jesus'],
    gradientColors: ['#0A1020', '#121C38', '#1A2850'],
    accentColor: '#6090D0',
    motif: {
      topSymbol: '✦',
      subtitleEs: 'Fe y Duda',
      subtitleEn: 'Faith & Doubt',
      artEmoji: '🙏',
      decorSymbols: ['🙏', '✦', '✝'],
      sheenColors: ['rgba(96,144,208,0.28)', 'rgba(60,100,160,0.08)'],
      cornerGlyph: '✦',
    },
  },
};

export const ALL_CARD_IDS = Object.keys(BIBLICAL_CARDS);

/** Card IDs eligible for standard random pack draws */
export const STANDARD_POOL_IDS = Object.values(BIBLICAL_CARDS)
  .filter((c) => c.inStandardPool)
  .map((c) => c.id);

/** Card IDs belonging to the Pascua 2026 event set */
export const PASCUA_2026_POOL_IDS = Object.values(BIBLICAL_CARDS)
  .filter((c) => c.eventSet === 'pascua_2026')
  .map((c) => c.id);

/** Card IDs belonging to the Milagros 2026 event set */
export const MILAGROS_2026_POOL_IDS = Object.values(BIBLICAL_CARDS)
  .filter((c) => c.eventSet === 'milagros_2026')
  .map((c) => c.id);

/**
 * Returns all cards belonging to a given eventSet, sorted by eventOrder.
 * Used by the album to render event sections in chronological order.
 */
export function getEventSetCards(eventSet: string): BiblicalCard[] {
  return Object.values(BIBLICAL_CARDS)
    .filter((c) => c.eventSet === eventSet)
    .sort((a, b) => (a.eventOrder ?? 0) - (b.eventOrder ?? 0));
}

export function getCard(id: string): BiblicalCard | undefined {
  return BIBLICAL_CARDS[id];
}

/** Cards that live in the Cartas Secretas album group */
export const SECRET_REWARD_IDS = Object.values(BIBLICAL_CARDS)
  .filter((c) => c.albumGroup === 'secret_rewards')
  .map((c) => c.id);

/** Returns all cards for a given albumGroup */
export function getAlbumGroupCards(group: BiblicalCard['albumGroup']): BiblicalCard[] {
  return Object.values(BIBLICAL_CARDS).filter((c) => c.albumGroup === group);
}
