// App constants and theme configuration

export const APP_CONFIG = {
  name: 'Daily Light',
  company: 'ChaViTico Games',
  splashDuration: 2000,
} as const;

export const THEMES = {
  dawn: {
    name: 'Dawn',
    nameEs: 'Amanecer',
    primary: '#E8A87C',
    secondary: '#C38D9E',
    accent: '#41B3A3',
    background: '#FDF6E3',
    backgroundDark: '#1A1A2E',
    surface: '#FFFFFF',
    surfaceDark: '#252542',
    text: '#2D2D2D',
    textDark: '#F5F5F5',
    textMuted: '#6B6B6B',
    textMutedDark: '#A0A0A0',
  },
  dusk: {
    name: 'Dusk',
    nameEs: 'Atardecer',
    primary: '#9B5DE5',
    secondary: '#F15BB5',
    accent: '#00BBF9',
    background: '#0F0E17',
    backgroundDark: '#0F0E17',
    surface: '#1E1E2F',
    surfaceDark: '#1E1E2F',
    text: '#FFFFFE',
    textDark: '#FFFFFE',
    textMuted: '#A7A9BE',
    textMutedDark: '#A7A9BE',
  },
  ocean: {
    name: 'Ocean',
    nameEs: 'Oceano',
    primary: '#0077B6',
    secondary: '#00B4D8',
    accent: '#90E0EF',
    background: '#F8FBFD',
    backgroundDark: '#0A1628',
    surface: '#FFFFFF',
    surfaceDark: '#152238',
    text: '#1B263B',
    textDark: '#E8F4F8',
    textMuted: '#577590',
    textMutedDark: '#8DB3C7',
  },
  forest: {
    name: 'Forest',
    nameEs: 'Bosque',
    primary: '#2D6A4F',
    secondary: '#40916C',
    accent: '#95D5B2',
    background: '#F7FDF9',
    backgroundDark: '#0D1F17',
    surface: '#FFFFFF',
    surfaceDark: '#1A3328',
    text: '#1B4332',
    textDark: '#D8F3DC',
    textMuted: '#52796F',
    textMutedDark: '#74C69D',
  },
  rose: {
    name: 'Rose',
    nameEs: 'Rosa',
    primary: '#C9184A',
    secondary: '#FF758F',
    accent: '#FFB3C1',
    background: '#FFF5F7',
    backgroundDark: '#1A0A10',
    surface: '#FFFFFF',
    surfaceDark: '#2D1520',
    text: '#590D22',
    textDark: '#FFE5EC',
    textMuted: '#A4133C',
    textMutedDark: '#FF8FA3',
  },
} as const;

export const DEFAULT_AVATARS = [
  { id: 'avatar_dove', name: 'Dove', nameEs: 'Paloma', emoji: '🕊️', description: 'Peace of the Spirit', descriptionEs: 'Paz del Espiritu', unlocked: true, rarity: 'common' },
  { id: 'avatar_sun', name: 'Sun', nameEs: 'Sol', emoji: '☀️', description: 'Light of the world', descriptionEs: 'Luz del mundo', unlocked: true, rarity: 'common' },
  { id: 'avatar_star', name: 'Star', nameEs: 'Estrella', emoji: '⭐', description: 'Guiding light', descriptionEs: 'Luz que guia', unlocked: true, rarity: 'common' },
  { id: 'avatar_heart', name: 'Heart', nameEs: 'Corazon', emoji: '❤️', description: 'Love without end', descriptionEs: 'Amor sin fin', unlocked: true, rarity: 'common' },
  { id: 'avatar_cross', name: 'Cross', nameEs: 'Cruz', emoji: '✝️', description: 'Symbol of salvation', descriptionEs: 'Simbolo de salvacion', unlocked: true, rarity: 'common' },
  { id: 'avatar_candle', name: 'Candle', nameEs: 'Vela', emoji: '🕯️', description: 'Illuminating faith', descriptionEs: 'Fe que ilumina', unlocked: true, rarity: 'common' },
  { id: 'avatar_book', name: 'Book', nameEs: 'Libro', emoji: '📖', description: 'The living Word', descriptionEs: 'La Palabra viva', unlocked: true, rarity: 'common' },
  { id: 'avatar_praying', name: 'Praying', nameEs: 'Orando', emoji: '🙏', description: 'Hands of devotion', descriptionEs: 'Manos de devocion', unlocked: true, rarity: 'common' },
  { id: 'avatar_rainbow', name: 'Rainbow', nameEs: 'Arcoiris', emoji: '🌈', description: 'Promise of God', descriptionEs: 'Promesa de Dios', price: 200, rarity: 'rare' },
  { id: 'avatar_crown', name: 'Crown', nameEs: 'Corona', emoji: '👑', description: 'Crown of glory', descriptionEs: 'Corona de gloria', price: 500, rarity: 'epic' },
  { id: 'avatar_angel', name: 'Angel', nameEs: 'Angel', emoji: '😇', description: 'Heavenly messenger', descriptionEs: 'Mensajero celestial', price: 300, rarity: 'rare' },
  { id: 'avatar_olive', name: 'Olive Branch', nameEs: 'Rama de Olivo', emoji: '🫒', description: 'Sign of peace', descriptionEs: 'Signo de paz', price: 250, rarity: 'rare' },
  { id: 'avatar_lamb', name: 'Lamb', nameEs: 'Cordero', emoji: '🐑', description: 'Gentle and pure', descriptionEs: 'Gentil y puro', price: 400, rarity: 'rare' },
  { id: 'avatar_fish', name: 'Fish', nameEs: 'Pez', emoji: '🐟', description: 'Early Christian symbol', descriptionEs: 'Simbolo cristiano primitivo', price: 150, rarity: 'common' },
  // ============================================
  // AVATARS V2 - Premium Illustrated Collection
  // Collection 1: Simbolos de Fe (Symbols of Faith)
  // ============================================
  { id: 'avatar_v2_paloma_paz', name: 'Dove of Peace', nameEs: 'Paloma de Paz', emoji: '🕊️', description: 'Premium illustrated dove with olive branch', descriptionEs: 'Paloma ilustrada premium con rama de olivo', price: 450, rarity: 'rare', collectionId: 'collection_v2_simbolos_fe', isV2: true },
  { id: 'avatar_v2_cruz_radiante', name: 'Radiant Cross', nameEs: 'Cruz Radiante', emoji: '✝️', description: 'Glowing cross with divine rays', descriptionEs: 'Cruz resplandeciente con rayos divinos', price: 500, rarity: 'rare', collectionId: 'collection_v2_simbolos_fe', isV2: true },
  { id: 'avatar_v2_lampara_aceite', name: 'Oil Lamp', nameEs: 'Lampara de Aceite', emoji: '🪔', description: 'Ancient oil lamp burning bright', descriptionEs: 'Lampara de aceite antigua ardiendo brillante', price: 280, rarity: 'common', collectionId: 'collection_v2_simbolos_fe', isV2: true },
  { id: 'avatar_v2_corona_vida', name: 'Crown of Life', nameEs: 'Corona de Vida', emoji: '👑', description: 'Majestic crown adorned with jewels', descriptionEs: 'Corona majestuosa adornada con joyas', price: 2500, rarity: 'epic', collectionId: 'collection_v2_simbolos_fe', isV2: true },
  { id: 'avatar_v2_biblia_abierta', name: 'Open Bible', nameEs: 'Biblia Abierta', emoji: '📖', description: 'Holy scriptures with radiant glow', descriptionEs: 'Escrituras santas con resplandor radiante', price: 320, rarity: 'common', collectionId: 'collection_v2_simbolos_fe', isV2: true },
  { id: 'avatar_v2_caliz', name: 'Holy Chalice', nameEs: 'Caliz Sagrado', emoji: '🏆', description: 'Sacred cup of communion', descriptionEs: 'Copa sagrada de la comunion', price: 550, rarity: 'rare', collectionId: 'collection_v2_simbolos_fe', isV2: true },
  { id: 'avatar_v2_ancla_esperanza', name: 'Anchor of Hope', nameEs: 'Ancla de Esperanza', emoji: '⚓', description: 'Steadfast anchor representing hope', descriptionEs: 'Ancla firme representando esperanza', price: 480, rarity: 'rare', collectionId: 'collection_v2_simbolos_fe', isV2: true },
  { id: 'avatar_v2_pan_uvas', name: 'Bread and Grapes', nameEs: 'Pan y Uvas', emoji: '🍇', description: 'Communion bread with grapes', descriptionEs: 'Pan de comunion con uvas', price: 350, rarity: 'common', collectionId: 'collection_v2_simbolos_fe', isV2: true },
  // ============================================
  // Collection 2: Naturaleza Biblica (Biblical Nature)
  // ============================================
  { id: 'avatar_v2_rama_olivo', name: 'Olive Branch', nameEs: 'Rama de Olivo', emoji: '🌿', description: 'Lush olive branch of peace', descriptionEs: 'Exuberante rama de olivo de paz', price: 260, rarity: 'common', collectionId: 'collection_v2_naturaleza', isV2: true },
  { id: 'avatar_v2_pez_ichthys', name: 'Ichthys Fish', nameEs: 'Pez Ichthys', emoji: '🐠', description: 'Ornate Christian fish symbol', descriptionEs: 'Simbolo del pez cristiano ornamentado', price: 300, rarity: 'common', collectionId: 'collection_v2_naturaleza', isV2: true },
  { id: 'avatar_v2_cordero', name: 'Lamb of God', nameEs: 'Cordero de Dios', emoji: '🐑', description: 'Pure white lamb with halo', descriptionEs: 'Cordero blanco puro con aureola', price: 600, rarity: 'rare', collectionId: 'collection_v2_naturaleza', isV2: true },
  { id: 'avatar_v2_leon', name: 'Lion of Judah', nameEs: 'Leon de Juda', emoji: '🦁', description: 'Majestic lion with golden mane', descriptionEs: 'Leon majestuoso con melena dorada', price: 3500, rarity: 'epic', collectionId: 'collection_v2_naturaleza', isV2: true },
  { id: 'avatar_v2_semilla_mostaza', name: 'Mustard Seed', nameEs: 'Semilla de Mostaza', emoji: '🌱', description: 'Tiny seed growing into faith', descriptionEs: 'Pequena semilla creciendo en fe', price: 520, rarity: 'rare', collectionId: 'collection_v2_naturaleza', isV2: true },
  { id: 'avatar_v2_vid_racimos', name: 'Vine and Grapes', nameEs: 'Vid y Racimos', emoji: '🍇', description: 'Abundant vine with clusters', descriptionEs: 'Vid abundante con racimos', price: 340, rarity: 'common', collectionId: 'collection_v2_naturaleza', isV2: true },
  // ============================================
  // Collection 3: Virtudes (Virtues)
  // ============================================
  { id: 'avatar_v2_gratitud', name: 'Gratitude', nameEs: 'Gratitud', emoji: '💖', description: 'Heart radiating thankful light', descriptionEs: 'Corazon irradiando luz de agradecimiento', price: 320, rarity: 'common', collectionId: 'collection_v2_virtudes', isV2: true },
  { id: 'avatar_v2_fe', name: 'Faith', nameEs: 'Fe', emoji: '🛡️', description: 'Shield of unwavering faith', descriptionEs: 'Escudo de fe inquebrantable', price: 580, rarity: 'rare', collectionId: 'collection_v2_virtudes', isV2: true },
  { id: 'avatar_v2_amor', name: 'Love', nameEs: 'Amor', emoji: '🤲', description: 'Hands reaching with compassion', descriptionEs: 'Manos extendidas con compasion', price: 550, rarity: 'rare', collectionId: 'collection_v2_virtudes', isV2: true },
  { id: 'avatar_v2_paz', name: 'Peace', nameEs: 'Paz', emoji: '☮️', description: 'Dove with olive in serene sky', descriptionEs: 'Paloma con olivo en cielo sereno', price: 500, rarity: 'rare', collectionId: 'collection_v2_virtudes', isV2: true },
  { id: 'avatar_v2_gozo', name: 'Joy', nameEs: 'Gozo', emoji: '✨', description: 'Radiant sun with sparkles', descriptionEs: 'Sol radiante con destellos', price: 350, rarity: 'common', collectionId: 'collection_v2_virtudes', isV2: true },
  { id: 'avatar_v2_valentia', name: 'Courage', nameEs: 'Valentia', emoji: '⚔️', description: 'Sword of light conquering darkness', descriptionEs: 'Espada de luz conquistando oscuridad', price: 1800, rarity: 'epic', collectionId: 'collection_v2_virtudes', isV2: true },
  // ============================================
  // Collection 4: Kids Friendly (Infantil)
  // ============================================
  { id: 'avatar_v2_estrellita', name: 'Little Star', nameEs: 'Estrellita', emoji: '🌟', description: 'Cute twinkling star with smile', descriptionEs: 'Linda estrella parpadeante con sonrisa', price: 200, rarity: 'common', collectionId: 'collection_v2_kids', isV2: true },
  { id: 'avatar_v2_arcoiris', name: 'Soft Rainbow', nameEs: 'Arcoiris Suave', emoji: '🌈', description: 'Gentle pastel rainbow arc', descriptionEs: 'Suave arco iris en tonos pastel', price: 240, rarity: 'common', collectionId: 'collection_v2_kids', isV2: true },
  { id: 'avatar_v2_nube', name: 'Happy Cloud', nameEs: 'Nube Feliz', emoji: '☁️', description: 'Fluffy cloud with happy face', descriptionEs: 'Nube esponjosa con cara feliz', price: 450, rarity: 'rare', collectionId: 'collection_v2_kids', isV2: true },
  { id: 'avatar_v2_angelito', name: 'Little Angel', nameEs: 'Angelito', emoji: '👼', description: 'Adorable cherub with wings', descriptionEs: 'Adorable querubin con alas', price: 550, rarity: 'rare', collectionId: 'collection_v2_kids', isV2: true },
  // ============================================
  // EXCLUSIVE CHEST AVATARS - Solo del Cofre Semanal
  // ============================================
  { id: 'avatar_chest_serafin', name: 'Seraph', nameEs: 'Serafin', emoji: '🔥', description: 'Six-winged heavenly being of fire', descriptionEs: 'Ser celestial de fuego con seis alas', chestOnly: true, rarity: 'epic' },
  { id: 'avatar_chest_zarza', name: 'Burning Bush', nameEs: 'Zarza Ardiente', emoji: '🌳', description: 'The holy fire of divine encounter', descriptionEs: 'El fuego sagrado del encuentro divino', chestOnly: true, rarity: 'epic' },
  { id: 'avatar_chest_mana', name: 'Manna', nameEs: 'Mana del Cielo', emoji: '❄️', description: 'Bread from heaven, daily provision', descriptionEs: 'Pan del cielo, provision diaria', chestOnly: true, rarity: 'rare' },
  { id: 'avatar_chest_trompeta', name: 'Shofar', nameEs: 'Shofar', emoji: '📯', description: 'Horn of proclamation and glory', descriptionEs: 'Cuerno de proclamacion y gloria', chestOnly: true, rarity: 'epic' },
  { id: 'avatar_chest_palacio', name: 'Heavenly Gate', nameEs: 'Puerta Celestial', emoji: '🏛️', description: 'Gateway to the eternal kingdom', descriptionEs: 'Puerta al reino eterno', chestOnly: true, rarity: 'epic' },
] as const;

export const STORE_ITEMS = [
  {
    id: 'nickname_change',
    type: 'nickname_change' as const,
    name: 'Nickname Change',
    nameEs: 'Cambio de Apodo',
    description: 'Change your nickname once',
    descriptionEs: 'Cambia tu apodo una vez',
    imageUrl: '',
    price: 500,
    category: 'special',
  },
  ...DEFAULT_AVATARS.filter(a => 'price' in a).map(a => ({
    id: a.id,
    type: 'avatar' as const,
    name: a.name,
    nameEs: a.name,
    description: `Unlock the ${a.name} avatar`,
    descriptionEs: `Desbloquea el avatar ${a.name}`,
    imageUrl: '',
    price: (a as { price: number }).price,
    category: 'avatars',
  })),
];

// Purchasable Themes (from store - these are the metadata parsed)
export const PURCHASABLE_THEMES: Record<string, {
  id: string;
  name: string;
  nameEs: string;
  description: string;
  descriptionEs: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    backgroundDark: string;
    surface: string;
    surfaceDark: string;
    text: string;
    textDark: string;
    textMuted: string;
    textMutedDark: string;
  };
  price: number;
  rarity: string;
}> = {
  theme_amanecer: {
    id: 'theme_amanecer',
    name: 'Sunrise',
    nameEs: 'Amanecer',
    description: 'Warm tones of a new day',
    descriptionEs: 'Tonos calidos de un nuevo dia',
    colors: {
      primary: '#E8A87C',
      secondary: '#C38D9E',
      accent: '#41B3A3',
      background: '#FDF6E3',
      backgroundDark: '#1A1A2E',
      surface: '#FFFFFF',
      surfaceDark: '#252542',
      text: '#2D2D2D',
      textDark: '#F5F5F5',
      textMuted: '#6B6B6B',
      textMutedDark: '#A0A0A0',
    },
    price: 0,
    rarity: 'common',
  },
  theme_noche_paz: {
    id: 'theme_noche_paz',
    name: 'Peaceful Night',
    nameEs: 'Noche de Paz',
    description: 'Calm serenity under the stars',
    descriptionEs: 'Serenidad bajo las estrellas',
    colors: {
      primary: '#5C6BC0',
      secondary: '#7986CB',
      accent: '#9FA8DA',
      background: '#0D1B2A',
      backgroundDark: '#0D1B2A',
      surface: '#1B263B',
      surfaceDark: '#1B263B',
      text: '#E8F4F8',
      textDark: '#E8F4F8',
      textMuted: '#8DB3C7',
      textMutedDark: '#8DB3C7',
    },
    price: 400,
    rarity: 'rare',
  },
  theme_bosque: {
    id: 'theme_bosque',
    name: 'Forest',
    nameEs: 'Bosque',
    description: 'Refreshing green sanctuary',
    descriptionEs: 'Santuario verde refrescante',
    colors: {
      primary: '#2D6A4F',
      secondary: '#40916C',
      accent: '#95D5B2',
      background: '#F7FDF9',
      backgroundDark: '#0D1F17',
      surface: '#FFFFFF',
      surfaceDark: '#1A3328',
      text: '#1B4332',
      textDark: '#D8F3DC',
      textMuted: '#52796F',
      textMutedDark: '#74C69D',
    },
    price: 300,
    rarity: 'common',
  },
  theme_desierto: {
    id: 'theme_desierto',
    name: 'Desert',
    nameEs: 'Desierto',
    description: 'Warm sands of contemplation',
    descriptionEs: 'Arenas calidas de contemplacion',
    colors: {
      primary: '#D4A373',
      secondary: '#CCD5AE',
      accent: '#E9EDC9',
      background: '#FEFAE0',
      backgroundDark: '#2C2416',
      surface: '#FFFFFF',
      surfaceDark: '#3D3426',
      text: '#5C4B37',
      textDark: '#F5E6D3',
      textMuted: '#8B7355',
      textMutedDark: '#C4A77D',
    },
    price: 350,
    rarity: 'common',
  },
  theme_promesa: {
    id: 'theme_promesa',
    name: 'Promise',
    nameEs: 'Promesa',
    description: 'Royal hues of divine covenant',
    descriptionEs: 'Tonos reales del pacto divino',
    colors: {
      primary: '#7B2CBF',
      secondary: '#9D4EDD',
      accent: '#C77DFF',
      background: '#F8F4FC',
      backgroundDark: '#1A0A2E',
      surface: '#FFFFFF',
      surfaceDark: '#2D1B4E',
      text: '#3C096C',
      textDark: '#E0AAFF',
      textMuted: '#7B2CBF',
      textMutedDark: '#C77DFF',
    },
    price: 600,
    rarity: 'rare',
  },
  theme_minimal: {
    id: 'theme_minimal',
    name: 'Minimal Light',
    nameEs: 'Minimal Claro',
    description: 'Clean simplicity for focus',
    descriptionEs: 'Simplicidad limpia para el enfoque',
    colors: {
      primary: '#374151',
      secondary: '#6B7280',
      accent: '#9CA3AF',
      background: '#F9FAFB',
      backgroundDark: '#111827',
      surface: '#FFFFFF',
      surfaceDark: '#1F2937',
      text: '#111827',
      textDark: '#F9FAFB',
      textMuted: '#6B7280',
      textMutedDark: '#9CA3AF',
    },
    price: 200,
    rarity: 'common',
  },
  // ============================================
  // THEMES V2 - Premium Palettes
  // ============================================
  theme_amanecer_dorado: {
    id: 'theme_amanecer_dorado',
    name: 'Golden Dawn',
    nameEs: 'Amanecer Dorado',
    description: 'Radiant gold hues of a new beginning',
    descriptionEs: 'Tonos dorados radiantes de un nuevo comienzo',
    colors: {
      primary: '#D97706',
      secondary: '#F59E0B',
      accent: '#FCD34D',
      background: '#FFFBEB',
      backgroundDark: '#1C1917',
      surface: '#FFFFFF',
      surfaceDark: '#292524',
      text: '#78350F',
      textDark: '#FEF3C7',
      textMuted: '#B45309',
      textMutedDark: '#FCD34D',
    },
    price: 500,
    rarity: 'rare',
  },
  theme_noche_profunda: {
    id: 'theme_noche_profunda',
    name: 'Deep Night Peace',
    nameEs: 'Noche de Paz Profunda',
    description: 'Serene darkness with celestial stars',
    descriptionEs: 'Oscuridad serena con estrellas celestiales',
    colors: {
      primary: '#4338CA',
      secondary: '#6366F1',
      accent: '#A5B4FC',
      background: '#0F0D1A',
      backgroundDark: '#0F0D1A',
      surface: '#1E1B2E',
      surfaceDark: '#1E1B2E',
      text: '#E0E7FF',
      textDark: '#E0E7FF',
      textMuted: '#818CF8',
      textMutedDark: '#818CF8',
    },
    price: 550,
    rarity: 'rare',
  },
  theme_bosque_sereno: {
    id: 'theme_bosque_sereno',
    name: 'Serene Forest',
    nameEs: 'Bosque Sereno',
    description: 'Peaceful green sanctuary of nature',
    descriptionEs: 'Santuario verde y pacifico de la naturaleza',
    colors: {
      primary: '#059669',
      secondary: '#10B981',
      accent: '#6EE7B7',
      background: '#ECFDF5',
      backgroundDark: '#022C22',
      surface: '#FFFFFF',
      surfaceDark: '#064E3B',
      text: '#064E3B',
      textDark: '#D1FAE5',
      textMuted: '#047857',
      textMutedDark: '#6EE7B7',
    },
    price: 300,
    rarity: 'common',
  },
  theme_desierto_suave: {
    id: 'theme_desierto_suave',
    name: 'Soft Desert',
    nameEs: 'Desierto Suave',
    description: 'Warm sand tones of contemplation',
    descriptionEs: 'Tonos arena calidos de contemplacion',
    colors: {
      primary: '#C2410C',
      secondary: '#EA580C',
      accent: '#FED7AA',
      background: '#FFF7ED',
      backgroundDark: '#1C1410',
      surface: '#FFFFFF',
      surfaceDark: '#292018',
      text: '#7C2D12',
      textDark: '#FFEDD5',
      textMuted: '#C2410C',
      textMutedDark: '#FDBA74',
    },
    price: 280,
    rarity: 'common',
  },
  theme_promesa_violeta: {
    id: 'theme_promesa_violeta',
    name: 'Violet Promise',
    nameEs: 'Promesa Violeta',
    description: 'Royal purple of divine covenant',
    descriptionEs: 'Purpura real del pacto divino',
    colors: {
      primary: '#7C3AED',
      secondary: '#8B5CF6',
      accent: '#C4B5FD',
      background: '#F5F3FF',
      backgroundDark: '#1E1033',
      surface: '#FFFFFF',
      surfaceDark: '#2E1B4B',
      text: '#4C1D95',
      textDark: '#EDE9FE',
      textMuted: '#7C3AED',
      textMutedDark: '#A78BFA',
    },
    price: 650,
    rarity: 'rare',
  },
  theme_cielo_gloria: {
    id: 'theme_cielo_gloria',
    name: 'Sky of Glory',
    nameEs: 'Cielo de Gloria',
    description: 'Majestic sky blue of heavenly realms',
    descriptionEs: 'Azul cielo majestuoso de reinos celestiales',
    colors: {
      primary: '#0284C7',
      secondary: '#0EA5E9',
      accent: '#7DD3FC',
      background: '#F0F9FF',
      backgroundDark: '#082F49',
      surface: '#FFFFFF',
      surfaceDark: '#0C4A6E',
      text: '#075985',
      textDark: '#E0F2FE',
      textMuted: '#0369A1',
      textMutedDark: '#38BDF8',
    },
    price: 550,
    rarity: 'rare',
  },
  theme_mar_misericordia: {
    id: 'theme_mar_misericordia',
    name: 'Sea of Mercy',
    nameEs: 'Mar de Misericordia',
    description: 'Teal depths of endless grace',
    descriptionEs: 'Profundidades aguamarina de gracia infinita',
    colors: {
      primary: '#0D9488',
      secondary: '#14B8A6',
      accent: '#5EEAD4',
      background: '#F0FDFA',
      backgroundDark: '#042F2E',
      surface: '#FFFFFF',
      surfaceDark: '#134E4A',
      text: '#115E59',
      textDark: '#CCFBF1',
      textMuted: '#0F766E',
      textMutedDark: '#2DD4BF',
    },
    price: 320,
    rarity: 'common',
  },
  theme_fuego_espiritu: {
    id: 'theme_fuego_espiritu',
    name: 'Fire of the Spirit',
    nameEs: 'Fuego del Espiritu',
    description: 'Holy flames of divine presence',
    descriptionEs: 'Llamas santas de la presencia divina',
    colors: {
      primary: '#DC2626',
      secondary: '#F97316',
      accent: '#FDE68A',
      background: '#FEF2F2',
      backgroundDark: '#1C1410',
      surface: '#FFFFFF',
      surfaceDark: '#2A1810',
      text: '#991B1B',
      textDark: '#FEE2E2',
      textMuted: '#DC2626',
      textMutedDark: '#FCA5A5',
    },
    price: 1500,
    rarity: 'epic',
  },
  theme_jardin_gracia: {
    id: 'theme_jardin_gracia',
    name: 'Garden of Grace',
    nameEs: 'Jardin de Gracia',
    description: 'Blooming garden of divine favor',
    descriptionEs: 'Jardin florido del favor divino',
    colors: {
      primary: '#DB2777',
      secondary: '#EC4899',
      accent: '#FBCFE8',
      background: '#FDF2F8',
      backgroundDark: '#1A0D14',
      surface: '#FFFFFF',
      surfaceDark: '#2D1520',
      text: '#831843',
      textDark: '#FCE7F3',
      textMuted: '#BE185D',
      textMutedDark: '#F472B6',
    },
    price: 380,
    rarity: 'common',
  },
  theme_olivo_paz: {
    id: 'theme_olivo_paz',
    name: 'Olive and Peace',
    nameEs: 'Olivo y Paz',
    description: 'Ancient olive hues of harmony',
    descriptionEs: 'Tonos antiguos de olivo y armonia',
    colors: {
      primary: '#65A30D',
      secondary: '#84CC16',
      accent: '#BEF264',
      background: '#F7FEE7',
      backgroundDark: '#1A2E05',
      surface: '#FFFFFF',
      surfaceDark: '#3F6212',
      text: '#365314',
      textDark: '#ECFCCB',
      textMuted: '#4D7C0F',
      textMutedDark: '#A3E635',
    },
    price: 300,
    rarity: 'common',
  },
  theme_trono_azul: {
    id: 'theme_trono_azul',
    name: 'Blue Throne',
    nameEs: 'Trono Azul',
    description: 'Royal blue of the heavenly throne',
    descriptionEs: 'Azul real del trono celestial',
    colors: {
      primary: '#1D4ED8',
      secondary: '#3B82F6',
      accent: '#93C5FD',
      background: '#EFF6FF',
      backgroundDark: '#0F172A',
      surface: '#FFFFFF',
      surfaceDark: '#1E3A5F',
      text: '#1E3A8A',
      textDark: '#DBEAFE',
      textMuted: '#2563EB',
      textMutedDark: '#60A5FA',
    },
    price: 600,
    rarity: 'rare',
  },
  theme_lampara_encendida: {
    id: 'theme_lampara_encendida',
    name: 'Burning Lamp',
    nameEs: 'Lampara Encendida',
    description: 'Warm glow of the ever-burning lamp',
    descriptionEs: 'Resplandor calido de la lampara ardiente',
    colors: {
      primary: '#B45309',
      secondary: '#D97706',
      accent: '#FDE68A',
      background: '#FFFBEB',
      backgroundDark: '#1C1712',
      surface: '#FFFFFF',
      surfaceDark: '#292418',
      text: '#78350F',
      textDark: '#FEF3C7',
      textMuted: '#D97706',
      textMutedDark: '#FBBF24',
    },
    price: 520,
    rarity: 'rare',
  },
  theme_pergamino_antiguo: {
    id: 'theme_pergamino_antiguo',
    name: 'Ancient Parchment',
    nameEs: 'Pergamino Antiguo',
    description: 'Timeless sepia of sacred scrolls',
    descriptionEs: 'Sepia atemporal de pergaminos sagrados',
    colors: {
      primary: '#A16207',
      secondary: '#CA8A04',
      accent: '#FEF08A',
      background: '#FEFCE8',
      backgroundDark: '#1A1608',
      surface: '#FFFFFF',
      surfaceDark: '#2E2810',
      text: '#713F12',
      textDark: '#FEF9C3',
      textMuted: '#A16207',
      textMutedDark: '#FACC15',
    },
    price: 350,
    rarity: 'common',
  },
  theme_luz_celestial: {
    id: 'theme_luz_celestial',
    name: 'Celestial Light',
    nameEs: 'Luz Celestial',
    description: 'Ethereal glow from heavenly realms',
    descriptionEs: 'Resplandor etereo de los cielos',
    colors: {
      primary: '#7C3AED',
      secondary: '#60A5FA',
      accent: '#FDE68A',
      background: '#FAFAFA',
      backgroundDark: '#0F0A1A',
      surface: '#FFFFFF',
      surfaceDark: '#1A1028',
      text: '#1F2937',
      textDark: '#F3F4F6',
      textMuted: '#6366F1',
      textMutedDark: '#A5B4FC',
    },
    price: 1800,
    rarity: 'epic',
  },
};

// Avatar Frames
export const AVATAR_FRAMES: Record<string, {
  id: string;
  name: string;
  nameEs: string;
  description: string;
  descriptionEs: string;
  color: string;
  price?: number;
  rarity: string;
  chestOnly?: boolean;
}> = {
  frame_dorado: { id: 'frame_dorado', name: 'Golden', nameEs: 'Dorado', description: 'Precious as refined gold', descriptionEs: 'Precioso como oro refinado', color: '#FFD700', price: 300, rarity: 'rare' },
  frame_plata: { id: 'frame_plata', name: 'Silver', nameEs: 'Plata', description: 'Pure and elegant', descriptionEs: 'Puro y elegante', color: '#C0C0C0', price: 200, rarity: 'common' },
  frame_azul: { id: 'frame_azul', name: 'Blue Hope', nameEs: 'Azul Esperanza', description: 'Color of heavenly hope', descriptionEs: 'Color de esperanza celestial', color: '#4A90D9', price: 250, rarity: 'common' },
  frame_verde: { id: 'frame_verde', name: 'Green Life', nameEs: 'Verde Vida', description: 'Growth and renewal', descriptionEs: 'Crecimiento y renovacion', color: '#4CAF50', price: 250, rarity: 'common' },
  frame_luz: { id: 'frame_luz', name: 'Soft Light', nameEs: 'Luz Suave', description: 'Gentle divine radiance', descriptionEs: 'Suave resplandor divino', color: '#FFF8DC', price: 350, rarity: 'rare' },
  frame_corona: { id: 'frame_corona', name: 'Leaf Crown', nameEs: 'Corona Hojas', description: 'Crown of righteousness', descriptionEs: 'Corona de justicia', color: '#228B22', price: 400, rarity: 'rare' },
  frame_estrellas: { id: 'frame_estrellas', name: 'Stars', nameEs: 'Estrellas', description: 'Like stars in the heavens', descriptionEs: 'Como estrellas en el cielo', color: '#E6E6FA', price: 500, rarity: 'epic' },
  frame_pergamino: { id: 'frame_pergamino', name: 'Parchment', nameEs: 'Pergamino', description: 'Ancient wisdom scroll', descriptionEs: 'Pergamino de sabiduria antigua', color: '#D4B896', price: 300, rarity: 'common' },
  frame_fuego: { id: 'frame_fuego', name: 'Soft Fire', nameEs: 'Fuego Suave', description: 'Holy Spirit flame', descriptionEs: 'Llama del Espiritu Santo', color: '#FF6B35', price: 450, rarity: 'rare' },
  frame_cielo: { id: 'frame_cielo', name: 'Heaven', nameEs: 'Cielo', description: 'Gateway to eternity', descriptionEs: 'Puerta a la eternidad', color: '#87CEEB', price: 600, rarity: 'epic' },
  // Exclusive chest-only frames
  frame_chest_celestial: { id: 'frame_chest_celestial', name: 'Celestial', nameEs: 'Celestial', description: 'Frame of heavenly light — chest exclusive', descriptionEs: 'Marco de luz celestial — exclusivo del cofre', color: '#C9B8FF', chestOnly: true, rarity: 'epic' },
  frame_chest_profecia: { id: 'frame_chest_profecia', name: 'Prophecy', nameEs: 'Profecia', description: 'Ancient words fulfilled — chest exclusive', descriptionEs: 'Palabras antiguas cumplidas — exclusivo del cofre', color: '#8B4513', chestOnly: true, rarity: 'epic' },
  frame_chest_zafiro: { id: 'frame_chest_zafiro', name: 'Sapphire Throne', nameEs: 'Trono de Zafiro', description: 'Like the sapphire pavement of God — chest exclusive', descriptionEs: 'Como el pavimento de zafiro de Dios — exclusivo del cofre', color: '#1E3A5F', chestOnly: true, rarity: 'rare' },
  frame_chest_santo: { id: 'frame_chest_santo', name: 'Holy of Holies', nameEs: 'Santo de los Santos', description: 'Reserved for the consecrated — chest exclusive', descriptionEs: 'Reservado para los consagrados — exclusivo del cofre', color: '#F5D78E', chestOnly: true, rarity: 'epic' },
  frame_chest_nuevo_dia: { id: 'frame_chest_nuevo_dia', name: 'New Dawn', nameEs: 'Nuevo Dia', description: 'His mercies are new every morning — chest exclusive', descriptionEs: 'Sus misericordias son nuevas cada manana — exclusivo del cofre', color: '#FF9A5C', chestOnly: true, rarity: 'rare' },
};

// Spiritual Titles
export const SPIRITUAL_TITLES: Record<string, {
  id: string;
  name: string;
  nameEs: string;
  description: string;
  descriptionEs: string;
  price: number;
  rarity: string;
}> = {
  title_buscador: { id: 'title_buscador', name: 'Seeker of Light', nameEs: 'Buscador de Luz', description: 'One who seeks divine truth', descriptionEs: 'Quien busca la verdad divina', price: 200, rarity: 'common' },
  title_corazon: { id: 'title_corazon', name: 'Grateful Heart', nameEs: 'Corazon Agradecido', description: 'Living in thankfulness', descriptionEs: 'Viviendo en gratitud', price: 250, rarity: 'common' },
  title_caminando: { id: 'title_caminando', name: 'Walking in Faith', nameEs: 'Caminando en Fe', description: 'Steps guided by trust', descriptionEs: 'Pasos guiados por confianza', price: 300, rarity: 'common' },
  title_siervo: { id: 'title_siervo', name: 'Faithful Servant', nameEs: 'Siervo Fiel', description: 'Devoted to the mission', descriptionEs: 'Dedicado a la mision', price: 400, rarity: 'rare' },
  title_portador: { id: 'title_portador', name: 'Hope Bearer', nameEs: 'Portador de Esperanza', description: 'Bringing light to darkness', descriptionEs: 'Trayendo luz a la oscuridad', price: 350, rarity: 'rare' },
  title_amigo: { id: 'title_amigo', name: 'Friend of the Master', nameEs: 'Amigo del Maestro', description: 'Walking closely with Him', descriptionEs: 'Caminando cerca de El', price: 500, rarity: 'rare' },
  title_valiente: { id: 'title_valiente', name: 'Kingdom Warrior', nameEs: 'Valiente del Reino', description: 'Fighting the good fight', descriptionEs: 'Peleando la buena batalla', price: 600, rarity: 'epic' },
  title_sembrador: { id: 'title_sembrador', name: 'Peace Sower', nameEs: 'Sembrador de Paz', description: 'Planting seeds of harmony', descriptionEs: 'Sembrando semillas de armonia', price: 450, rarity: 'rare' },
  title_luz: { id: 'title_luz', name: 'Light in the Storm', nameEs: 'Luz en la Tormenta', description: 'Steady through trials', descriptionEs: 'Firme en las pruebas', price: 550, rarity: 'rare' },
  title_guardian: { id: 'title_guardian', name: 'Guardian of the Word', nameEs: 'Guardian de la Palabra', description: 'Keeper of sacred truth', descriptionEs: 'Protector de la verdad sagrada', price: 700, rarity: 'epic' },
  title_constructor: { id: 'title_constructor', name: 'Altar Builder', nameEs: 'Constructor de Altar', description: 'Creating sacred spaces', descriptionEs: 'Creando espacios sagrados', price: 500, rarity: 'rare' },
  title_peregrino: { id: 'title_peregrino', name: 'Pilgrim of Grace', nameEs: 'Peregrino de Gracia', description: 'Journey of faith', descriptionEs: 'Viaje de fe', price: 400, rarity: 'rare' },
};

// Rarity colors for UI
export const RARITY_COLORS = {
  common: '#9CA3AF',
  rare: '#3B82F6',
  epic: '#A855F7',
} as const;

// Rarity gradient backgrounds for premium card styling
export const RARITY_GRADIENTS = {
  common: ['#F3F4F6', '#E5E7EB'],
  rare: ['#EFF6FF', '#DBEAFE'],
  epic: ['#FAF5FF', '#F3E8FF'],
} as const;

// Item Collections - group related items for completion bonuses
export const ITEM_COLLECTIONS: Record<string, {
  id: string;
  name: string;
  nameEs: string;
  description: string;
  descriptionEs: string;
  icon: string;
  items: string[];
  rewardPoints: number;
  isV2?: boolean;
}> = {
  collection_simbolos_fe: {
    id: 'collection_simbolos_fe',
    name: 'Symbols of Faith',
    nameEs: 'Simbolos de Fe',
    description: 'Sacred symbols representing faith',
    descriptionEs: 'Simbolos sagrados de la fe',
    icon: '✝️',
    items: ['avatar_dove', 'avatar_cross', 'avatar_candle', 'avatar_crown'],
    rewardPoints: 200,
  },
  collection_naturaleza: {
    id: 'collection_naturaleza',
    name: 'Biblical Nature',
    nameEs: 'Naturaleza Biblica',
    description: 'Nature symbols from Scripture',
    descriptionEs: 'Simbolos de la naturaleza en las Escrituras',
    icon: '🌿',
    items: ['avatar_olive', 'avatar_fish', 'avatar_lamb', 'avatar_rainbow'],
    rewardPoints: 250,
  },
  collection_marcos_luz: {
    id: 'collection_marcos_luz',
    name: 'Frames of Light',
    nameEs: 'Marcos de Luz',
    description: 'Radiant frame collection',
    descriptionEs: 'Coleccion de marcos radiantes',
    icon: '✨',
    items: ['frame_dorado', 'frame_luz', 'frame_estrellas', 'frame_cielo'],
    rewardPoints: 300,
  },
  collection_titulos_servicio: {
    id: 'collection_titulos_servicio',
    name: 'Titles of Service',
    nameEs: 'Titulos de Servicio',
    description: 'Titles for faithful servants',
    descriptionEs: 'Titulos para siervos fieles',
    icon: '👑',
    items: ['title_siervo', 'title_portador', 'title_sembrador', 'title_guardian'],
    rewardPoints: 350,
  },
  // ============================================
  // V2 COLLECTIONS - Premium Avatar Collections
  // ============================================
  collection_v2_simbolos_fe: {
    id: 'collection_v2_simbolos_fe',
    name: 'Symbols of Faith V2',
    nameEs: 'Simbolos de Fe V2',
    description: 'Premium illustrated faith symbols',
    descriptionEs: 'Simbolos de fe ilustrados premium',
    icon: '✝️',
    items: ['avatar_v2_paloma_paz', 'avatar_v2_cruz_radiante', 'avatar_v2_lampara_aceite', 'avatar_v2_corona_vida', 'avatar_v2_biblia_abierta', 'avatar_v2_caliz', 'avatar_v2_ancla_esperanza', 'avatar_v2_pan_uvas'],
    rewardPoints: 500,
    isV2: true,
  },
  collection_v2_naturaleza: {
    id: 'collection_v2_naturaleza',
    name: 'Biblical Nature V2',
    nameEs: 'Naturaleza Biblica V2',
    description: 'Premium nature-inspired avatars',
    descriptionEs: 'Avatares premium inspirados en la naturaleza',
    icon: '🌿',
    items: ['avatar_v2_rama_olivo', 'avatar_v2_pez_ichthys', 'avatar_v2_cordero', 'avatar_v2_leon', 'avatar_v2_semilla_mostaza', 'avatar_v2_vid_racimos'],
    rewardPoints: 600,
    isV2: true,
  },
  collection_v2_virtudes: {
    id: 'collection_v2_virtudes',
    name: 'Virtues Collection',
    nameEs: 'Coleccion de Virtudes',
    description: 'Spiritual virtues as avatars',
    descriptionEs: 'Virtudes espirituales como avatares',
    icon: '💖',
    items: ['avatar_v2_gratitud', 'avatar_v2_fe', 'avatar_v2_amor', 'avatar_v2_paz', 'avatar_v2_gozo', 'avatar_v2_valentia'],
    rewardPoints: 550,
    isV2: true,
  },
  collection_v2_kids: {
    id: 'collection_v2_kids',
    name: 'Kids Friendly',
    nameEs: 'Infantil Amigable',
    description: 'Cute avatars for young hearts',
    descriptionEs: 'Avatares lindos para corazones jovenes',
    icon: '🌟',
    items: ['avatar_v2_estrellita', 'avatar_v2_arcoiris', 'avatar_v2_nube', 'avatar_v2_angelito'],
    rewardPoints: 300,
    isV2: true,
  },
};

// Store Bundles - discounted item packages
export const STORE_BUNDLES: Record<string, {
  id: string;
  name: string;
  nameEs: string;
  description: string;
  descriptionEs: string;
  items: string[];
  originalPrice: number;
  bundlePrice: number;
  rarity: string;
  isV2?: boolean;
}> = {
  bundle_gratitud: {
    id: 'bundle_gratitud',
    name: 'Gratitude Kit',
    nameEs: 'Kit Gratitud',
    description: 'Start your journey with thankfulness',
    descriptionEs: 'Comienza tu viaje con gratitud',
    items: ['theme_bosque', 'frame_verde', 'title_corazon'],
    originalPrice: 800,
    bundlePrice: 550,
    rarity: 'rare',
  },
  bundle_luz_divina: {
    id: 'bundle_luz_divina',
    name: 'Divine Light Bundle',
    nameEs: 'Paquete Luz Divina',
    description: 'Illuminate your spiritual path',
    descriptionEs: 'Ilumina tu camino espiritual',
    items: ['theme_noche_paz', 'frame_luz', 'title_buscador'],
    originalPrice: 950,
    bundlePrice: 650,
    rarity: 'rare',
  },
  bundle_peregrino: {
    id: 'bundle_peregrino',
    name: 'Pilgrim Collection',
    nameEs: 'Coleccion Peregrino',
    description: 'For those walking in faith',
    descriptionEs: 'Para quienes caminan en fe',
    items: ['theme_desierto', 'frame_pergamino', 'title_peregrino', 'avatar_lamb'],
    originalPrice: 1450,
    bundlePrice: 950,
    rarity: 'epic',
  },
  // ============================================
  // V2 BUNDLES - Premium Packages
  // ============================================
  bundle_v2_gratitud: {
    id: 'bundle_v2_gratitud',
    name: 'Gratitude V2 Kit',
    nameEs: 'Kit Gratitud V2',
    description: 'Premium gratitude collection with V2 items',
    descriptionEs: 'Coleccion premium de gratitud con items V2',
    items: ['theme_jardin_gracia', 'avatar_v2_gratitud', 'frame_dorado', 'title_corazon'],
    originalPrice: 1350,
    bundlePrice: 950,
    rarity: 'rare',
    isV2: true,
  },
  bundle_v2_paz: {
    id: 'bundle_v2_paz',
    name: 'Peace V2 Kit',
    nameEs: 'Kit Paz V2',
    description: 'Serenity and peace themed bundle',
    descriptionEs: 'Paquete tematico de serenidad y paz',
    items: ['theme_noche_profunda', 'avatar_v2_paloma_paz', 'avatar_v2_paz', 'title_sembrador'],
    originalPrice: 1950,
    bundlePrice: 1350,
    rarity: 'rare',
    isV2: true,
  },
  bundle_v2_fe: {
    id: 'bundle_v2_fe',
    name: 'Faith V2 Kit',
    nameEs: 'Kit Fe V2',
    description: 'Strengthen your faith with premium items',
    descriptionEs: 'Fortalece tu fe con items premium',
    items: ['theme_cielo_gloria', 'avatar_v2_fe', 'avatar_v2_cruz_radiante', 'frame_cielo', 'title_valiente'],
    originalPrice: 2330,
    bundlePrice: 1600,
    rarity: 'epic',
    isV2: true,
  },
  bundle_v2_promesa: {
    id: 'bundle_v2_promesa',
    name: 'Promise V2 Kit',
    nameEs: 'Kit Promesa V2',
    description: 'Divine promises collection',
    descriptionEs: 'Coleccion de promesas divinas',
    items: ['theme_promesa_violeta', 'avatar_v2_arcoiris', 'avatar_v2_ancla_esperanza', 'title_portador'],
    originalPrice: 1580,
    bundlePrice: 1100,
    rarity: 'rare',
    isV2: true,
  },
  bundle_v2_infantil: {
    id: 'bundle_v2_infantil',
    name: 'Kids Starter Kit',
    nameEs: 'Kit Infantil',
    description: 'Cute collection for young believers',
    descriptionEs: 'Coleccion linda para jovenes creyentes',
    items: ['avatar_v2_estrellita', 'avatar_v2_arcoiris', 'avatar_v2_nube', 'avatar_v2_angelito'],
    originalPrice: 1440,
    bundlePrice: 900,
    rarity: 'rare',
    isV2: true,
  },
  bundle_v2_naturaleza: {
    id: 'bundle_v2_naturaleza',
    name: 'Nature V2 Bundle',
    nameEs: 'Paquete Naturaleza V2',
    description: 'Biblical nature premium collection',
    descriptionEs: 'Coleccion premium de naturaleza biblica',
    items: ['theme_bosque_sereno', 'avatar_v2_rama_olivo', 'avatar_v2_vid_racimos', 'avatar_v2_semilla_mostaza', 'frame_corona'],
    originalPrice: 1720,
    bundlePrice: 1200,
    rarity: 'epic',
    isV2: true,
  },
};

// Weekly Chest rewards configuration
export const WEEKLY_CHEST_CONFIG = {
  possibleRewards: [
    { type: 'points', value: 100, weight: 30, rarity: 'common' },
    { type: 'points', value: 200, weight: 20, rarity: 'rare' },
    { type: 'points', value: 350, weight: 10, rarity: 'epic' },
    { type: 'item', itemId: 'avatar_fish', weight: 10, rarity: 'common' },
    { type: 'item', itemId: 'frame_plata', weight: 6, rarity: 'common' },
    { type: 'item', itemId: 'title_buscador', weight: 4, rarity: 'common' },
    // Exclusive chest-only items
    { type: 'item', itemId: 'avatar_chest_serafin', weight: 8, rarity: 'epic' },
    { type: 'item', itemId: 'avatar_chest_zarza', weight: 6, rarity: 'epic' },
    { type: 'item', itemId: 'avatar_chest_mana', weight: 6, rarity: 'rare' },
    { type: 'item', itemId: 'avatar_chest_trompeta', weight: 5, rarity: 'epic' },
    { type: 'item', itemId: 'avatar_chest_palacio', weight: 5, rarity: 'epic' },
    { type: 'item', itemId: 'frame_chest_celestial', weight: 6, rarity: 'epic' },
    { type: 'item', itemId: 'frame_chest_profecia', weight: 5, rarity: 'epic' },
    { type: 'item', itemId: 'frame_chest_zafiro', weight: 5, rarity: 'rare' },
    { type: 'item', itemId: 'frame_chest_santo', weight: 4, rarity: 'epic' },
    { type: 'item', itemId: 'frame_chest_nuevo_dia', weight: 4, rarity: 'rare' },
    { type: 'item', itemId: 'title_chest_ungido', weight: 5, rarity: 'epic' },
    { type: 'item', itemId: 'title_chest_columna', weight: 4, rarity: 'epic' },
    { type: 'item', itemId: 'title_chest_profeta', weight: 4, rarity: 'epic' },
    { type: 'item', itemId: 'title_chest_escogido', weight: 6, rarity: 'rare' },
    { type: 'item', itemId: 'title_chest_intercesor', weight: 5, rarity: 'rare' },
    { type: 'item', itemId: 'theme_chest_gloria', weight: 4, rarity: 'epic' },
    { type: 'item', itemId: 'theme_chest_desierto', weight: 5, rarity: 'rare' },
    { type: 'item', itemId: 'theme_chest_trono', weight: 3, rarity: 'epic' },
    { type: 'item', itemId: 'theme_chest_lluvia', weight: 5, rarity: 'rare' },
    { type: 'item', itemId: 'theme_chest_mar_rojo', weight: 4, rarity: 'epic' },
  ],
} as const;

// Prayer Request Categories
export const PRAYER_CATEGORIES = [
  { key: 'work', labelEn: 'Work / Provision', labelEs: 'Trabajo / Provisión', icon: 'Briefcase' },
  { key: 'health', labelEn: 'Health', labelEs: 'Salud', icon: 'Heart' },
  { key: 'family', labelEn: 'Family', labelEs: 'Familia', icon: 'Users' },
  { key: 'peace', labelEn: 'Peace / Anxiety', labelEs: 'Paz / Ansiedad', icon: 'Cloud' },
  { key: 'wisdom', labelEn: 'Wisdom / Direction', labelEs: 'Sabiduría / Dirección', icon: 'Compass' },
  { key: 'studies', labelEn: 'Studies', labelEs: 'Estudios', icon: 'BookOpen' },
  { key: 'restoration', labelEn: 'Restoration', labelEs: 'Restauración', icon: 'RefreshCw' },
  { key: 'gratitude', labelEn: 'Gratitude', labelEs: 'Gratitud', icon: 'Sparkles' },
  { key: 'salvation', labelEn: 'Salvation (for someone)', labelEs: 'Salvación (por alguien)', icon: 'HandHeart' },
  { key: 'strength', labelEn: 'Strength', labelEs: 'Fortaleza', icon: 'Shield' },
] as const;

export type PrayerCategoryKey = typeof PRAYER_CATEGORIES[number]['key'];

export const TRANSLATIONS = {
  en: {
    // General
    app_name: 'Daily Light',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    done: 'Done',
    back: 'Back',

    // Tabs
    tab_home: 'Today',
    tab_library: 'Library',
    tab_store: 'Customize',
    tab_community: 'Community',
    tab_settings: 'Settings',

    // Community
    community_title: 'Community',
    community_subtitle: 'We walk together',
    community_empty: 'No community members yet. Be the first to join!',
    community_you: 'You',
    community_devotionals: 'Devotionals',
    community_streak: 'Streak',
    community_opt_in: 'Show me in Community',
    community_opt_in_desc: 'Allow others to see your progress',
    community_walking_together: 'Walking together in faith',
    community_god_works: 'God works in His people',

    // Onboarding
    welcome: 'Welcome to Daily Light',
    welcome_subtitle: 'Your daily companion for faith, hope, and love',
    choose_nickname: 'Choose Your Nickname',
    nickname_placeholder: 'Enter a unique nickname',
    nickname_taken: 'This nickname is already taken',
    nickname_invalid: 'Nickname must be 3-15 characters',
    choose_avatar: 'Choose Your Avatar',
    get_started: 'Get Started',

    // Home
    todays_devotional: "Today's Devotional",
    bible_verse: 'Bible Verse',
    reflection: 'Reflection',
    story: 'Story',
    biblical_character: 'Biblical Character',
    application: 'Apply It',
    prayer: 'Prayer',
    mark_complete: 'Mark as Complete',
    completed: 'Completed',
    time_remaining: 'Read for {time} more',
    scroll_to_complete: 'Scroll to bottom to complete',

    // TTS
    play: 'Play',
    pause: 'Pause',
    stop: 'Stop',
    tts_speed: 'Reading Speed',
    tts_voice: 'Voice',

    // Music
    background_music: 'Background Music',
    volume: 'Volume',

    // Library
    library: 'Library',
    all_devotionals: 'All',
    favorites: 'Favorites',
    no_favorites: 'No favorites yet',
    search_placeholder: 'Search devotionals...',
    filter_category: 'Category',
    all_categories: 'All Categories',
    no_results: 'No results found',

    // Store
    store: 'Store',
    points: 'Points',
    purchase: 'Purchase',
    purchased: 'Owned',
    not_enough_points: 'Not enough points',
    purchase_success: 'Purchase successful!',

    // Settings
    settings: 'Settings',
    theme: 'Theme',
    language: 'Language',
    notifications: 'Notifications',
    streak_reminders: 'Streak Reminders',
    music_settings: 'Music',
    tts_settings: 'Text to Speech',

    // Stats
    stats: 'Your Journey',
    current_streak: 'Current Streak',
    best_streak: 'Best Streak',
    total_completed: 'Devotionals Read',
    total_time: 'Time in Prayer',
    days: 'days',
    hours: 'hours',
    minutes: 'min',

    // Gamification
    share_devotional: 'Share',
    prayer_confirm: 'I prayed today',
    points_earned: '+{points} points',
    daily_limit_reached: 'Daily limit reached',
    weekly_challenges: 'Weekly Challenges',
    challenge_progress: '{current}/{goal}',
    claim_reward: 'Claim Reward',
    reward_claimed: 'Reward Claimed',
    themes: 'Themes',
    frames: 'Frames',
    music_tracks: 'Music',
    titles: 'Titles',
    equip: 'Equip',
    equipped: 'Equipped',
    preview: 'Preview',
    unlock: 'Unlock',
    profile: 'Profile',
    your_title: 'Your Title',
    no_title: 'No title selected',

    // Transfer Code
    account_transfer: 'Account Transfer',
    account_transfer_desc: 'Move your progress to another device',
    generate_code: 'Generate Transfer Code',
    enter_code: 'Enter Transfer Code',
    transfer_code: 'Transfer Code',
    code_expires_in: 'Code expires in {minutes} minutes',
    code_expired: 'Code expired',
    copy_code: 'Copy Code',
    code_copied: 'Code copied!',
    enter_code_placeholder: 'Enter 8-character code',
    restore: 'Restore',
    restoring: 'Restoring...',
    restore_success: 'Account restored successfully!',
    restore_success_desc: 'Your progress has been transferred to this device.',
    invalid_code: 'Invalid or expired code',
    transfer_warning: 'This code expires in 15 minutes. Enter it on your new device.',
    generating: 'Generating...',
    user_id: 'User ID',

    // Prayer Tab
    tab_prayer: 'Prayer',
    prayer_title: 'Prayer',
    prayer_subtitle: 'We lift up our community',
    prayer_my_request: 'My Request',
    prayer_select_category: 'Select a category',
    prayer_mode_daily: 'Today',
    prayer_mode_weekly: 'This Week',
    prayer_save: 'Save',
    prayer_current_request: 'Current request',
    prayer_expires: 'Expires',
    prayer_community_requests: 'Community Requests',
    prayer_community_empty: 'No prayer requests yet. Be the first!',
    prayer_summary: 'Summary',
    prayer_anonymous: 'A brother/sister',
    prayer_today_badge: 'Today',
    prayer_week_badge: 'Week',
    prayer_request_saved: 'Prayer request saved',
    prayer_already_submitted: 'Already submitted for this period',
    prayer_of_the_day: 'Prayer of the Day',
    prayer_of_the_day_empty: 'No prayer of the day yet',
    prayer_prayed_for_community: 'I prayed for the community',
    prayer_prayed_today: 'You already prayed today',
    prayer_display_opt_in: 'Show my nickname in prayers',
    prayer_display_opt_in_desc: 'If off, you appear as "A brother/sister"',
  },
  es: {
    // General
    app_name: 'Luz Diaria',
    loading: 'Cargando...',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    done: 'Listo',
    back: 'Volver',

    // Tabs
    tab_home: 'Hoy',
    tab_library: 'Biblioteca',
    tab_store: 'Personalizar',
    tab_community: 'Comunidad',
    tab_settings: 'Ajustes',

    // Community
    community_title: 'Comunidad',
    community_subtitle: 'Caminamos juntos',
    community_empty: 'Aun no hay usuarios en Comunidad. Se el primero en activarlo.',
    community_you: 'Tu',
    community_devotionals: 'Devocionales',
    community_streak: 'Racha',
    community_opt_in: 'Mostrarme en Comunidad',
    community_opt_in_desc: 'Permite que otros vean tu progreso',
    community_walking_together: 'Caminando juntos en fe',
    community_god_works: 'Dios obra en Su pueblo',

    // Onboarding
    welcome: 'Bienvenido a Luz Diaria',
    welcome_subtitle: 'Tu companero diario de fe, esperanza y amor',
    choose_nickname: 'Elige Tu Apodo',
    nickname_placeholder: 'Ingresa un apodo unico',
    nickname_taken: 'Este apodo ya esta en uso',
    nickname_invalid: 'El apodo debe tener 3-15 caracteres',
    choose_avatar: 'Elige Tu Avatar',
    get_started: 'Comenzar',

    // Home
    todays_devotional: 'Devocional de Hoy',
    bible_verse: 'Versiculo Biblico',
    reflection: 'Reflexion',
    story: 'Historia',
    biblical_character: 'Personaje Biblico',
    application: 'Aplicacion',
    prayer: 'Oracion',
    mark_complete: 'Marcar Completo',
    completed: 'Completado',
    time_remaining: 'Lee por {time} mas',
    scroll_to_complete: 'Desplazate hasta abajo para completar',

    // TTS
    play: 'Reproducir',
    pause: 'Pausar',
    stop: 'Detener',
    tts_speed: 'Velocidad de Lectura',
    tts_voice: 'Voz',

    // Music
    background_music: 'Musica de Fondo',
    volume: 'Volumen',

    // Library
    library: 'Biblioteca',
    all_devotionals: 'Todos',
    favorites: 'Favoritos',
    no_favorites: 'Sin favoritos aun',
    search_placeholder: 'Buscar devocionales...',
    filter_category: 'Categoria',
    all_categories: 'Todas las Categorias',
    no_results: 'Sin resultados',

    // Store
    store: 'Tienda',
    points: 'Puntos',
    purchase: 'Comprar',
    purchased: 'Adquirido',
    not_enough_points: 'Puntos insuficientes',
    purchase_success: 'Compra exitosa!',

    // Settings
    settings: 'Ajustes',
    theme: 'Tema',
    language: 'Idioma',
    notifications: 'Notificaciones',
    streak_reminders: 'Recordatorios de Racha',
    music_settings: 'Musica',
    tts_settings: 'Texto a Voz',

    // Stats
    stats: 'Tu Camino',
    current_streak: 'Racha Actual',
    best_streak: 'Mejor Racha',
    total_completed: 'Devocionales Leidos',
    total_time: 'Tiempo en Oracion',
    days: 'dias',
    hours: 'horas',
    minutes: 'min',

    // Gamification
    share_devotional: 'Compartir',
    prayer_confirm: 'Hoy hice mi oracion',
    points_earned: '+{points} puntos',
    daily_limit_reached: 'Limite diario alcanzado',
    weekly_challenges: 'Desafios Semanales',
    challenge_progress: '{current}/{goal}',
    claim_reward: 'Reclamar Premio',
    reward_claimed: 'Premio Reclamado',
    themes: 'Temas',
    frames: 'Marcos',
    music_tracks: 'Musica',
    titles: 'Titulos',
    equip: 'Equipar',
    equipped: 'Equipado',
    preview: 'Vista Previa',
    unlock: 'Desbloquear',
    profile: 'Perfil',
    your_title: 'Tu Titulo',
    no_title: 'Sin titulo seleccionado',

    // Transfer Code
    account_transfer: 'Transferir Cuenta',
    account_transfer_desc: 'Mueve tu progreso a otro dispositivo',
    generate_code: 'Generar Codigo de Transferencia',
    enter_code: 'Ingresar Codigo de Transferencia',
    transfer_code: 'Codigo de Transferencia',
    code_expires_in: 'El codigo expira en {minutes} minutos',
    code_expired: 'Codigo expirado',
    copy_code: 'Copiar Codigo',
    code_copied: 'Codigo copiado!',
    enter_code_placeholder: 'Ingresa codigo de 8 caracteres',
    restore: 'Restaurar',
    restoring: 'Restaurando...',
    restore_success: 'Cuenta restaurada exitosamente!',
    restore_success_desc: 'Tu progreso ha sido transferido a este dispositivo.',
    invalid_code: 'Codigo invalido o expirado',
    transfer_warning: 'Este codigo expira en 15 minutos. Ingresalo en tu nuevo dispositivo.',
    generating: 'Generando...',
    user_id: 'ID de Usuario',

    // Prayer Tab
    tab_prayer: 'Oración',
    prayer_title: 'Oración',
    prayer_subtitle: 'Elevamos a nuestra comunidad',
    prayer_my_request: 'Mi Petición',
    prayer_select_category: 'Selecciona una categoría',
    prayer_mode_daily: 'Hoy',
    prayer_mode_weekly: 'Esta Semana',
    prayer_save: 'Guardar',
    prayer_current_request: 'Petición actual',
    prayer_expires: 'Expira',
    prayer_community_requests: 'Peticiones de la Comunidad',
    prayer_community_empty: 'Aún no hay peticiones. ¡Sé el primero!',
    prayer_summary: 'Resumen',
    prayer_anonymous: 'Un hermano/a',
    prayer_today_badge: 'Hoy',
    prayer_week_badge: 'Semana',
    prayer_request_saved: 'Petición guardada',
    prayer_already_submitted: 'Ya enviaste para este período',
    prayer_of_the_day: 'Oración del Día',
    prayer_of_the_day_empty: 'Aún no hay oración del día',
    prayer_prayed_for_community: 'Oré por la comunidad',
    prayer_prayed_today: 'Ya oraste hoy',
    prayer_display_opt_in: 'Mostrar mi nombre en oraciones',
    prayer_display_opt_in_desc: 'Si está desactivado, aparecerás como "Un hermano/a"',
  },
} as const;
