// Duelo de Sabiduría — Bible Trivia Questions Dataset (~480 questions)

export type DuelCategory =
  | 'vida_jesus'
  | 'milagros'
  | 'profetas'
  | 'reyes'
  | 'personajes'
  | 'versiculos'
  | 'antiguo_testamento'
  | 'nuevo_testamento';

export interface DuelQuestion {
  id: string;
  category: DuelCategory;
  questionEs: string;
  options: [string, string, string, string]; // exactly 4 options
  correctIndex: 0 | 1 | 2 | 3; // index of the correct answer
}

export const DUEL_QUESTIONS: DuelQuestion[] = [

  // ─────────────────────────────────────────────────────────────────────────
  // VIDA DE JESÚS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'vj_001',
    category: 'vida_jesus',
    questionEs: '¿En qué ciudad nació Jesús?',
    options: ['Nazaret', 'Jerusalén', 'Belén', 'Jericó'],
    correctIndex: 2,
  },
  {
    id: 'vj_002',
    category: 'vida_jesus',
    questionEs: '¿Cuántos años tenía Jesús cuando comenzó su ministerio público?',
    options: ['25 años', '30 años', '33 años', '40 años'],
    correctIndex: 1,
  },
  {
    id: 'vj_003',
    category: 'vida_jesus',
    questionEs: '¿Quién bautizó a Jesús?',
    options: ['Pedro', 'Pablo', 'Juan el Bautista', 'Elías'],
    correctIndex: 2,
  },
  {
    id: 'vj_004',
    category: 'vida_jesus',
    questionEs: '¿En qué río fue bautizado Jesús?',
    options: ['Jordán', 'Nilo', 'Éufrates', 'Galilea'],
    correctIndex: 0,
  },
  {
    id: 'vj_005',
    category: 'vida_jesus',
    questionEs: '¿Cuántos días estuvo Jesús en el desierto siendo tentado?',
    options: ['20 días', '30 días', '40 días', '7 días'],
    correctIndex: 2,
  },
  {
    id: 'vj_006',
    category: 'vida_jesus',
    questionEs: '¿Cuántos apóstoles eligió Jesús?',
    options: ['7', '10', '12', '14'],
    correctIndex: 2,
  },
  {
    id: 'vj_007',
    category: 'vida_jesus',
    questionEs: '¿Quién traicionó a Jesús por 30 monedas de plata?',
    options: ['Pedro', 'Judas Iscariote', 'Tomás', 'Bartolomé'],
    correctIndex: 1,
  },
  {
    id: 'vj_008',
    category: 'vida_jesus',
    questionEs: '¿Cuál fue la primera señal que hizo Jesús según el Evangelio de Juan?',
    options: ['Resucitar a Lázaro', 'Curar a un ciego', 'Convertir el agua en vino', 'Caminar sobre el agua'],
    correctIndex: 2,
  },
  {
    id: 'vj_009',
    category: 'vida_jesus',
    questionEs: '¿Cómo se llamaba la madre de Jesús?',
    options: ['Marta', 'María', 'Ana', 'Rebeca'],
    correctIndex: 1,
  },
  {
    id: 'vj_010',
    category: 'vida_jesus',
    questionEs: '¿Cómo se llamaba el padre adoptivo de Jesús?',
    options: ['Zacarías', 'Simón', 'José', 'Joachín'],
    correctIndex: 2,
  },
  {
    id: 'vj_011',
    category: 'vida_jesus',
    questionEs: '¿En qué lugar fue crucificado Jesús?',
    options: ['Monte de los Olivos', 'Gólgota', 'Getsemaní', 'Calvario de Herodes'],
    correctIndex: 1,
  },
  {
    id: 'vj_012',
    category: 'vida_jesus',
    questionEs: '¿Cuántos días pasó Jesús en la tumba antes de resucitar?',
    options: ['1 día', '2 días', '3 días', '7 días'],
    correctIndex: 2,
  },
  {
    id: 'vj_013',
    category: 'vida_jesus',
    questionEs: '¿Quién era el gobernador romano que condenó a Jesús?',
    options: ['Herodes', 'César', 'Poncio Pilato', 'Nerón'],
    correctIndex: 2,
  },
  {
    id: 'vj_014',
    category: 'vida_jesus',
    questionEs: '¿Qué dijo Jesús en la cruz: "Padre, perdónalos porque no saben lo que hacen"?',
    options: ['Verdad', 'Nunca dijo eso', 'Solo en sueños', 'Lo dijo Pedro'],
    correctIndex: 0,
  },
  {
    id: 'vj_015',
    category: 'vida_jesus',
    questionEs: '¿Dónde oró Jesús la noche antes de ser arrestado?',
    options: ['Monte Sinaí', 'En el templo', 'Getsemaní', 'Monte Tabor'],
    correctIndex: 2,
  },
  {
    id: 'vj_016',
    category: 'vida_jesus',
    questionEs: '¿Cuántos días después de la resurrección ascendió Jesús al cielo?',
    options: ['3 días', '7 días', '40 días', '50 días'],
    correctIndex: 2,
  },
  {
    id: 'vj_017',
    category: 'vida_jesus',
    questionEs: '¿En qué pueblo de Galilea creció Jesús?',
    options: ['Capernaúm', 'Nazaret', 'Betania', 'Gadara'],
    correctIndex: 1,
  },
  {
    id: 'vj_018',
    category: 'vida_jesus',
    questionEs: '¿Quién fue el primer apóstol llamado por Jesús junto a su hermano?',
    options: ['Juan', 'Santiago', 'Pedro', 'Andrés'],
    correctIndex: 3,
  },
  {
    id: 'vj_019',
    category: 'vida_jesus',
    questionEs: '¿Cuántas veces negó Pedro conocer a Jesús?',
    options: ['Una vez', 'Dos veces', 'Tres veces', 'Cuatro veces'],
    correctIndex: 2,
  },
  {
    id: 'vj_020',
    category: 'vida_jesus',
    questionEs: '¿Qué profesión tenía Jesús antes de su ministerio?',
    options: ['Pescador', 'Sacerdote', 'Carpintero', 'Pastor'],
    correctIndex: 2,
  },
  {
    id: 'vj_021',
    category: 'vida_jesus',
    questionEs: '¿A qué ciudad entró Jesús montado en un burro el Domingo de Ramos?',
    options: ['Belén', 'Nazaret', 'Jericó', 'Jerusalén'],
    correctIndex: 3,
  },
  {
    id: 'vj_022',
    category: 'vida_jesus',
    questionEs: '¿Quién ayudó a Jesús a cargar la cruz?',
    options: ['Juan', 'Simón de Cirene', 'Nicodemo', 'José de Arimatea'],
    correctIndex: 1,
  },
  {
    id: 'vj_023',
    category: 'vida_jesus',
    questionEs: '¿En qué lago realizó Jesús la mayor parte de sus milagros de pesca?',
    options: ['Mar Muerto', 'Lago Tiberiades', 'Mar Mediterráneo', 'Lago Galilea'],
    correctIndex: 1,
  },
  {
    id: 'vj_024',
    category: 'vida_jesus',
    questionEs: '¿Qué hizo Jesús en el templo al ver a los mercaderes?',
    options: ['Oró por ellos', 'Los sanó', 'Los expulsó volcando sus mesas', 'Les predicó'],
    correctIndex: 2,
  },
  {
    id: 'vj_025',
    category: 'vida_jesus',
    questionEs: '¿Cuál fue la última comida que Jesús compartió con sus doce apóstoles?',
    options: ['El banquete de bodas', 'La cena de Pentecostés', 'La Última Cena', 'La cena en Betania'],
    correctIndex: 2,
  },
  {
    id: 'vj_026',
    category: 'vida_jesus',
    questionEs: '¿Cuándo nació Jesús, quiénes vinieron a adorarle guiados por una estrella?',
    options: ['Los pastores', 'Los magos del oriente', 'Los escribas', 'Los levitas'],
    correctIndex: 1,
  },
  {
    id: 'vj_027',
    category: 'vida_jesus',
    questionEs: '¿Qué ángel anunció a María que concebiría al Hijo de Dios?',
    options: ['Miguel', 'Rafael', 'Gabriel', 'Uriel'],
    correctIndex: 2,
  },
  {
    id: 'vj_028',
    category: 'vida_jesus',
    questionEs: '¿Qué sucedió cuando Jesús fue tentado y venció al diablo en el desierto?',
    options: ['Jesús ayunó otros 40 días', 'Ángeles vinieron a servirle', 'Regresó a Nazaret', 'El diablo lo dejó para siempre'],
    correctIndex: 1,
  },
  {
    id: 'vj_029',
    category: 'vida_jesus',
    questionEs: '¿En qué ciudad vivía Lázaro, a quien Jesús resucitó?',
    options: ['Betania', 'Nazaret', 'Capernaúm', 'Jericó'],
    correctIndex: 0,
  },
  {
    id: 'vj_030',
    category: 'vida_jesus',
    questionEs: '¿Cuál era la profesión de Mateo antes de seguir a Jesús?',
    options: ['Pescador', 'Cobrador de impuestos', 'Sacerdote', 'Carpintero'],
    correctIndex: 1,
  },
  {
    id: 'vj_031',
    category: 'vida_jesus',
    questionEs: '¿Quién recibió a Jesús en su casa en Jericó, siendo un cobrador de impuestos?',
    options: ['Mateo', 'Leví', 'Zaqueo', 'Nicodemo'],
    correctIndex: 2,
  },
  {
    id: 'vj_032',
    category: 'vida_jesus',
    questionEs: '¿Cuál fue la primera persona que vio a Jesús resucitado?',
    options: ['Pedro', 'Juan', 'María Magdalena', 'La Virgen María'],
    correctIndex: 2,
  },
  {
    id: 'vj_033',
    category: 'vida_jesus',
    questionEs: '¿Cuántas bienaventuranzas proclamó Jesús en el Sermón del Monte?',
    options: ['6', '7', '8', '10'],
    correctIndex: 2,
  },
  {
    id: 'vj_034',
    category: 'vida_jesus',
    questionEs: '¿Cuándo tenía 12 años, ¿dónde encontraron sus padres a Jesús?',
    options: ['En el río Jordán', 'En Nazaret', 'En el templo de Jerusalén', 'En casa de Zacarías'],
    correctIndex: 2,
  },
  {
    id: 'vj_035',
    category: 'vida_jesus',
    questionEs: '¿Qué título usó Jesús para referirse a sí mismo con más frecuencia?',
    options: ['Hijo de Dios', 'Mesías', 'Hijo del Hombre', 'Señor'],
    correctIndex: 2,
  },
  {
    id: 'vj_036',
    category: 'vida_jesus',
    questionEs: '¿Cuántos panes y peces tenía el niño que los ofreció para la multiplicación?',
    options: ['3 panes y 2 peces', '5 panes y 2 peces', '7 panes y 3 peces', '5 panes y 5 peces'],
    correctIndex: 1,
  },
  {
    id: 'vj_037',
    category: 'vida_jesus',
    questionEs: '¿En qué monte se transfiguró Jesús ante Pedro, Juan y Santiago?',
    options: ['Monte Sinaí', 'Monte Sión', 'Monte Tabor', 'Monte Carmelo'],
    correctIndex: 2,
  },
  {
    id: 'vj_038',
    category: 'vida_jesus',
    questionEs: '¿Qué símbolo institucuyó Jesús en la Última Cena?',
    options: ['El bautismo', 'La Eucaristía', 'La confesión', 'El ayuno'],
    correctIndex: 1,
  },
  {
    id: 'vj_039',
    category: 'vida_jesus',
    questionEs: '¿Cuántos apóstoles estuvieron presentes en la Transfiguración?',
    options: ['2', '3', '5', '12'],
    correctIndex: 1,
  },
  {
    id: 'vj_040',
    category: 'vida_jesus',
    questionEs: '¿Cuál era el nombre hebreo de Jesús?',
    options: ['Yeshua', 'Yavé', 'Elohim', 'Adonai'],
    correctIndex: 0,
  },
  {
    id: 'vj_041',
    category: 'vida_jesus',
    questionEs: '¿Qué le dijo Jesús al ladrón crucificado junto a Él que le pidió ser recordado?',
    options: ['"Hoy estarás conmigo en el paraíso"', '"Eres perdonado de tus pecados"', '"Sigue creyendo"', '"Te veré en la resurrección"'],
    correctIndex: 0,
  },
  {
    id: 'vj_042',
    category: 'vida_jesus',
    questionEs: '¿Quién donó su tumba nueva para sepultar a Jesús?',
    options: ['Nicodemo', 'Juan el apóstol', 'José de Arimatea', 'Simón de Cirene'],
    correctIndex: 2,
  },
  {
    id: 'vj_043',
    category: 'vida_jesus',
    questionEs: '¿Qué dijo Jesús cuando fue tentado por el diablo con alimentos?',
    options: ['"No sólo de pan vive el hombre"', '"Aléjate de mí, Satanás"', '"El hombre no necesita comer"', '"Dios proveerá"'],
    correctIndex: 0,
  },
  {
    id: 'vj_044',
    category: 'vida_jesus',
    questionEs: '¿A quién le enseñó Jesús la "oración del Señor" (Padre Nuestro)?',
    options: ['A los fariseos', 'A sus discípulos', 'A la mujer samaritana', 'A Nicodemo'],
    correctIndex: 1,
  },
  {
    id: 'vj_045',
    category: 'vida_jesus',
    questionEs: '¿Qué mandamiento llamó Jesús "el más grande"?',
    options: ['No matarás', 'Honrar al padre y a la madre', 'Amar a Dios sobre todas las cosas', 'No robarás'],
    correctIndex: 2,
  },
  {
    id: 'vj_046',
    category: 'vida_jesus',
    questionEs: '¿Cuántos cestos de sobras sobraron en la multiplicación de los panes?',
    options: ['5', '7', '12', '14'],
    correctIndex: 2,
  },
  {
    id: 'vj_047',
    category: 'vida_jesus',
    questionEs: '¿Cuál de los discípulos negó conocer a Jesús tres veces antes del canto del gallo?',
    options: ['Judas', 'Andrés', 'Pedro', 'Felipe'],
    correctIndex: 2,
  },
  {
    id: 'vj_048',
    category: 'vida_jesus',
    questionEs: '¿En qué ciudad estaba la casa donde el Espíritu Santo descendió en Pentecostés?',
    options: ['Nazaret', 'Belén', 'Antioquía', 'Jerusalén'],
    correctIndex: 3,
  },
  {
    id: 'vj_049',
    category: 'vida_jesus',
    questionEs: '¿Cuál fue la pregunta que Jesús hizo a sus discípulos: "¿Quién dicen los hombres que soy yo"?',
    options: ['En la Última Cena', 'En Cesarea de Filipo', 'En el Monte Tabor', 'En el templo'],
    correctIndex: 1,
  },
  {
    id: 'vj_050',
    category: 'vida_jesus',
    questionEs: '¿Qué parabola contó Jesús sobre un hijo que pidió su herencia y la derrochó?',
    options: ['La parábola del sembrador', 'La parábola del hijo pródigo', 'La parábola de los talentos', 'La parábola del buen samaritano'],
    correctIndex: 1,
  },
  {
    id: 'vj_051',
    category: 'vida_jesus',
    questionEs: '¿Cómo llamó Jesús a sus discípulos cuando los envió de dos en dos?',
    options: ['Mensajeros', 'Embajadores', 'Apóstoles', 'Maestros'],
    correctIndex: 2,
  },
  {
    id: 'vj_052',
    category: 'vida_jesus',
    questionEs: '¿Con qué comparó Jesús el reino de los cielos en la parábola de la levadura?',
    options: ['Con un grano de mostaza', 'Con un tesoro escondido', 'Con la levadura en la harina', 'Con una perla preciosa'],
    correctIndex: 2,
  },
  {
    id: 'vj_053',
    category: 'vida_jesus',
    questionEs: '¿Quién lavó los pies de Jesús con perfume y los secó con su cabello?',
    options: ['María, madre de Jesús', 'Marta', 'María Magdalena', 'María de Betania'],
    correctIndex: 2,
  },
  {
    id: 'vj_054',
    category: 'vida_jesus',
    questionEs: '¿Cuánto tiempo estuvo Jesús en Egipto después del nacimiento?',
    options: ['No se especifica', '3 años', '40 días', '7 meses'],
    correctIndex: 0,
  },
  {
    id: 'vj_055',
    category: 'vida_jesus',
    questionEs: '¿Qué hizo Jesús cuando la multitud quiso hacerlo rey?',
    options: ['Aceptó el título', 'Se retiró solo a la montaña', 'Les predicó sobre el reino espiritual', 'Llamó a sus discípulos'],
    correctIndex: 1,
  },
  {
    id: 'vj_056',
    category: 'vida_jesus',
    questionEs: '¿Cuál discípulo se describió como "el discípulo amado" en el Evangelio de Juan?',
    options: ['Pedro', 'Andrés', 'Santiago', 'Juan'],
    correctIndex: 3,
  },
  {
    id: 'vj_057',
    category: 'vida_jesus',
    questionEs: '¿Qué ofreció Herodes Antipas darle a la hija de Herodías?',
    options: ['La mitad de su reino', 'Oro y plata', 'Hasta la mitad de su territorio', 'Un palacio'],
    correctIndex: 0,
  },
  {
    id: 'vj_058',
    category: 'vida_jesus',
    questionEs: '¿Qué frases dijo Jesús sobre la sal en el Sermón del Monte?',
    options: ['"Sed la sal de la tierra"', '"Usad la sal con sabiduría"', '"Evitad la sal y el pecado"', '"La sal es amarga como el pecado"'],
    correctIndex: 0,
  },
  {
    id: 'vj_059',
    category: 'vida_jesus',
    questionEs: '¿Cuántas veces le preguntó Jesús a Pedro si lo amaba, después de la resurrección?',
    options: ['Una vez', 'Dos veces', 'Tres veces', 'Siete veces'],
    correctIndex: 2,
  },
  {
    id: 'vj_060',
    category: 'vida_jesus',
    questionEs: '¿Quién pidió el cuerpo de Jesús a Pilato para darle sepultura?',
    options: ['Juan', 'Pedro', 'Nicodemo', 'José de Arimatea'],
    correctIndex: 3,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // MILAGROS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'mi_001',
    category: 'milagros',
    questionEs: '¿A cuántas personas alimentó Jesús con 5 panes y 2 peces?',
    options: ['2,000', '3,000', '5,000', '10,000'],
    correctIndex: 2,
  },
  {
    id: 'mi_002',
    category: 'milagros',
    questionEs: '¿A quién resucitó Jesús después de 4 días en el sepulcro?',
    options: ['Jairo', 'Lázaro', 'Tabita', 'Eutico'],
    correctIndex: 1,
  },
  {
    id: 'mi_003',
    category: 'milagros',
    questionEs: '¿Qué profeta dividió las aguas del Mar Rojo?',
    options: ['Elías', 'Josué', 'Moisés', 'Samuel'],
    correctIndex: 2,
  },
  {
    id: 'mi_004',
    category: 'milagros',
    questionEs: '¿Qué milagro hizo Elías en el monte Carmelo?',
    options: ['Dividió el río Jordán', 'Hizo descender fuego del cielo', 'Resucitó a un muerto', 'Multiplicó el aceite'],
    correctIndex: 1,
  },
  {
    id: 'mi_005',
    category: 'milagros',
    questionEs: '¿Quién caminó sobre el agua junto a Jesús?',
    options: ['Juan', 'Santiago', 'Andrés', 'Pedro'],
    correctIndex: 3,
  },
  {
    id: 'mi_006',
    category: 'milagros',
    questionEs: '¿Cuántos leprosos fueron sanados por Jesús de los cuales solo uno regresó a agradecer?',
    options: ['5', '7', '10', '12'],
    correctIndex: 2,
  },
  {
    id: 'mi_007',
    category: 'milagros',
    questionEs: '¿Cómo llamó Dios a Moisés desde la zarza ardiente?',
    options: ['Por nombre dos veces', 'Con un rayo de luz', 'A través de un ángel', 'En sueños'],
    correctIndex: 0,
  },
  {
    id: 'mi_008',
    category: 'milagros',
    questionEs: '¿Qué hizo Jesús para sanar al hombre ciego de nacimiento en Juan 9?',
    options: ['Le tocó los ojos', 'Hizo barro con tierra y saliva y lo puso en sus ojos', 'Oró y el hombre fue sanado', 'Le ordenó que se lavara en el estanque'],
    correctIndex: 1,
  },
  {
    id: 'mi_009',
    category: 'milagros',
    questionEs: '¿A quién resucitó Elías, el hijo de la viuda de Sarepta?',
    options: ['Al hijo de Sunem', 'Al hijo de la viuda', 'A Naamán', 'A Giezi'],
    correctIndex: 1,
  },
  {
    id: 'mi_010',
    category: 'milagros',
    questionEs: '¿En qué boda convirtió Jesús el agua en vino?',
    options: ['En Belén', 'En Caná de Galilea', 'En Nazaret', 'En Betania'],
    correctIndex: 1,
  },
  {
    id: 'mi_011',
    category: 'milagros',
    questionEs: '¿Cómo cruzaron los israelitas el río Jordán para entrar a Canaán?',
    options: ['En barcas', 'El río se dividió', 'A nado', 'Por un puente'],
    correctIndex: 1,
  },
  {
    id: 'mi_012',
    category: 'milagros',
    questionEs: '¿Qué milagro hizo Eliseo con las aguas de Jericó que eran malas?',
    options: ['Oró y el agua se limpió', 'Echó sal y las saneó', 'Dividió las aguas', 'Las convirtió en vino'],
    correctIndex: 1,
  },
  {
    id: 'mi_013',
    category: 'milagros',
    questionEs: '¿Qué sucedió cuando Josué mandó que el pueblo marchara alrededor de Jericó?',
    options: ['La ciudad se rindió', 'Los muros de la ciudad cayeron', 'Los enemigos huyeron', 'Dios envió fuego'],
    correctIndex: 1,
  },
  {
    id: 'mi_014',
    category: 'milagros',
    questionEs: '¿Cuántas jarras de agua convirtió Jesús en vino en Caná?',
    options: ['3', '4', '6', '12'],
    correctIndex: 2,
  },
  {
    id: 'mi_015',
    category: 'milagros',
    questionEs: '¿A qué hija de un líder de la sinagoga resucitó Jesús?',
    options: ['A la hija de Nicodemo', 'A la hija de Jairo', 'A la hija de Zacarías', 'A la hija de Herodes'],
    correctIndex: 1,
  },
  {
    id: 'mi_016',
    category: 'milagros',
    questionEs: '¿Qué órgano del criado del sumo sacerdote restauró Jesús en Getsemaní?',
    options: ['Un ojo', 'Una mano', 'Una oreja', 'Un pie'],
    correctIndex: 2,
  },
  {
    id: 'mi_017',
    category: 'milagros',
    questionEs: '¿Cómo se llamaba el ciego que Jesús sanó en Jericó?',
    options: ['Timeo', 'Bartimeo', 'Zaqueo', 'Simón'],
    correctIndex: 1,
  },
  {
    id: 'mi_018',
    category: 'milagros',
    questionEs: '¿Cuántos años llevaba paralítico el hombre que fue sanado en el estanque de Betesda?',
    options: ['18 años', '28 años', '38 años', '48 años'],
    correctIndex: 2,
  },
  {
    id: 'mi_019',
    category: 'milagros',
    questionEs: '¿Qué apóstol resucitó a Dorcas (Tabita)?',
    options: ['Juan', 'Pablo', 'Pedro', 'Felipe'],
    correctIndex: 2,
  },
  {
    id: 'mi_020',
    category: 'milagros',
    questionEs: '¿Cómo fue sanada la mujer que llevaba 12 años con hemorragias?',
    options: ['Jesús oró por ella', 'Ella tocó el manto de Jesús', 'Jesús la tocó', 'Ella se bañó en agua bendita'],
    correctIndex: 1,
  },
  {
    id: 'mi_021',
    category: 'milagros',
    questionEs: '¿Qué dijo Jesús para calmar la tormenta en el mar?',
    options: ['"Paz, estás en calma"', '"¡Calla, enmudece!"', '"Detente, viento"', '"En nombre de Dios, silencio"'],
    correctIndex: 1,
  },
  {
    id: 'mi_022',
    category: 'milagros',
    questionEs: '¿Cuántos panes y peces sobraron en la segunda multiplicación por Jesús (para 4,000)?',
    options: ['5 cestos', '7 cestos', '12 cestos', '14 cestos'],
    correctIndex: 1,
  },
  {
    id: 'mi_023',
    category: 'milagros',
    questionEs: '¿Qué profeta multiplicó el aceite de una viuda para saldar sus deudas?',
    options: ['Elías', 'Eliseo', 'Isaías', 'Samuel'],
    correctIndex: 1,
  },
  {
    id: 'mi_024',
    category: 'milagros',
    questionEs: '¿Quién fue mordido por una víbora y no sufrió daño alguno?',
    options: ['Pedro', 'Bernabé', 'Pablo', 'Timoteo'],
    correctIndex: 2,
  },
  {
    id: 'mi_025',
    category: 'milagros',
    questionEs: '¿Qué dijo Jesús para resucitar a Lázaro?',
    options: ['"Lázaro, sal fuera"', '"En nombre de Dios, levántate"', '"Lázaro, despierta"', '"Levántate y anda"'],
    correctIndex: 0,
  },
  {
    id: 'mi_026',
    category: 'milagros',
    questionEs: '¿Cuántas plagas mandó Dios sobre Egipto para liberar a Israel?',
    options: ['7', '8', '10', '12'],
    correctIndex: 2,
  },
  {
    id: 'mi_027',
    category: 'milagros',
    questionEs: '¿Qué le hizo Dios al sol durante la batalla de Josué en Gabaón?',
    options: ['Lo apagó', 'Detuvo el sol y la luna', 'Hizo dos soles', 'Oscureció el cielo'],
    correctIndex: 1,
  },
  {
    id: 'mi_028',
    category: 'milagros',
    questionEs: '¿Qué ángel hirió a 185,000 soldados asirios en una noche?',
    options: ['Gabriel', 'Rafael', 'El ángel del Señor', 'Miguel'],
    correctIndex: 2,
  },
  {
    id: 'mi_029',
    category: 'milagros',
    questionEs: '¿Cómo Moisés proveyó agua en el desierto cuando el pueblo tenía sed?',
    options: ['Oró y llovió', 'Golpeó una roca con su vara', 'Encontró un pozo', 'El maná se convirtió en agua'],
    correctIndex: 1,
  },
  {
    id: 'mi_030',
    category: 'milagros',
    questionEs: '¿Qué cayó del cielo para alimentar a los israelitas en el desierto?',
    options: ['Pan', 'Maná', 'Carne y maná', 'Frutas'],
    correctIndex: 1,
  },
  {
    id: 'mi_031',
    category: 'milagros',
    questionEs: '¿Qué le pasó a la mano de Moisés cuando la metió en su manto y la sacó?',
    options: ['Se paralizó', 'Se volvió leprosa y luego sanó', 'Brilló como el sol', 'Se volvió de oro'],
    correctIndex: 1,
  },
  {
    id: 'mi_032',
    category: 'milagros',
    questionEs: '¿Qué hizo Elías para resucitar al hijo de la sunamita?',
    options: ['Oró y lo tocó una vez', 'Se extendió sobre el niño tres veces', 'Sopló sobre su cara', 'Le ungió con aceite'],
    correctIndex: 1,
  },
  {
    id: 'mi_033',
    category: 'milagros',
    questionEs: '¿Cuántas personas alimentó Jesús en la segunda multiplicación?',
    options: ['3,000', '4,000', '5,000', '7,000'],
    correctIndex: 1,
  },
  {
    id: 'mi_034',
    category: 'milagros',
    questionEs: '¿Qué ocurrió en el cielo cuando Jesús fue bautizado?',
    options: ['Hubo truenos y relámpagos', 'El Espíritu Santo descendió como paloma y una voz habló', 'Los ángeles cantaron', 'Brilló una estrella'],
    correctIndex: 1,
  },
  {
    id: 'mi_035',
    category: 'milagros',
    questionEs: '¿Qué ángel liberó a Pedro de la prisión de Herodes?',
    options: ['Rafael', 'Gabriel', 'Miguel', 'El ángel del Señor'],
    correctIndex: 3,
  },
  {
    id: 'mi_036',
    category: 'milagros',
    questionEs: '¿Qué hizo el hacha que cayó al río Jordán cuando Eliseo lanzó un palo?',
    options: ['Se hundió más', 'Flotó', 'Se convirtió en pez', 'Saltó a la orilla'],
    correctIndex: 1,
  },
  {
    id: 'mi_037',
    category: 'milagros',
    questionEs: '¿Qué leprosidad fue curada gracias a Eliseo sumergiéndose siete veces en el Jordán?',
    options: ['La de Giezi', 'La de Naamán', 'La de los diez leprosos', 'La de Miriam'],
    correctIndex: 1,
  },
  {
    id: 'mi_038',
    category: 'milagros',
    questionEs: '¿Qué milagro ocurrió cuando los apóstoles oraron en Pentecostés?',
    options: ['Terremotos', 'El Espíritu Santo descendió como lenguas de fuego', 'Se multiplicaron los panes', 'Sanaron muchos enfermos'],
    correctIndex: 1,
  },
  {
    id: 'mi_039',
    category: 'milagros',
    questionEs: '¿Qué milagro hizo Pablo en Éfeso que llenó de asombro a todos?',
    options: ['Resucitó a un muerto', 'Sanó a un paralítico de nacimiento', 'Los pañuelos de su cuerpo sanaban enfermos', 'Habló en lenguas desconocidas'],
    correctIndex: 2,
  },
  {
    id: 'mi_040',
    category: 'milagros',
    questionEs: '¿Cuántos días estuvo Jonás en el vientre del gran pez antes de ser echado a tierra?',
    options: ['1 día', '2 días', '3 días', '7 días'],
    correctIndex: 2,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // PROFETAS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'pr_001',
    category: 'profetas',
    questionEs: '¿En qué libro bíblico se encuentra la frase "En el principio era el Verbo"?',
    options: ['Isaías', 'Génesis', 'Juan', 'Apocalipsis'],
    correctIndex: 2,
  },
  {
    id: 'pr_002',
    category: 'profetas',
    questionEs: '¿Qué profeta fue tragado por un pez grande?',
    options: ['Amós', 'Jonás', 'Nahúm', 'Habacuc'],
    correctIndex: 1,
  },
  {
    id: 'pr_003',
    category: 'profetas',
    questionEs: '¿Cuántos días estuvo Jonás en el vientre del gran pez?',
    options: ['1 día', '2 días', '3 días', '7 días'],
    correctIndex: 2,
  },
  {
    id: 'pr_004',
    category: 'profetas',
    questionEs: '¿Qué profeta anunció "una virgen concebirá y dará a luz un hijo"?',
    options: ['Jeremías', 'Ezequiel', 'Daniel', 'Isaías'],
    correctIndex: 3,
  },
  {
    id: 'pr_005',
    category: 'profetas',
    questionEs: '¿Qué profeta fue llevado al cielo en un carro de fuego?',
    options: ['Elías', 'Enoc', 'Eliseo', 'Ezequiel'],
    correctIndex: 0,
  },
  {
    id: 'pr_006',
    category: 'profetas',
    questionEs: '¿Qué profeta fue lanzado al foso de los leones?',
    options: ['Isaías', 'Jeremías', 'Daniel', 'Ezequiel'],
    correctIndex: 2,
  },
  {
    id: 'pr_007',
    category: 'profetas',
    questionEs: '¿Qué profeta llamó al pueblo de Israel "huesos secos" en una visión?',
    options: ['Isaías', 'Ezequiel', 'Jeremías', 'Zacarías'],
    correctIndex: 1,
  },
  {
    id: 'pr_008',
    category: 'profetas',
    questionEs: '¿A qué ciudad fue enviado Jonás a predicar?',
    options: ['Babilonia', 'Nínive', 'Tiro', 'Sidón'],
    correctIndex: 1,
  },
  {
    id: 'pr_009',
    category: 'profetas',
    questionEs: '¿Cuántos años profetizó Isaías, aproximadamente?',
    options: ['20 años', '40 años', '60 años', '80 años'],
    correctIndex: 2,
  },
  {
    id: 'pr_010',
    category: 'profetas',
    questionEs: '¿Quién fue el padre espiritual del profeta Eliseo?',
    options: ['Samuel', 'Elías', 'Moisés', 'Ezequiel'],
    correctIndex: 1,
  },
  {
    id: 'pr_011',
    category: 'profetas',
    questionEs: '¿Qué profeta lleva el libro más corto del Antiguo Testamento?',
    options: ['Abdías', 'Nahúm', 'Joel', 'Hageo'],
    correctIndex: 0,
  },
  {
    id: 'pr_012',
    category: 'profetas',
    questionEs: '¿Con qué animal compara Isaías al siervo sufriente de Dios?',
    options: ['Un cordero llevado al matadero', 'Un toro para el sacrificio', 'Una paloma herida', 'Un leon enjaulado'],
    correctIndex: 0,
  },
  {
    id: 'pr_013',
    category: 'profetas',
    questionEs: '¿Qué profeta se casó con una prostituta como señal para Israel?',
    options: ['Amós', 'Miqueas', 'Oseas', 'Joel'],
    correctIndex: 2,
  },
  {
    id: 'pr_014',
    category: 'profetas',
    questionEs: '¿Quién profetizó "derramaré mi Espíritu sobre toda carne"?',
    options: ['Isaías', 'Joel', 'Ezequiel', 'Zacarías'],
    correctIndex: 1,
  },
  {
    id: 'pr_015',
    category: 'profetas',
    questionEs: '¿Qué profeta fue conocido como el "profeta llorón"?',
    options: ['Isaías', 'Jeremías', 'Ezequiel', 'Oseas'],
    correctIndex: 1,
  },
  {
    id: 'pr_016',
    category: 'profetas',
    questionEs: '¿En qué libro de los profetas se habla del "Valle de los Huesos Secos"?',
    options: ['Isaías', 'Jeremías', 'Ezequiel', 'Daniel'],
    correctIndex: 2,
  },
  {
    id: 'pr_017',
    category: 'profetas',
    questionEs: '¿Cuántos reyes vio Isaías en sus visiones durante su ministerio?',
    options: ['2', '4', '6', '8'],
    correctIndex: 1,
  },
  {
    id: 'pr_018',
    category: 'profetas',
    questionEs: '¿Qué símbolo usó Dios para llamar a Jeremías como profeta desde antes de nacer?',
    options: ['Una zarza ardiente', '"Antes de formarte en el vientre te conocí"', 'Un ángel de luz', 'Un sueño'],
    correctIndex: 1,
  },
  {
    id: 'pr_019',
    category: 'profetas',
    questionEs: '¿Qué profeta anunció el nacimiento del Mesías en Belén de Judá?',
    options: ['Isaías', 'Ezequiel', 'Miqueas', 'Zacarías'],
    correctIndex: 2,
  },
  {
    id: 'pr_020',
    category: 'profetas',
    questionEs: '¿Cuántos capítulos tiene el libro de Isaías?',
    options: ['39', '52', '66', '73'],
    correctIndex: 2,
  },
  {
    id: 'pr_021',
    category: 'profetas',
    questionEs: '¿Con qué visión comenzó el ministerio profético de Isaías?',
    options: ['Un carro de fuego', 'El trono de Dios con serafines', 'Un valle de huesos', 'Una zarza ardiente'],
    correctIndex: 1,
  },
  {
    id: 'pr_022',
    category: 'profetas',
    questionEs: '¿Cuántos años estuvo Daniel en Babilonia antes de que cayera ese reino?',
    options: ['30 años', '40 años', '60 años', '70 años'],
    correctIndex: 3,
  },
  {
    id: 'pr_023',
    category: 'profetas',
    questionEs: '¿Qué profeta dijo "¿Cómo oiré si no me lo proclaman; y cómo proclamarán si no son enviados?"?',
    options: ['Isaías', 'Pablo', 'Elías', 'Jeremías'],
    correctIndex: 1,
  },
  {
    id: 'pr_024',
    category: 'profetas',
    questionEs: '¿Qué profeta interpretó la escritura en la pared para el rey Belsasar?',
    options: ['Jeremías', 'Ezequiel', 'Daniel', 'Isaías'],
    correctIndex: 2,
  },
  {
    id: 'pr_025',
    category: 'profetas',
    questionEs: '¿Qué profeta menor habló de la "Nueva Jerusalén" descrita con muros y puertas de piedras preciosas?',
    options: ['Ageo', 'Malaquías', 'Zacarías', 'Sofonías'],
    correctIndex: 2,
  },
  {
    id: 'pr_026',
    category: 'profetas',
    questionEs: '¿Cuál fue el mensaje central del profeta Amós?',
    options: ['El amor de Dios', 'La justicia social', 'La misericordia', 'El arrepentimiento'],
    correctIndex: 1,
  },
  {
    id: 'pr_027',
    category: 'profetas',
    questionEs: '¿A qué profeta se le llamó a comer un rollo de libro que era dulce como miel?',
    options: ['Jeremías', 'Isaías', 'Ezequiel', 'Juan'],
    correctIndex: 2,
  },
  {
    id: 'pr_028',
    category: 'profetas',
    questionEs: '¿Qué profeta anunció: "He aquí yo envío mi mensajero delante de tu faz"?',
    options: ['Elías', 'Joel', 'Malaquías', 'Isaías'],
    correctIndex: 2,
  },
  {
    id: 'pr_029',
    category: 'profetas',
    questionEs: '¿Qué profeta confrontó al rey David por su pecado con Betsabé?',
    options: ['Samuel', 'Gad', 'Natán', 'Aarón'],
    correctIndex: 2,
  },
  {
    id: 'pr_030',
    category: 'profetas',
    questionEs: '¿Qué profeta recibió visiones de cuatro bestias que simbolizaban reinos?',
    options: ['Isaías', 'Jeremías', 'Ezequiel', 'Daniel'],
    correctIndex: 3,
  },
  {
    id: 'pr_031',
    category: 'profetas',
    questionEs: '¿Con qué objeto visual demostró Jeremías la destrucción de Judá?',
    options: ['Un rollo', 'Una vasija de barro que rompió', 'Un hueso seco', 'Un estandarte rasgado'],
    correctIndex: 1,
  },
  {
    id: 'pr_032',
    category: 'profetas',
    questionEs: '¿Qué profeta fue rescatado de un cisterna donde fue arrojado?',
    options: ['Isaías', 'Jeremías', 'Amós', 'Oseas'],
    correctIndex: 1,
  },
  {
    id: 'pr_033',
    category: 'profetas',
    questionEs: '¿Quién profetizó que el Mesías entraría en Jerusalén montado en un asno?',
    options: ['Isaías', 'Miqueas', 'Zacarías', 'Malaquías'],
    correctIndex: 2,
  },
  {
    id: 'pr_034',
    category: 'profetas',
    questionEs: '¿Cuántos profetas mayores se reconocen en el Antiguo Testamento?',
    options: ['3', '4', '5', '6'],
    correctIndex: 1,
  },
  {
    id: 'pr_035',
    category: 'profetas',
    questionEs: '¿Qué profeta fue amigo de Eliseo y preguntó: "¿Hay aquí algún profeta del Señor"?',
    options: ['Josafat', 'Elías', 'Samuel', 'Miqueas ben Yimlá'],
    correctIndex: 3,
  },
  {
    id: 'pr_036',
    category: 'profetas',
    questionEs: '¿Qué profeta recibió la tarea de volver a ungir a un rey de Israel y también de Siria?',
    options: ['Samuel', 'Natán', 'Elías', 'Eliseo'],
    correctIndex: 2,
  },
  {
    id: 'pr_037',
    category: 'profetas',
    questionEs: '¿En qué profeta se encuentra la promesa de "un corazón nuevo y un espíritu nuevo"?',
    options: ['Isaías 40', 'Jeremías 31', 'Ezequiel 36', 'Daniel 9'],
    correctIndex: 2,
  },
  {
    id: 'pr_038',
    category: 'profetas',
    questionEs: '¿Cuántos años predijo Jeremías que duraría el cautiverio de Babilonia?',
    options: ['40 años', '50 años', '70 años', '100 años'],
    correctIndex: 2,
  },
  {
    id: 'pr_039',
    category: 'profetas',
    questionEs: '¿Qué profeta habló sobre "el cordero que quita el pecado del mundo"?',
    options: ['Isaías', 'Juan el Bautista', 'Jeremías', 'Elías'],
    correctIndex: 1,
  },
  {
    id: 'pr_040',
    category: 'profetas',
    questionEs: '¿Qué profeta fue el maestro y consejero del joven rey Josías?',
    options: ['Isaías', 'Jeremías', 'Jilquías', 'Hulda'],
    correctIndex: 3,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // REYES
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 're_001',
    category: 'reyes',
    questionEs: '¿Quién fue el primer rey de Israel?',
    options: ['David', 'Saúl', 'Salomón', 'Roboam'],
    correctIndex: 1,
  },
  {
    id: 're_002',
    category: 'reyes',
    questionEs: '¿Cuántos años reinó Salomón sobre Israel?',
    options: ['20 años', '30 años', '40 años', '50 años'],
    correctIndex: 2,
  },
  {
    id: 're_003',
    category: 'reyes',
    questionEs: '¿Quién construyó el primer templo de Jerusalén?',
    options: ['David', 'Salomón', 'Ezequías', 'Josías'],
    correctIndex: 1,
  },
  {
    id: 're_004',
    category: 'reyes',
    questionEs: '¿Con qué mató David a Goliat?',
    options: ['Una espada', 'Una lanza', 'Una honda y una piedra', 'Sus manos desnudas'],
    correctIndex: 2,
  },
  {
    id: 're_005',
    category: 'reyes',
    questionEs: '¿Qué don pidió Salomón a Dios?',
    options: ['Riquezas', 'Sabiduría', 'Larga vida', 'Victoria en la guerra'],
    correctIndex: 1,
  },
  {
    id: 're_006',
    category: 'reyes',
    questionEs: '¿Quién ungió a David como rey de Israel?',
    options: ['Elías', 'Moisés', 'Samuel', 'Natán'],
    correctIndex: 2,
  },
  {
    id: 're_007',
    category: 'reyes',
    questionEs: '¿Cuántos años reinó David sobre todo Israel?',
    options: ['30 años', '33 años', '40 años', '45 años'],
    correctIndex: 2,
  },
  {
    id: 're_008',
    category: 'reyes',
    questionEs: '¿Quién fue el hijo de David que lo traicionó y quiso arrebatarle el reino?',
    options: ['Amnón', 'Absalón', 'Adonías', 'Salomón'],
    correctIndex: 1,
  },
  {
    id: 're_009',
    category: 'reyes',
    questionEs: '¿Qué reina visitó a Salomón para probar su sabiduría?',
    options: ['La reina de Egipto', 'La reina de Saba', 'La reina de Tiro', 'La reina de Fenicia'],
    correctIndex: 1,
  },
  {
    id: 're_010',
    category: 'reyes',
    questionEs: '¿Quién fue el rey que dividió Israel en dos reinos al suceder a Salomón?',
    options: ['Jeroboam', 'Roboam', 'Acab', 'Josafat'],
    correctIndex: 1,
  },
  {
    id: 're_011',
    category: 'reyes',
    questionEs: '¿Qué rey malvado de Israel se casó con Jezabel y adoró a Baal?',
    options: ['Jeroboam', 'Baasa', 'Acab', 'Zimri'],
    correctIndex: 2,
  },
  {
    id: 're_012',
    category: 'reyes',
    questionEs: '¿Quién fue el rey de Judá que reformó el culto y encontró el libro de la ley?',
    options: ['Ezequías', 'Josafat', 'Josías', 'Asa'],
    correctIndex: 2,
  },
  {
    id: 're_013',
    category: 'reyes',
    questionEs: '¿Qué rey de Judá fue conocido por hacer túneles de agua en Jerusalén?',
    options: ['David', 'Salomón', 'Ezequías', 'Joás'],
    correctIndex: 2,
  },
  {
    id: 're_014',
    category: 'reyes',
    questionEs: '¿Cuántos años reinó Saúl antes de que David fuera ungido?',
    options: ['10 años', '20 años', '40 años', '50 años'],
    correctIndex: 2,
  },
  {
    id: 're_015',
    category: 'reyes',
    questionEs: '¿Qué rey de Israel construyó la ciudad de Samaria como su capital?',
    options: ['Jeroboam', 'Omri', 'Acab', 'Jehú'],
    correctIndex: 1,
  },
  {
    id: 're_016',
    category: 'reyes',
    questionEs: '¿Cuántos hijos tenía David que aspiraban al trono?',
    options: ['2', '3', '4', 'Varios pero los más conocidos son Absalón y Adonías'],
    correctIndex: 3,
  },
  {
    id: 're_017',
    category: 'reyes',
    questionEs: '¿Qué rey de Babilonia destruyó el templo de Salomón?',
    options: ['Ciro', 'Darío', 'Nabucodonosor', 'Belsasar'],
    correctIndex: 2,
  },
  {
    id: 're_018',
    category: 'reyes',
    questionEs: '¿Quién fue el primer rey de las diez tribus del norte (Israel) después de la división?',
    options: ['Roboam', 'Jeroboam', 'Baasa', 'Omri'],
    correctIndex: 1,
  },
  {
    id: 're_019',
    category: 'reyes',
    questionEs: '¿Con quién se enfrentó David antes de ser rey, siendo pastorcillo?',
    options: ['Con Saúl', 'Con Goliat', 'Con un oso y un león primero', 'Con los filisteos'],
    correctIndex: 2,
  },
  {
    id: 're_020',
    category: 'reyes',
    questionEs: '¿Cuántos años reinó Salomón en Jerusalén sobre todo Israel?',
    options: ['20 años', '30 años', '40 años', '50 años'],
    correctIndex: 2,
  },
  {
    id: 're_021',
    category: 'reyes',
    questionEs: '¿Cuál fue el pecado de Saúl que hizo que Dios lo rechazara como rey?',
    options: ['Mató a sacerdotes', 'No destruyó completamente a los amalecitas como Dios ordenó', 'Adoró ídolos', 'Robó del tesoro del templo'],
    correctIndex: 1,
  },
  {
    id: 're_022',
    category: 'reyes',
    questionEs: '¿Qué rey persa permitió a los judíos regresar de Babilonia?',
    options: ['Darío', 'Jerjes', 'Ciro el Grande', 'Artajerjes'],
    correctIndex: 2,
  },
  {
    id: 're_023',
    category: 'reyes',
    questionEs: '¿Qué hizo Salomón que provocó la división del reino después de su muerte?',
    options: ['Subió los impuestos', 'Se alejó de Dios y adoró dioses extranjeros', 'Mató a sus herederos', 'Vendió tierras de Israel'],
    correctIndex: 1,
  },
  {
    id: 're_024',
    category: 'reyes',
    questionEs: '¿Qué rey de Judá extendió su vida 15 años más por oración?',
    options: ['Josafat', 'Ezequías', 'Josías', 'Asa'],
    correctIndex: 1,
  },
  {
    id: 're_025',
    category: 'reyes',
    questionEs: '¿Cuál fue el nombre del rey que hizo matar a los niños de Belén para eliminar a Jesús?',
    options: ['Herodes Antipas', 'Herodes el Grande', 'Poncio Pilato', 'Arquelao'],
    correctIndex: 1,
  },
  {
    id: 're_026',
    category: 'reyes',
    questionEs: '¿Qué rey de Israel fue conocido por su extrema maldad y mató a todos los profetas de Dios?',
    options: ['Jeroboam', 'Omri', 'Acab', 'Jehú'],
    correctIndex: 2,
  },
  {
    id: 're_027',
    category: 'reyes',
    questionEs: '¿Quién fue el único rey que reinó en Jerusalén mientras la ciudad fue tomada por David?',
    options: ['Melquisedec', 'Adonisedec', 'Adoni-Bezec', 'Ninguno, David la tomó de los jebuseos'],
    correctIndex: 3,
  },
  {
    id: 're_028',
    category: 'reyes',
    questionEs: '¿A quién le robó David su esposa Betsabé?',
    options: ['Absalón', 'Urías el hitita', 'Jonatán', 'Nabal'],
    correctIndex: 1,
  },
  {
    id: 're_029',
    category: 'reyes',
    questionEs: '¿Cuántos años reinó el rey Jeroboam sobre Israel (el del norte)?',
    options: ['10 años', '22 años', '28 años', '40 años'],
    correctIndex: 1,
  },
  {
    id: 're_030',
    category: 'reyes',
    questionEs: '¿A qué tribu pertenecía el rey David?',
    options: ['Benjamín', 'Leví', 'Judá', 'Efraín'],
    correctIndex: 2,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // PERSONAJES BÍBLICOS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'pe_001',
    category: 'personajes',
    questionEs: '¿Quién fue la primera mujer según la Biblia?',
    options: ['Sara', 'Rebeca', 'Eva', 'Raquel'],
    correctIndex: 2,
  },
  {
    id: 'pe_002',
    category: 'personajes',
    questionEs: '¿Cuántos años vivió Matusalén, el hombre más longevo de la Biblia?',
    options: ['800 años', '899 años', '969 años', '1000 años'],
    correctIndex: 2,
  },
  {
    id: 'pe_003',
    category: 'personajes',
    questionEs: '¿Quién fue el padre de Abraham?',
    options: ['Noé', 'Sem', 'Taré', 'Nacor'],
    correctIndex: 2,
  },
  {
    id: 'pe_004',
    category: 'personajes',
    questionEs: '¿Qué nombre le dio Dios a Abram?',
    options: ['Israel', 'Abraham', 'Isaac', 'Jacob'],
    correctIndex: 1,
  },
  {
    id: 'pe_005',
    category: 'personajes',
    questionEs: '¿Cuántos hijos tuvo Jacob, que forman las tribus de Israel?',
    options: ['10', '11', '12', '13'],
    correctIndex: 2,
  },
  {
    id: 'pe_006',
    category: 'personajes',
    questionEs: '¿Quién interpretó los sueños del faraón en Egipto?',
    options: ['Moisés', 'José', 'Daniel', 'Samuel'],
    correctIndex: 1,
  },
  {
    id: 'pe_007',
    category: 'personajes',
    questionEs: '¿Quién fue la suegra de Rut?',
    options: ['Noemí', 'Débora', 'Ana', 'Ester'],
    correctIndex: 0,
  },
  {
    id: 'pe_008',
    category: 'personajes',
    questionEs: '¿En qué río fue encontrado Moisés de bebé?',
    options: ['Jordán', 'Éufrates', 'Nilo', 'Tigris'],
    correctIndex: 2,
  },
  {
    id: 'pe_009',
    category: 'personajes',
    questionEs: '¿Quién fue el primer hijo de Adán y Eva?',
    options: ['Abel', 'Set', 'Caín', 'Enoc'],
    correctIndex: 2,
  },
  {
    id: 'pe_010',
    category: 'personajes',
    questionEs: '¿Cuántos hijos tuvo Noé?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1,
  },
  {
    id: 'pe_011',
    category: 'personajes',
    questionEs: '¿A quién vendieron como esclavo los hermanos de José?',
    options: ['A los egipcios', 'A los ismaelitas', 'A los filisteos', 'A los amalecitas'],
    correctIndex: 1,
  },
  {
    id: 'pe_012',
    category: 'personajes',
    questionEs: '¿Quién fue la madre de Samuel el profeta?',
    options: ['Débora', 'Ana', 'Raquel', 'Rut'],
    correctIndex: 1,
  },
  {
    id: 'pe_013',
    category: 'personajes',
    questionEs: '¿Quién fue el primer mártir cristiano mencionado en Hechos?',
    options: ['Pedro', 'Santiago', 'Esteban', 'Juan'],
    correctIndex: 2,
  },
  {
    id: 'pe_014',
    category: 'personajes',
    questionEs: '¿Cuántos libros escribió el apóstol Pablo en el Nuevo Testamento?',
    options: ['10', '13', '14', '7'],
    correctIndex: 1,
  },
  {
    id: 'pe_015',
    category: 'personajes',
    questionEs: '¿Cómo se llamaba el compañero de misión de Pablo que era médico?',
    options: ['Bernabé', 'Timoteo', 'Lucas', 'Tito'],
    correctIndex: 2,
  },
  {
    id: 'pe_016',
    category: 'personajes',
    questionEs: '¿Quién fue la única jueza mencionada en el Antiguo Testamento?',
    options: ['Rut', 'Ester', 'Débora', 'Miriam'],
    correctIndex: 2,
  },
  {
    id: 'pe_017',
    category: 'personajes',
    questionEs: '¿Cuál era la característica física de Sansón que le daba su fuerza?',
    options: ['Sus músculos', 'Sus cabellos largos', 'Su estatura', 'Sus ojos'],
    correctIndex: 1,
  },
  {
    id: 'pe_018',
    category: 'personajes',
    questionEs: '¿Quién fue el esposo de Rut?',
    options: ['Elimelec', 'Booz', 'Mahlon', 'Quilión'],
    correctIndex: 1,
  },
  {
    id: 'pe_019',
    category: 'personajes',
    questionEs: '¿Cuál era el nombre original de Pablo antes de su conversión?',
    options: ['Simón', 'Lucas', 'Saulo', 'Marcos'],
    correctIndex: 2,
  },
  {
    id: 'pe_020',
    category: 'personajes',
    questionEs: '¿Quién fue el padre de Juan el Bautista?',
    options: ['Simeón', 'José', 'Zacarías', 'Cleofás'],
    correctIndex: 2,
  },
  {
    id: 'pe_021',
    category: 'personajes',
    questionEs: '¿Quién era la madre de Juan el Bautista?',
    options: ['Ana', 'María', 'Elisabet', 'Rebeca'],
    correctIndex: 2,
  },
  {
    id: 'pe_022',
    category: 'personajes',
    questionEs: '¿Cuántos años tenía Abraham cuando nació Isaac?',
    options: ['70 años', '80 años', '90 años', '100 años'],
    correctIndex: 3,
  },
  {
    id: 'pe_023',
    category: 'personajes',
    questionEs: '¿Quién fue el primer sumo sacerdote de Israel?',
    options: ['Moisés', 'Aarón', 'Leví', 'Fineas'],
    correctIndex: 1,
  },
  {
    id: 'pe_024',
    category: 'personajes',
    questionEs: '¿A qué personaje le fue probada la fe pidiéndole sacrificar a su hijo?',
    options: ['Isaac', 'Jacob', 'Abraham', 'Job'],
    correctIndex: 2,
  },
  {
    id: 'pe_025',
    category: 'personajes',
    questionEs: '¿Cuántos hijos tenía Job al final de su historia (después del período de prueba)?',
    options: ['Los mismos 10', '7 hijos y 3 hijas', '10 hijos y 10 hijas', '14 hijos'],
    correctIndex: 1,
  },
  {
    id: 'pe_026',
    category: 'personajes',
    questionEs: '¿Quién fue el compañero de Daniel en Babilonia que también fue arrojado al horno de fuego?',
    options: ['Sadrac, Mesac y Abednego', 'Azarías, Misael y Ananías (los tres amigos)', 'Son los mismos que la pregunta anterior', 'Todos son correctos'],
    correctIndex: 3,
  },
  {
    id: 'pe_027',
    category: 'personajes',
    questionEs: '¿Cómo se llamaba el amigo íntimo del rey David que era hijo del rey Saúl?',
    options: ['Absalón', 'Mefiboset', 'Jonatán', 'Isbaal'],
    correctIndex: 2,
  },
  {
    id: 'pe_028',
    category: 'personajes',
    questionEs: '¿Quién era el primo de Mardoqueo que llegó a ser reina de Persia?',
    options: ['Rut', 'Débora', 'Ester', 'Miriam'],
    correctIndex: 2,
  },
  {
    id: 'pe_029',
    category: 'personajes',
    questionEs: '¿Qué personaje del AT fue llamado "varón perfecto e íntegro" por Dios?',
    options: ['Abraham', 'Noé', 'Job', 'Enoc'],
    correctIndex: 2,
  },
  {
    id: 'pe_030',
    category: 'personajes',
    questionEs: '¿De qué tribu era el apóstol Pablo?',
    options: ['Judá', 'Leví', 'Benjamín', 'Efraín'],
    correctIndex: 2,
  },
  {
    id: 'pe_031',
    category: 'personajes',
    questionEs: '¿Qué personaje bíblico fue "arrebatado" por Dios sin morir, antes del diluvio?',
    options: ['Noé', 'Elías', 'Enoc', 'Moisés'],
    correctIndex: 2,
  },
  {
    id: 'pe_032',
    category: 'personajes',
    questionEs: '¿Quién fue el suegro de Moisés que le enseñó a delegar autoridad?',
    options: ['Jetro', 'Raguel', 'Hobab', 'Amós'],
    correctIndex: 0,
  },
  {
    id: 'pe_033',
    category: 'personajes',
    questionEs: '¿Cuántos años tenía Moisés cuando Dios lo llamó desde la zarza ardiente?',
    options: ['40 años', '60 años', '80 años', '100 años'],
    correctIndex: 2,
  },
  {
    id: 'pe_034',
    category: 'personajes',
    questionEs: '¿Quién fue la esposa de Abraham antes de llamarse Sara?',
    options: ['Agar', 'Sarai', 'Tamar', 'Rebeca'],
    correctIndex: 1,
  },
  {
    id: 'pe_035',
    category: 'personajes',
    questionEs: '¿Cuál fue el nombre que Dios le puso a Jacob?',
    options: ['Abraham', 'Isaac', 'Israel', 'Judá'],
    correctIndex: 2,
  },
  {
    id: 'pe_036',
    category: 'personajes',
    questionEs: '¿Qué apóstol fue el primero en declarar que Jesús era "el Cristo, el Hijo de Dios vivo"?',
    options: ['Juan', 'Santiago', 'Andrés', 'Pedro'],
    correctIndex: 3,
  },
  {
    id: 'pe_037',
    category: 'personajes',
    questionEs: '¿Quién fue la primera cristiana de Europa, convertida por Pablo?',
    options: ['Priscila', 'Lidia', 'Febe', 'Eunice'],
    correctIndex: 1,
  },
  {
    id: 'pe_038',
    category: 'personajes',
    questionEs: '¿Cómo se llamaba el hermano de Moisés?',
    options: ['Josué', 'Aarón', 'Caleb', 'Fineas'],
    correctIndex: 1,
  },
  {
    id: 'pe_039',
    category: 'personajes',
    questionEs: '¿Quién fue la hermana de Moisés y Aarón?',
    options: ['Débora', 'Miriam', 'Ester', 'Rut'],
    correctIndex: 1,
  },
  {
    id: 'pe_040',
    category: 'personajes',
    questionEs: '¿Cuál era el nombre de la esposa de Lot que se convirtió en estatua de sal?',
    options: ['La Biblia no da su nombre', 'Sara', 'Edna', 'Milca'],
    correctIndex: 0,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // VERSÍCULOS CONOCIDOS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 've_001',
    category: 'versiculos',
    questionEs: '¿Qué versículo dice "Todo lo puedo en Cristo que me fortalece"?',
    options: ['Romanos 8:28', 'Filipenses 4:13', 'Juan 3:16', 'Salmo 23:1'],
    correctIndex: 1,
  },
  {
    id: 've_002',
    category: 'versiculos',
    questionEs: '¿Cómo comienza el Salmo 23?',
    options: ['"Bendito sea el Señor"', '"El Señor es mi pastor"', '"Porque de tal manera amó Dios"', '"Toda la Escritura es útil"'],
    correctIndex: 1,
  },
  {
    id: 've_003',
    category: 'versiculos',
    questionEs: '¿Qué libro comienza con "En el principio creó Dios los cielos y la tierra"?',
    options: ['Job', 'Salmos', 'Génesis', 'Juan'],
    correctIndex: 2,
  },
  {
    id: 've_004',
    category: 'versiculos',
    questionEs: '¿Qué versículo dice "Porque tanto amó Dios al mundo que dio a su Hijo unigénito"?',
    options: ['Juan 1:1', 'Juan 3:16', 'Juan 14:6', 'Romanos 5:8'],
    correctIndex: 1,
  },
  {
    id: 've_005',
    category: 'versiculos',
    questionEs: '¿Qué versículo dice "Yo soy el camino, la verdad y la vida"?',
    options: ['Juan 10:10', 'Juan 11:25', 'Juan 14:6', 'Juan 15:5'],
    correctIndex: 2,
  },
  {
    id: 've_006',
    category: 'versiculos',
    questionEs: '¿Dónde se encuentra el versículo "La fe es la certeza de lo que se espera"?',
    options: ['Romanos 10:17', 'Hebreos 11:1', 'Santiago 2:17', '1 Corintios 13:13'],
    correctIndex: 1,
  },
  {
    id: 've_007',
    category: 'versiculos',
    questionEs: '¿Qué versículo dice "El Señor es mi luz y mi salvación, ¿a quién temeré"?',
    options: ['Salmo 23:1', 'Salmo 27:1', 'Salmo 46:1', 'Salmo 91:1'],
    correctIndex: 1,
  },
  {
    id: 've_008',
    category: 'versiculos',
    questionEs: '¿Qué libro contiene el versículo "Para todo hay una estación"?',
    options: ['Proverbios', 'Salmos', 'Eclesiastés', 'Job'],
    correctIndex: 2,
  },
  {
    id: 've_009',
    category: 'versiculos',
    questionEs: '¿Cuál es el versículo más corto de la Biblia?',
    options: ['"Dios es amor"', '"Jesús lloró"', '"Orad sin cesar"', '"No temáis"'],
    correctIndex: 1,
  },
  {
    id: 've_010',
    category: 'versiculos',
    questionEs: '¿En qué libro se encuentra "Porque yo sé los planes que tengo para vosotros, dice el Señor"?',
    options: ['Isaías 29', 'Jeremías 29', 'Ezequiel 29', 'Proverbios 29'],
    correctIndex: 1,
  },
  {
    id: 've_011',
    category: 'versiculos',
    questionEs: '¿Qué versículo dice "Encomienda al Señor tu camino; confía en Él"?',
    options: ['Proverbios 3:5-6', 'Salmo 37:5', 'Filipenses 4:6', 'Romanos 8:28'],
    correctIndex: 1,
  },
  {
    id: 've_012',
    category: 'versiculos',
    questionEs: '¿Dónde se encuentra la frase "El amor es sufrido, es benigno"?',
    options: ['1 Corintios 13', 'Romanos 8', 'Juan 15', 'Efesios 5'],
    correctIndex: 0,
  },
  {
    id: 've_013',
    category: 'versiculos',
    questionEs: '¿Qué libro contiene el versículo "En el principio era el Verbo, y el Verbo era con Dios"?',
    options: ['Génesis 1', 'Juan 1', 'Proverbios 8', 'Isaías 1'],
    correctIndex: 1,
  },
  {
    id: 've_014',
    category: 'versiculos',
    questionEs: '¿Dónde dice la Biblia "No os conforméis a este siglo"?',
    options: ['Efesios 4:22', 'Colosenses 3:10', 'Romanos 12:2', 'Gálatas 5:16'],
    correctIndex: 2,
  },
  {
    id: 've_015',
    category: 'versiculos',
    questionEs: '¿Qué versículo dice "Pedid y se os dará; buscad y hallaréis"?',
    options: ['Juan 14:13', 'Mateo 7:7', 'Lucas 11:9', 'Mateo 7:7 y Lucas 11:9'],
    correctIndex: 3,
  },
  {
    id: 've_016',
    category: 'versiculos',
    questionEs: '¿En qué libro se dice "Bienaventurados los pobres en espíritu"?',
    options: ['Lucas 6', 'Mateo 5', 'Juan 3', 'Marcos 1'],
    correctIndex: 1,
  },
  {
    id: 've_017',
    category: 'versiculos',
    questionEs: '¿Qué dice Proverbios 22:6?',
    options: ['"El que halla esposa halla algo bueno"', '"Instruye al niño en su camino"', '"La mujer virtuosa corona a su marido"', '"El necio habla sin pensar"'],
    correctIndex: 1,
  },
  {
    id: 've_018',
    category: 'versiculos',
    questionEs: '¿Dónde aparece la promesa "Si mi pueblo se humillare y orare"?',
    options: ['2 Crónicas 7:14', '2 Samuel 7:14', 'Nehemías 7:14', 'Esdras 7:14'],
    correctIndex: 0,
  },
  {
    id: 've_019',
    category: 'versiculos',
    questionEs: '¿Qué versículo dice "Porque somos hechura suya, creados en Cristo Jesús"?',
    options: ['Colosenses 1:16', 'Efesios 2:10', 'Romanos 9:21', '1 Pedro 2:9'],
    correctIndex: 1,
  },
  {
    id: 've_020',
    category: 'versiculos',
    questionEs: '¿Qué dice Santiago 1:5 sobre la sabiduría?',
    options: ['Que viene del estudio', 'Que si alguien la pide a Dios, Él la da generosamente', 'Que solo los sabios la pueden recibir', 'Que es el mayor don espiritual'],
    correctIndex: 1,
  },
  {
    id: 've_021',
    category: 'versiculos',
    questionEs: '¿Cuál es el Salmo que empieza "¿Hasta cuándo, Señor, me olvidarás para siempre"?',
    options: ['Salmo 10', 'Salmo 13', 'Salmo 22', 'Salmo 88'],
    correctIndex: 1,
  },
  {
    id: 've_022',
    category: 'versiculos',
    questionEs: '¿Qué versículo dice "Amarás al Señor tu Dios con todo tu corazón"?',
    options: ['Deuteronomio 6:5', 'Levítico 19:18', 'Éxodo 20:3', 'Números 15:40'],
    correctIndex: 0,
  },
  {
    id: 've_023',
    category: 'versiculos',
    questionEs: '¿En qué versículo se dice "La paga del pecado es muerte, pero la dádiva de Dios es vida eterna"?',
    options: ['Romanos 3:23', 'Romanos 6:23', 'Romanos 8:1', 'Romanos 10:9'],
    correctIndex: 1,
  },
  {
    id: 've_024',
    category: 'versiculos',
    questionEs: '¿Qué dice Apocalipsis 3:20?',
    options: ['Que Jesús viene pronto', '"He aquí, yo estoy a la puerta y llamo"', 'Que el diablo será atado', 'Que los vencedores reinarán'],
    correctIndex: 1,
  },
  {
    id: 've_025',
    category: 'versiculos',
    questionEs: '¿Qué versículo dice "Yo soy la resurrección y la vida"?',
    options: ['Juan 10:10', 'Juan 11:25', 'Juan 14:6', 'Juan 20:31'],
    correctIndex: 1,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ANTIGUO TESTAMENTO
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'at_001',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos días tardó Dios en crear el mundo según Génesis?',
    options: ['5 días', '6 días', '7 días', '10 días'],
    correctIndex: 1,
  },
  {
    id: 'at_002',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántas plagas envió Dios sobre Egipto?',
    options: ['7', '8', '10', '12'],
    correctIndex: 2,
  },
  {
    id: 'at_003',
    category: 'antiguo_testamento',
    questionEs: '¿Qué árbol no podían comer Adán y Eva en el Edén?',
    options: ['El árbol de la vida', 'El árbol del conocimiento del bien y del mal', 'El árbol de los olivos', 'El árbol de la sabiduría'],
    correctIndex: 1,
  },
  {
    id: 'at_004',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos años pasó el pueblo de Israel en el desierto?',
    options: ['20 años', '30 años', '40 años', '50 años'],
    correctIndex: 2,
  },
  {
    id: 'at_005',
    category: 'antiguo_testamento',
    questionEs: '¿En qué monte recibió Moisés los Diez Mandamientos?',
    options: ['Monte Sión', 'Monte Carmelo', 'Monte Sinaí', 'Monte Hermón'],
    correctIndex: 2,
  },
  {
    id: 'at_006',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos libros tiene el Antiguo Testamento?',
    options: ['27', '33', '39', '46'],
    correctIndex: 2,
  },
  {
    id: 'at_007',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos días duró el diluvio universal según Génesis?',
    options: ['20 días', '40 días', '40 noches y 40 días', '100 días'],
    correctIndex: 2,
  },
  {
    id: 'at_008',
    category: 'antiguo_testamento',
    questionEs: '¿En qué monte descansó el arca de Noé después del diluvio?',
    options: ['Monte Sinaí', 'Monte Hermón', 'Monte Ararat', 'Monte Carmel'],
    correctIndex: 2,
  },
  {
    id: 'at_009',
    category: 'antiguo_testamento',
    questionEs: '¿Cuál fue la primera plaga que envió Dios sobre Egipto?',
    options: ['Ranas', 'El agua se convirtió en sangre', 'Langostas', 'Tinieblas'],
    correctIndex: 1,
  },
  {
    id: 'at_010',
    category: 'antiguo_testamento',
    questionEs: '¿Cuál fue la décima y última plaga de Egipto?',
    options: ['Langostas', 'Tinieblas', 'Muerte de los primogénitos', 'Granizo'],
    correctIndex: 2,
  },
  {
    id: 'at_011',
    category: 'antiguo_testamento',
    questionEs: '¿Qué símbolo puso Dios en el cielo como señal del pacto con Noé?',
    options: ['Una nube', 'Un arcoíris', 'Una estrella', 'El sol y la luna'],
    correctIndex: 1,
  },
  {
    id: 'at_012',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántas personas entraron en el arca de Noé?',
    options: ['4', '6', '8', '12'],
    correctIndex: 2,
  },
  {
    id: 'at_013',
    category: 'antiguo_testamento',
    questionEs: '¿Cuál es el libro más largo del Antiguo Testamento?',
    options: ['Génesis', 'Números', 'Isaías', 'Salmos'],
    correctIndex: 3,
  },
  {
    id: 'at_014',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos libros de Moisés (Pentateuco) hay?',
    options: ['3', '4', '5', '6'],
    correctIndex: 2,
  },
  {
    id: 'at_015',
    category: 'antiguo_testamento',
    questionEs: '¿Qué ley dio Dios a Israel en el Monte Sinaí?',
    options: ['Los Diez Mandamientos', 'El Libro del Pacto', 'Las Leyes Levíticas', 'Todos los anteriores'],
    correctIndex: 3,
  },
  {
    id: 'at_016',
    category: 'antiguo_testamento',
    questionEs: '¿Cuál es el primer libro de la Biblia?',
    options: ['Éxodo', 'Levítico', 'Génesis', 'Deuteronomio'],
    correctIndex: 2,
  },
  {
    id: 'at_017',
    category: 'antiguo_testamento',
    questionEs: '¿Qué ciudad intentó construir la humanidad para alcanzar el cielo?',
    options: ['Babilonia', 'La Torre de Babel', 'Nínive', 'Sodoma'],
    correctIndex: 1,
  },
  {
    id: 'at_018',
    category: 'antiguo_testamento',
    questionEs: '¿Qué ciudad fue destruida junto con Sodoma?',
    options: ['Nínive', 'Tiro', 'Gomorra', 'Zoar'],
    correctIndex: 2,
  },
  {
    id: 'at_019',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántas tribus de Israel hubo después de la división del reino?',
    options: ['10 en el norte y 2 en el sur', '11 en el norte y 1 en el sur', '6 en el norte y 6 en el sur', '9 en el norte y 3 en el sur'],
    correctIndex: 0,
  },
  {
    id: 'at_020',
    category: 'antiguo_testamento',
    questionEs: '¿Qué libro del AT contiene la historia del regreso de los judíos del exilio babilónico?',
    options: ['Esdras', 'Nehemías', 'Esdras y Nehemías', 'Esther'],
    correctIndex: 2,
  },
  {
    id: 'at_021',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos salmos tiene el libro de Salmos?',
    options: ['100', '120', '150', '175'],
    correctIndex: 2,
  },
  {
    id: 'at_022',
    category: 'antiguo_testamento',
    questionEs: '¿Quién escribió la mayoría de los Salmos?',
    options: ['Asaf', 'Salomón', 'Moisés', 'David'],
    correctIndex: 3,
  },
  {
    id: 'at_023',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos capítulos tiene el libro de Proverbios?',
    options: ['25', '27', '30', '31'],
    correctIndex: 3,
  },
  {
    id: 'at_024',
    category: 'antiguo_testamento',
    questionEs: '¿Qué libro del AT habla exclusivamente sobre los sufrimientos de un hombre justo?',
    options: ['Eclesiastés', 'Job', 'Lamentaciones', 'Proverbios'],
    correctIndex: 1,
  },
  {
    id: 'at_025',
    category: 'antiguo_testamento',
    questionEs: '¿Cuál fue el primer pecado registrado en la Biblia?',
    options: ['El asesinato de Abel', 'La desobediencia de Adán y Eva', 'La construcción de la torre de Babel', 'La idolatría del becerro de oro'],
    correctIndex: 1,
  },
  {
    id: 'at_026',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos días estuvo Moisés en el monte Sinaí recibiendo la ley?',
    options: ['20 días', '30 días', '40 días', '50 días'],
    correctIndex: 2,
  },
  {
    id: 'at_027',
    category: 'antiguo_testamento',
    questionEs: '¿Qué tribu de Israel fue separada para el servicio sacerdotal?',
    options: ['Judá', 'Benjamín', 'Leví', 'Efraín'],
    correctIndex: 2,
  },
  {
    id: 'at_028',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos libros históricos hay en el Antiguo Testamento?',
    options: ['9', '12', '15', '17'],
    correctIndex: 1,
  },
  {
    id: 'at_029',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos profetas menores hay en el Antiguo Testamento?',
    options: ['10', '12', '14', '15'],
    correctIndex: 1,
  },
  {
    id: 'at_030',
    category: 'antiguo_testamento',
    questionEs: '¿Qué fiesta conmemoraba la liberación de Egipto?',
    options: ['Pentecostés', 'La Pascua', 'Los Tabernáculos', 'El Año Nuevo Judío'],
    correctIndex: 1,
  },
  {
    id: 'at_031',
    category: 'antiguo_testamento',
    questionEs: '¿Dónde se guardaba el Arca del Pacto?',
    options: ['En el palacio real', 'En el lugar santísimo del tabernáculo y el templo', 'En las tiendas de los levitas', 'En la ciudad de David'],
    correctIndex: 1,
  },
  {
    id: 'at_032',
    category: 'antiguo_testamento',
    questionEs: '¿Qué contenía el Arca del Pacto?',
    options: ['Las tablas de la ley, el maná y la vara de Aarón', 'Solo las tablas de la ley', 'Los rollos de los profetas', 'Los objetos del tabernáculo'],
    correctIndex: 0,
  },
  {
    id: 'at_033',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos capítulos tiene el libro de Génesis?',
    options: ['40', '48', '50', '52'],
    correctIndex: 2,
  },
  {
    id: 'at_034',
    category: 'antiguo_testamento',
    questionEs: '¿Qué animal habló con Eva en el jardín del Edén?',
    options: ['Un ángel caído', 'La serpiente', 'Un dragón', 'Un querubín'],
    correctIndex: 1,
  },
  {
    id: 'at_035',
    category: 'antiguo_testamento',
    questionEs: '¿De qué fue hecho Adán según Génesis?',
    options: ['De luz divina', 'Del polvo de la tierra', 'Del barro del río', 'De agua y tierra'],
    correctIndex: 1,
  },
  {
    id: 'at_036',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos años vivió Adán según la Biblia?',
    options: ['700 años', '800 años', '930 años', '1000 años'],
    correctIndex: 2,
  },
  {
    id: 'at_037',
    category: 'antiguo_testamento',
    questionEs: '¿Qué hizo Dios el séptimo día de la creación?',
    options: ['Creó al hombre', 'Descansó', 'Creó los ángeles', 'Estableció el pacto con Adán'],
    correctIndex: 1,
  },
  {
    id: 'at_038',
    category: 'antiguo_testamento',
    questionEs: '¿A quién protegió Dios con una marca para que nadie lo matara después de su crimen?',
    options: ['Abel', 'Set', 'Caín', 'Lamec'],
    correctIndex: 2,
  },
  {
    id: 'at_039',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos animales de cada especie impura llevó Noé al arca?',
    options: ['1 pareja (2)', '2 parejas (4)', '3 parejas (6)', '7 parejas (14)'],
    correctIndex: 0,
  },
  {
    id: 'at_040',
    category: 'antiguo_testamento',
    questionEs: '¿Cuántos animales de cada especie pura llevó Noé al arca?',
    options: ['1 pareja', '3 parejas', '7 parejas', '12 parejas'],
    correctIndex: 2,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // NUEVO TESTAMENTO
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'nt_001',
    category: 'nuevo_testamento',
    questionEs: '¿Cuántos Evangelios hay en el Nuevo Testamento?',
    options: ['3', '4', '5', '6'],
    correctIndex: 1,
  },
  {
    id: 'nt_002',
    category: 'nuevo_testamento',
    questionEs: '¿Quién escribió el libro de Apocalipsis?',
    options: ['Pedro', 'Pablo', 'Juan', 'Santiago'],
    correctIndex: 2,
  },
  {
    id: 'nt_003',
    category: 'nuevo_testamento',
    questionEs: '¿Cuántas cartas (epístolas) escribió Pablo en el Nuevo Testamento?',
    options: ['10', '13', '14', '7'],
    correctIndex: 1,
  },
  {
    id: 'nt_004',
    category: 'nuevo_testamento',
    questionEs: '¿En qué ciudad ocurrió Pentecostés, cuando descendió el Espíritu Santo?',
    options: ['Belén', 'Nazaret', 'Jerusalén', 'Antioquía'],
    correctIndex: 2,
  },
  {
    id: 'nt_005',
    category: 'nuevo_testamento',
    questionEs: '¿Cómo se llamaba el apóstol que dudó de la resurrección de Jesús?',
    options: ['Mateo', 'Marcos', 'Tomás', 'Felipe'],
    correctIndex: 2,
  },
  {
    id: 'nt_006',
    category: 'nuevo_testamento',
    questionEs: '¿Cuántos libros tiene el Nuevo Testamento?',
    options: ['24', '25', '27', '29'],
    correctIndex: 2,
  },
  {
    id: 'nt_007',
    category: 'nuevo_testamento',
    questionEs: '¿En qué isla estuvo el apóstol Juan cuando recibió las visiones del Apocalipsis?',
    options: ['Chipre', 'Patmos', 'Creta', 'Malta'],
    correctIndex: 1,
  },
  {
    id: 'nt_008',
    category: 'nuevo_testamento',
    questionEs: '¿Cuál fue la última cena que Jesús compartió con sus apóstoles?',
    options: ['La Cena de Bodas', 'La Última Cena de Pascua', 'La Fiesta del Tabernáculo', 'El Banquete de Jericó'],
    correctIndex: 1,
  },
  {
    id: 'nt_009',
    category: 'nuevo_testamento',
    questionEs: '¿Cuál es el primer libro del Nuevo Testamento?',
    options: ['Marcos', 'Lucas', 'Mateo', 'Juan'],
    correctIndex: 2,
  },
  {
    id: 'nt_010',
    category: 'nuevo_testamento',
    questionEs: '¿Cuál es el libro más largo del Nuevo Testamento?',
    options: ['Mateo', 'Juan', 'Hechos', 'Lucas'],
    correctIndex: 3,
  },
  {
    id: 'nt_011',
    category: 'nuevo_testamento',
    questionEs: '¿A qué iglesia dirigió Pablo la carta más larga del NT?',
    options: ['Los corintios', 'Los romanos', 'Los gálatas', 'Los efesios'],
    correctIndex: 1,
  },
  {
    id: 'nt_012',
    category: 'nuevo_testamento',
    questionEs: '¿Cuántos hombres fueron elegidos para servir las mesas en Hechos 6?',
    options: ['5', '7', '10', '12'],
    correctIndex: 1,
  },
  {
    id: 'nt_013',
    category: 'nuevo_testamento',
    questionEs: '¿Cómo se llamó el primer nombre que recibió el conjunto de seguidores de Jesús?',
    options: ['Nazarenos', 'Galileos', 'Cristinos', 'Cristianos'],
    correctIndex: 3,
  },
  {
    id: 'nt_014',
    category: 'nuevo_testamento',
    questionEs: '¿Dónde fueron llamados "cristianos" los seguidores de Jesús por primera vez?',
    options: ['Jerusalén', 'Roma', 'Antioquía', 'Éfeso'],
    correctIndex: 2,
  },
  {
    id: 'nt_015',
    category: 'nuevo_testamento',
    questionEs: '¿Cuántos viajes misioneros realizó Pablo?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1,
  },
  {
    id: 'nt_016',
    category: 'nuevo_testamento',
    questionEs: '¿Quién fue el primer gentil convertido al cristianismo mencionado en Hechos?',
    options: ['El etíope eunuco', 'Cornelio', 'Lidia', 'El carcelero de Filipos'],
    correctIndex: 1,
  },
  {
    id: 'nt_017',
    category: 'nuevo_testamento',
    questionEs: '¿Cuántos ancianos rodeaban el trono de Dios en la visión de Apocalipsis 4?',
    options: ['12', '14', '24', '144'],
    correctIndex: 2,
  },
  {
    id: 'nt_018',
    category: 'nuevo_testamento',
    questionEs: '¿Qué número lleva la "marca de la bestia" en Apocalipsis?',
    options: ['666', '777', '888', '616'],
    correctIndex: 0,
  },
  {
    id: 'nt_019',
    category: 'nuevo_testamento',
    questionEs: '¿A cuántas iglesias de Asia Menor se dirigen los mensajes en Apocalipsis 2-3?',
    options: ['5', '7', '10', '12'],
    correctIndex: 1,
  },
  {
    id: 'nt_020',
    category: 'nuevo_testamento',
    questionEs: '¿En qué libro del NT se narra el viaje y naufragio de Pablo en Malta?',
    options: ['Romanos', 'Gálatas', 'Hechos', '2 Corintios'],
    correctIndex: 2,
  },
  {
    id: 'nt_021',
    category: 'nuevo_testamento',
    questionEs: '¿Cuántos evangelistas (escritores de los Evangelios) hay?',
    options: ['2', '3', '4', '5'],
    correctIndex: 2,
  },
  {
    id: 'nt_022',
    category: 'nuevo_testamento',
    questionEs: '¿Quién escribió el Evangelio de Lucas y el libro de Hechos?',
    options: ['Pablo', 'Lucas', 'Marcos', 'Bernabé'],
    correctIndex: 1,
  },
  {
    id: 'nt_023',
    category: 'nuevo_testamento',
    questionEs: '¿Cuál es el evangelio más corto?',
    options: ['Mateo', 'Marcos', 'Lucas', 'Juan'],
    correctIndex: 1,
  },
  {
    id: 'nt_024',
    category: 'nuevo_testamento',
    questionEs: '¿Cómo se llama el libro que describe los viajes misioneros y la iglesia primitiva?',
    options: ['Epístola a los Hebreos', 'Hechos de los Apóstoles', 'Cartas Pastorales', 'El libro de las Misiones'],
    correctIndex: 1,
  },
  {
    id: 'nt_025',
    category: 'nuevo_testamento',
    questionEs: '¿Cuántos "frutos del Espíritu" lista Pablo en Gálatas 5?',
    options: ['7', '9', '10', '12'],
    correctIndex: 1,
  },
  {
    id: 'nt_026',
    category: 'nuevo_testamento',
    questionEs: '¿Cuál es el primer fruto del Espíritu mencionado en Gálatas 5?',
    options: ['Paz', 'Gozo', 'Amor', 'Paciencia'],
    correctIndex: 2,
  },
  {
    id: 'nt_027',
    category: 'nuevo_testamento',
    questionEs: '¿Cuántos dones espirituales lista Pablo en 1 Corintios 12?',
    options: ['7', '9', '12', '14'],
    correctIndex: 1,
  },
  {
    id: 'nt_028',
    category: 'nuevo_testamento',
    questionEs: '¿Cuáles son las tres virtudes permanentes que menciona Pablo en 1 Corintios 13?',
    options: ['Fe, esperanza y amor', 'Fe, oración y obediencia', 'Amor, justicia y paz', 'Esperanza, gracia y verdad'],
    correctIndex: 0,
  },
  {
    id: 'nt_029',
    category: 'nuevo_testamento',
    questionEs: '¿Quién le preguntó a Jesús "¿Qué es la verdad?" antes de su crucifixión?',
    options: ['Herodes', 'Caifás', 'Poncio Pilato', 'Los fariseos'],
    correctIndex: 2,
  },
  {
    id: 'nt_030',
    category: 'nuevo_testamento',
    questionEs: '¿Qué hizo Pablo en la sinagoga de Tesalónica según Hechos 17?',
    options: ['Sanó enfermos', 'Razonó sobre las Escrituras por tres días de reposo', 'Fue arrestado', 'Fundó la primera iglesia'],
    correctIndex: 1,
  },
  {
    id: 'nt_031',
    category: 'nuevo_testamento',
    questionEs: '¿Qué dijo Jesús que era "la primera y más grande" ley?',
    options: ['No matarás', 'Amarás al Señor tu Dios', 'Amarás a tu prójimo', 'Honrarás a tus padres'],
    correctIndex: 1,
  },
  {
    id: 'nt_032',
    category: 'nuevo_testamento',
    questionEs: '¿Cuántas veces intentaron apedrear a Jesús antes de su crucifixión según Juan?',
    options: ['1 vez', '2 veces', '3 veces', '4 veces'],
    correctIndex: 1,
  },
  {
    id: 'nt_033',
    category: 'nuevo_testamento',
    questionEs: '¿Cuántas palabras dijo Jesús desde la cruz?',
    options: ['5', '7', '8', '10'],
    correctIndex: 1,
  },
  {
    id: 'nt_034',
    category: 'nuevo_testamento',
    questionEs: '¿Con qué Jesús comparó el reino de los cielos en la parábola del grano de mostaza?',
    options: ['Con una semilla de lino', 'Con el grano de mostaza más pequeño que se convierte en árbol', 'Con el trigo que crece junto con la cizaña', 'Con la semilla que cae en buena tierra'],
    correctIndex: 1,
  },
  {
    id: 'nt_035',
    category: 'nuevo_testamento',
    questionEs: '¿Quién fue el sustituto que el pueblo pidió liberar en lugar de Jesús?',
    options: ['Simón', 'Barrabás', 'Gestas', 'Dimas'],
    correctIndex: 1,
  },
  {
    id: 'nt_036',
    category: 'nuevo_testamento',
    questionEs: '¿Cuál fue el idioma principal en que fue escrito el Nuevo Testamento?',
    options: ['Latín', 'Hebreo', 'Arameo', 'Griego koiné'],
    correctIndex: 3,
  },
  {
    id: 'nt_037',
    category: 'nuevo_testamento',
    questionEs: '¿En qué ciudad fue arrestado Pablo por última vez antes de ser llevado a Roma?',
    options: ['Antioquía', 'Éfeso', 'Jerusalén', 'Corinto'],
    correctIndex: 2,
  },
  {
    id: 'nt_038',
    category: 'nuevo_testamento',
    questionEs: '¿Cuántos años estuvo Pablo en Roma en su primer arresto domiciliario?',
    options: ['1 año', '2 años', '3 años', '5 años'],
    correctIndex: 1,
  },
  {
    id: 'nt_039',
    category: 'nuevo_testamento',
    questionEs: '¿Quién acompañó a Pablo en su segundo viaje misionero?',
    options: ['Bernabé', 'Silas', 'Timoteo', 'Silas y Timoteo'],
    correctIndex: 3,
  },
  {
    id: 'nt_040',
    category: 'nuevo_testamento',
    questionEs: '¿A qué se refiere "la nueva Jerusalén" en el libro de Apocalipsis?',
    options: ['La Jerusalén reconstruida', 'La ciudad celestial que desciende del cielo', 'El templo reconstruido de Herodes', 'El Israel espiritual'],
    correctIndex: 1,
  },
];

// ─── Utility Functions ──────────────────────────────────────────────────────────

/**
 * Returns a shuffled selection of questions for a duel.
 * Supports anti-repetition: excludes recently-used question IDs when possible.
 * If the pool after exclusion is too small, it falls back to the full pool.
 */
export function getRandomDuelQuestions(
  count = 10,
  excludeIds: string[] = []
): DuelQuestion[] {
  const MIN_AVAILABLE = count + 5; // Keep at least a small buffer

  // Try filtered pool first
  const filtered = DUEL_QUESTIONS.filter(q => !excludeIds.includes(q.id));

  const pool = filtered.length >= MIN_AVAILABLE ? filtered : DUEL_QUESTIONS;
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export const CATEGORY_LABELS_ES: Record<DuelCategory, string> = {
  vida_jesus: 'Vida de Jesús',
  milagros: 'Milagros',
  profetas: 'Profetas',
  reyes: 'Reyes',
  personajes: 'Personajes Bíblicos',
  versiculos: 'Versículos',
  antiguo_testamento: 'Antiguo Testamento',
  nuevo_testamento: 'Nuevo Testamento',
};
